const VOCAB_PART_4 = [
  { en: "living room", th: "ห้องนั่งเล่น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🛋️" },
  { en: "bedroom", th: "ห้องนอน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🛏️" },
  { en: "bathroom", th: "ห้องน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🚽" },
  { en: "kitchen", th: "ห้องครัว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🍳" },
  { en: "dining room", th: "ห้องรับประทานอาหาร", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "hallway", th: "ทางเดินในบ้าน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "corridor", th: "ระเบียงทางเดิน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "attic", th: "ห้องใต้หลังคา", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "basement", th: "ห้องใต้ดิน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "garage", th: "โรงรถ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🚗" },
  { en: "balcony", th: "ระเบียง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "terrace", th: "ลานระเบียง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "study room", th: "ห้องทำงาน/ห้องอ่านหนังสือ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "nursery", th: "ห้องเด็กอ่อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "laundry room", th: "ห้องซักผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "closet", th: "ตู้เสื้อผ้าฝังผนัง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "pantry", th: "ห้องเก็บอาหาร", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "garden", th: "สวน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🌳" },
  { en: "yard", th: "สนามหญ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "porch", th: "ระเบียงหน้าบ้าน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "staircase", th: "บันได", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "ceiling", th: "เพดาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "floor", th: "พื้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "wall", th: "ผนัง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "roof", th: "หลังคา", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🏠" },
  { en: "window", th: "หน้าต่าง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "door", th: "ประตู", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🚪" },
  { en: "doorway", th: "ช่องประตู", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "fence", th: "รั้ว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "gate", th: "ประตูรั้ว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "driveway", th: "ทางเข้าบ้าน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "chimney", th: "ปล่องไฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "foundation", th: "ฐานราก", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "sofa", th: "โซฟา", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🛋️" },
  { en: "couch", th: "เก้าอี้นวม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "armchair", th: "เก้าอี้แขน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "coffee table", th: "โต๊ะกลาง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "dining table", th: "โต๊ะอาหาร", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "chair", th: "เก้าอี้", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🪑" },
  { en: "bed", th: "เตียง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🛏️" },
  { en: "bunk bed", th: "เตียงสองชั้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "mattress", th: "ที่นอน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "pillow", th: "หมอน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "cushion", th: "เบาะรองนั่ง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "blanket", th: "ผ้าห่ม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "bookshelf", th: "ชั้นวางหนังสือ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "bookcase", th: "ตู้หนังสือ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "wardrobe", th: "ตู้เสื้อผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "cabinet", th: "ตู้เก็บของ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "drawer", th: "ลิ้นชัก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "dresser", th: "ตู้ลิ้นชักเสื้อผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "nightstand", th: "โต๊ะข้างเตียง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "desk", th: "โต๊ะทำงาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "stool", th: "เก้าอี้สตูล", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "bench", th: "ม้านั่ง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🪑" },
  { en: "rug", th: "พรมปูพื้นผืนเล็ก", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "carpet", th: "พรม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "curtain", th: "ผ้าม่าน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "mirror", th: "กระจก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🪞" },
  { en: "lamp", th: "โคมไฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "💡" },
  { en: "chandelier", th: "โคมไฟระย้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "ottoman", th: "เก้าอี้วางเท้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "cradle", th: "เปลเด็ก", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "shelf", th: "ชั้นวางของ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "hook", th: "ตะขอแขวน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "rack", th: "ราวแขวนของ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "refrigerator", th: "ตู้เย็น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🧊" },
  { en: "freezer", th: "ตู้แช่แข็ง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🧊" },
  { en: "oven", th: "เตาอบ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "microwave", th: "ไมโครเวฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "stove", th: "เตาไฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "dishwasher", th: "เครื่องล้างจาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "washing machine", th: "เครื่องซักผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🧺" },
  { en: "dryer", th: "เครื่องอบผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "air conditioner", th: "เครื่องปรับอากาศ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "❄️" },
  { en: "electric fan", th: "พัดลม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "heater", th: "เครื่องทำความร้อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "water heater", th: "เครื่องทำน้ำอุ่น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "vacuum cleaner", th: "เครื่องดูดฝุ่น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "iron", th: "เตารีด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "toaster", th: "เครื่องปิ้งขนมปัง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🍞" },
  { en: "blender", th: "เครื่องปั่น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "kettle", th: "กาต้มน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "rice cooker", th: "หม้อหุงข้าว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🍚" },
  { en: "coffee maker", th: "เครื่องชงกาแฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "☕" },
  { en: "television", th: "โทรทัศน์", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "📺" },
  { en: "air purifier", th: "เครื่องฟอกอากาศ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "humidifier", th: "เครื่องเพิ่มความชื้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "dehumidifier", th: "เครื่องลดความชื้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "water dispenser", th: "เครื่องกดน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "exhaust fan", th: "พัดลมดูดอากาศ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "pot", th: "หม้อ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🍲" },
  { en: "pan", th: "กระทะแบน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "frying pan", th: "กระทะทอด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "saucepan", th: "หม้อซอส", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "wok", th: "กระทะก้นลึก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "knife", th: "มีด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔪" },
  { en: "cutting board", th: "เขียง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "spatula", th: "ตะหลิว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "ladle", th: "ทัพพี", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "colander", th: "กระชอนกรอง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "strainer", th: "ที่กรอง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "bowl", th: "ชาม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🥣" },
  { en: "plate", th: "จาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🍽️" },
  { en: "dish", th: "จานอาหาร", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "cup", th: "ถ้วย", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "☕" },
  { en: "mug", th: "แก้วมัค", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "glass", th: "แก้วน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🥛" },
  { en: "fork", th: "ส้อม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🍴" },
  { en: "spoon", th: "ช้อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🥄" },
  { en: "chopsticks", th: "ตะเกียบ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🥢" },
  { en: "teapot", th: "กาน้ำชา", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "tray", th: "ถาด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "jar", th: "โหล", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "container", th: "ภาชนะเก็บของ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "lid", th: "ฝาปิด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "can opener", th: "ที่เปิดกระป๋อง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "peeler", th: "ที่ปอกเปลือก", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "grater", th: "ที่ขูด", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "rolling pin", th: "ไม้คลึงแป้ง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "oven mitt", th: "ถุงมือกันความร้อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "apron", th: "ผ้ากันเปื้อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "tablecloth", th: "ผ้าปูโต๊ะ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "napkin", th: "ผ้าเช็ดปาก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "thermos", th: "กระติกน้ำร้อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "food container", th: "กล่องใส่อาหาร", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🥡" },
  { en: "broom", th: "ไม้กวาด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🧹" },
  { en: "mop", th: "ไม้ถูพื้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "dustpan", th: "ที่โกยผง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "bucket", th: "ถัง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🪣" },
  { en: "sponge", th: "ฟองน้ำล้างจาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🧽" },
  { en: "detergent", th: "ผงซักฟอก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "bleach", th: "น้ำยาฟอกขาว", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "disinfectant", th: "น้ำยาฆ่าเชื้อ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "trash can", th: "ถังขยะ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🗑️" },
  { en: "garbage bag", th: "ถุงขยะ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "duster", th: "แปรงปัดฝุ่น", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "scrub brush", th: "แปรงขัด", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "rubber gloves", th: "ถุงมือยาง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🧤" },
  { en: "air freshener", th: "สเปรย์ปรับอากาศ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "cleaning cloth", th: "ผ้าเช็ดทำความสะอาด", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "vacuum bag", th: "ถุงเก็บฝุ่น", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "hammer", th: "ค้อน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔨" },
  { en: "screwdriver", th: "ไขควง", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🪛" },
  { en: "wrench", th: "ประแจ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "🔧" },
  { en: "pliers", th: "คีม", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "nail", th: "ตะปู", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "screw", th: "สกรู", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🔩" },
  { en: "drill", th: "สว่านไฟฟ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "ladder", th: "บันไดพาดขึ้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🪜" },
  { en: "toolbox", th: "กล่องเครื่องมือ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🧰" },
  { en: "tape measure", th: "สายวัด", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "flashlight", th: "ไฟฉาย", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔦" },
  { en: "extension cord", th: "ปลั๊กพ่วง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "light bulb", th: "หลอดไฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "💡" },
  { en: "socket", th: "เต้ารับไฟฟ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🔌" },
  { en: "switch", th: "สวิตช์ไฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "fuse", th: "ฟิวส์", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "plug", th: "ปลั๊กไฟ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔌" },
  { en: "battery", th: "ถ่านไฟฉาย", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔋" },
  { en: "paint", th: "สี", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🎨" },
  { en: "paintbrush", th: "แปรงทาสี", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "glue", th: "กาว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "adhesive tape", th: "เทปกาว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "rope", th: "เชือก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "saw", th: "เลื่อย", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "level tool", th: "เครื่องมือวัดระดับ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "doorbell", th: "กริ่งประตู", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🔔" },
  { en: "doormat", th: "พรมเช็ดเท้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "clothesline", th: "ราวตากผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "clothes hanger", th: "ไม้แขวนเสื้อ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "towel", th: "ผ้าเช็ดตัว", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "bath towel", th: "ผ้าเช็ดตัวผืนใหญ่", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "shower curtain", th: "ม่านห้องอาบน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "bathtub", th: "อ่างอาบน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🛁" },
  { en: "sink", th: "อ่างล้างจาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "faucet", th: "ก๊อกน้ำ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🚰" },
  { en: "toilet", th: "โถส้วม", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🚽" },
  { en: "toilet paper", th: "กระดาษชำระ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🧻" },
  { en: "soap", th: "สบู่", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🧼" },
  { en: "shampoo", th: "แชมพู", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "toothbrush", th: "แปรงสีฟัน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🪥" },
  { en: "toothpaste", th: "ยาสีฟัน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "" },
  { en: "fireplace", th: "เตาผิง", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "candle", th: "เทียนไข", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🕯️" },
  { en: "clock", th: "นาฬิกาแขวน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🕐" },
  { en: "picture frame", th: "กรอบรูป", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🖼️" },
  { en: "vase", th: "แจกัน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "" },
  { en: "houseplant", th: "ต้นไม้ประดับในบ้าน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "🪴" },
  { en: "key", th: "กุญแจ", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔑" },
  { en: "lock", th: "กลอนล็อก", category: "บ้านและเครื่องใช้ในบ้าน", level: "A1", emoji: "🔒" },
  { en: "doorknob", th: "ลูกบิดประตู", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "welcome mat", th: "พรมต้อนรับหน้าประตู", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "skylight", th: "หน้าต่างบนหลังคา", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "floor tile", th: "กระเบื้องปูพื้น", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "wallpaper", th: "วอลเปเปอร์", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "" },
  { en: "thermostat", th: "เครื่องควบคุมอุณหภูมิ", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "🌡️" },
  { en: "smoke detector", th: "เครื่องตรวจจับควัน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B2", emoji: "" },
  { en: "shirt", th: "เสื้อเชิ้ต", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👕" },
  { en: "t-shirt", th: "เสื้อยืด", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👕" },
  { en: "trousers", th: "กางเกงขายาว", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👖" },
  { en: "pants", th: "กางเกง", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👖" },
  { en: "jeans", th: "กางเกงยีนส์", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👖" },
  { en: "shorts", th: "กางเกงขาสั้น", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "skirt", th: "กระโปรง", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "dress", th: "ชุดเดรส", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👗" },
  { en: "blouse", th: "เสื้อเบลาส์", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "suit", th: "ชุดสูท", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "🤵" },
  { en: "jacket", th: "แจ็คเก็ต", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧥" },
  { en: "coat", th: "เสื้อโค้ท", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧥" },
  { en: "overcoat", th: "เสื้อโค้ทตัวยาว", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "raincoat", th: "เสื้อกันฝน", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "sweater", th: "เสื้อกันหนาว", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "cardigan", th: "เสื้อคาร์ดิแกน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "hoodie", th: "เสื้อฮู้ด", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "vest", th: "เสื้อกั๊ก", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "waistcoat", th: "เสื้อกั๊กสูท", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "blazer", th: "เสื้อสูทลำลอง", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "uniform", th: "ชุดยูนิฟอร์ม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "pajamas", th: "ชุดนอน", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "nightgown", th: "ชุดนอนสตรี", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "underwear", th: "กางเกงชั้นใน", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "boxer shorts", th: "กางเกงในชาย", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "bra", th: "เสื้อชั้นใน", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "socks", th: "ถุงเท้า", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧦" },
  { en: "stockings", th: "ถุงน่อง", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "tights", th: "ถุงน่องเลกกิ้ง", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "leggings", th: "กางเกงเลกกิ้ง", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "swimsuit", th: "ชุดว่ายน้ำ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "👙" },
  { en: "bikini", th: "ชุดว่ายน้ำบิกินี่", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "tracksuit", th: "ชุดวอร์ม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "apron dress", th: "ชุดกันเปื้อน", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "scarf", th: "ผ้าพันคอ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧣" },
  { en: "shawl", th: "ผ้าคลุมไหล่", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "gloves", th: "ถุงมือ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧤" },
  { en: "mittens", th: "ถุงมือแบบไม่มีนิ้ว", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "hat", th: "หมวก", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧢" },
  { en: "cap", th: "หมวกแก๊ป", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🧢" },
  { en: "beanie", th: "หมวกไหมพรม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "helmet", th: "หมวกกันน็อก", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "⛑️" },
  { en: "belt", th: "เข็มขัด", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "tie", th: "เนคไท", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👔" },
  { en: "bow tie", th: "หูกระต่าย", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "🎀" },
  { en: "shoes", th: "รองเท้า", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👞" },
  { en: "sneakers", th: "รองเท้าผ้าใบ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👟" },
  { en: "boots", th: "รองเท้าบูท", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🥾" },
  { en: "sandals", th: "รองเท้าแตะ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🩴" },
  { en: "slippers", th: "รองเท้าแตะในบ้าน", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🩴" },
  { en: "high heels", th: "รองเท้าส้นสูง", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "👠" },
  { en: "flip-flops", th: "รองเท้าแตะคีบ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "loafers", th: "รองเท้าไม่มีเชือก", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "flats", th: "รองเท้าส้นเตี้ย", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "socks and shoes", th: "ถุงเท้าและรองเท้า", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "necklace", th: "สร้อยคอ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "📿" },
  { en: "bracelet", th: "สร้อยข้อมือ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "earrings", th: "ต่างหู", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "ring", th: "แหวน", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "💍" },
  { en: "brooch", th: "เข็มกลัดประดับ", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "pendant", th: "จี้", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "anklet", th: "สร้อยข้อเท้า", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "cufflinks", th: "กระดุมข้อมือ", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "watch", th: "นาฬิกาข้อมือ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "⌚" },
  { en: "wristwatch", th: "นาฬิกาข้อมือ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "sunglasses", th: "แว่นกันแดด", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🕶️" },
  { en: "eyeglasses", th: "แว่นตา", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👓" },
  { en: "handbag", th: "กระเป๋าถือ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👜" },
  { en: "purse", th: "กระเป๋าสตางค์สตรี", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "wallet", th: "กระเป๋าสตางค์", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👛" },
  { en: "backpack", th: "กระเป๋าเป้", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "🎒" },
  { en: "briefcase", th: "กระเป๋าเอกสาร", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "💼" },
  { en: "suitcase", th: "กระเป๋าเดินทาง", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "🧳" },
  { en: "umbrella", th: "ร่ม", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "☂️" },
  { en: "hairpin", th: "กิ๊บติดผม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "hairband", th: "ที่คาดผม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "headband", th: "ผ้าคาดผม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "brooch pin", th: "เข็มกลัด", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "button", th: "กระดุม", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "zipper", th: "ซิป", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "collar", th: "ปกเสื้อ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "sleeve", th: "แขนเสื้อ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "hem", th: "ชายเสื้อ", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "pocket", th: "กระเป๋าเสื้อ", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "" },
  { en: "cotton", th: "ผ้าฝ้าย", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "silk", th: "ผ้าไหม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "wool", th: "ผ้าขนสัตว์", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "linen", th: "ผ้าลินิน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "leather", th: "หนัง", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "denim", th: "ผ้ายีนส์", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "polyester", th: "ผ้าใยสังเคราะห์", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "velvet", th: "ผ้ากำมะหยี่", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "satin", th: "ผ้าซาติน", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "nylon", th: "ผ้าไนลอน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "lace", th: "ผ้าลูกไม้", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "suede", th: "หนังกลับ", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "cashmere", th: "ผ้าแคชเมียร์", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "spandex", th: "ผ้ายืด", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "fleece", th: "ผ้าขนแกะสังเคราะห์", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "corduroy", th: "ผ้าลูกฟูก", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "overalls", th: "ชุดเอี๊ยม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "jumpsuit", th: "ชุดจั๊มสูท", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "turtleneck", th: "เสื้อคอเต่า", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "polo shirt", th: "เสื้อโปโล", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "tank top", th: "เสื้อกล้าม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "camisole", th: "เสื้อกล้ามบาง", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "gown", th: "ชุดราตรี", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👗" },
  { en: "tuxedo", th: "ชุดทักซิโด้", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "🤵" },
  { en: "cloak", th: "เสื้อคลุม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "cape", th: "ผ้าคลุมไหล่แบบยาว", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "poncho", th: "เสื้อคลุมปอนโช", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "kimono", th: "ชุดกิโมโน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "robe", th: "เสื้อคลุมอาบน้ำ", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "bathrobe", th: "เสื้อคลุมอาบน้ำแบบหนา", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "ballet flats", th: "รองเท้าบัลเล่ต์", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "clogs", th: "รองเท้าไม้", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "moccasins", th: "รองเท้าโมคาซิน", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "espadrilles", th: "รองเท้าเชือกถัก", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "platform shoes", th: "รองเท้าพื้นหนา", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "wedges", th: "รองเท้าส้นตัน", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "gaiters", th: "สนับแข้ง", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "mask", th: "หน้ากาก", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "😷" },
  { en: "face mask", th: "หน้ากากอนามัย", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "😷" },
  { en: "ear muffs", th: "ที่ครอบหูกันหนาว", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "shoulder bag", th: "กระเป๋าสะพายไหล่", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "tote bag", th: "กระเป๋าผ้า", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "👜" },
  { en: "clutch bag", th: "กระเป๋าคลัทช์", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "fanny pack", th: "กระเป๋าคาดเอว", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "tiara", th: "มงกุฎเล็ก", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "👑" },
  { en: "crown", th: "มงกุฎ", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👑" },
  { en: "locket", th: "จี้เปิดได้", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "charm bracelet", th: "สร้อยข้อมือประดับจี้", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "hairclip", th: "กิ๊บหนีบผม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "wig", th: "วิกผม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "veil", th: "ผ้าคลุมหน้า", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "garter", th: "สายรัดถุงเท้า", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "suspenders", th: "สายเอี๊ยม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "cummerbund", th: "ผ้าคาดเอวชุดสูท", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "ascot", th: "ผ้าผูกคอทางการ", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "knee-high socks", th: "ถุงเท้ายาวถึงเข่า", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "thermal underwear", th: "ชุดชั้นในกันหนาว", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "windbreaker", th: "เสื้อกันลม", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "parka", th: "เสื้อกันหนาวมีฮู้ด", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "down jacket", th: "เสื้อขนเป็ด", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "denim jacket", th: "แจ็คเก็ตยีนส์", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "" },
  { en: "trench coat", th: "เสื้อโค้ทกันฝนยาว", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "overshirt", th: "เสื้อคลุมแบบเชิ้ต", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "shrug", th: "เสื้อคลุมไหล่แขนสั้น", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "" },
  { en: "romper", th: "ชุดจั๊มสูทขาสั้น", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "" },
  { en: "bandana", th: "ผ้าโพกศีรษะลายสก็อต", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "" },
  { en: "house", th: "บ้าน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏠" },
  { en: "building", th: "อาคาร", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏢" },
  { en: "skyscraper", th: "ตึกระฟ้า", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🏙️" },
  { en: "apartment", th: "อพาร์ตเมนต์", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏢" },
  { en: "condominium", th: "คอนโดมิเนียม", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🏢" },
  { en: "school", th: "โรงเรียน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏫" },
  { en: "university", th: "มหาวิทยาลัย", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🎓" },
  { en: "library", th: "ห้องสมุด", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "📚" },
  { en: "museum", th: "พิพิธภัณฑ์", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏛️" },
  { en: "church", th: "โบสถ์คริสต์", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "⛪" },
  { en: "temple", th: "วัด", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🛕" },
  { en: "mosque", th: "มัสยิด", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🕌" },
  { en: "cathedral", th: "มหาวิหาร", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "⛪" },
  { en: "monastery", th: "อาราม", category: "สถานที่และภูมิศาสตร์", level: "B2", emoji: "" },
  { en: "palace", th: "วัง", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🏰" },
  { en: "castle", th: "ปราสาท", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏰" },
  { en: "fortress", th: "ป้อมปราการ", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "tower", th: "หอคอย", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🗼" },
  { en: "bridge", th: "สะพาน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🌉" },
  { en: "tunnel", th: "อุโมงค์", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "stadium", th: "สนามกีฬา", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏟️" },
  { en: "arena", th: "สนามแข่งขัน", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "theater", th: "โรงละคร", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🎭" },
  { en: "cinema", th: "โรงภาพยนตร์", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🎬" },
  { en: "hotel", th: "โรงแรม", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏨" },
  { en: "motel", th: "โมเทล", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "hostel", th: "ที่พักราคาประหยัด", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "restaurant", th: "ร้านอาหาร", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🍽️" },
  { en: "cafe", th: "ร้านกาแฟ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "☕" },
  { en: "bakery", th: "ร้านเบเกอรี่", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🥐" },
  { en: "market", th: "ตลาด", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏪" },
  { en: "supermarket", th: "ซูเปอร์มาร์เก็ต", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🛒" },
  { en: "shopping mall", th: "ห้างสรรพสินค้า", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏬" },
  { en: "convenience store", th: "ร้านสะดวกซื้อ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏪" },
  { en: "bank", th: "ธนาคาร", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏦" },
  { en: "post office", th: "ที่ทำการไปรษณีย์", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏤" },
  { en: "police station", th: "สถานีตำรวจ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🚓" },
  { en: "fire station", th: "สถานีดับเพลิง", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🚒" },
  { en: "train station", th: "สถานีรถไฟ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🚉" },
  { en: "bus station", th: "สถานีขนส่ง", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🚌" },
  { en: "airport", th: "สนามบิน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "✈️" },
  { en: "harbor", th: "ท่าเรือ", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "⚓" },
  { en: "port", th: "ท่าเรือขนส่งสินค้า", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "parking lot", th: "ลานจอดรถ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🅿️" },
  { en: "gas station", th: "ปั๊มน้ำมัน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "⛽" },
  { en: "factory", th: "โรงงาน", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🏭" },
  { en: "warehouse", th: "โกดังสินค้า", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "office building", th: "อาคารสำนักงาน", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🏢" },
  { en: "city hall", th: "ศาลาว่าการเมือง", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "courthouse", th: "ศาล", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "embassy", th: "สถานทูต", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "prison", th: "เรือนจำ", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "zoo", th: "สวนสัตว์", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🦁" },
  { en: "aquarium", th: "พิพิธภัณฑ์สัตว์น้ำ", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🐠" },
  { en: "amusement park", th: "สวนสนุก", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🎡" },
  { en: "playground", th: "สนามเด็กเล่น", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "" },
  { en: "park", th: "สวนสาธารณะ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏞️" },
  { en: "botanical garden", th: "สวนพฤกษศาสตร์", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "cemetery", th: "สุสาน", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "swimming pool", th: "สระว่ายน้ำ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏊" },
  { en: "farm", th: "ฟาร์ม", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🚜" },
  { en: "ranch", th: "ฟาร์มปศุสัตว์", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "village", th: "หมู่บ้าน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏘️" },
  { en: "town", th: "เมืองเล็ก", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "" },
  { en: "city", th: "เมือง", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🏙️" },
  { en: "capital city", th: "เมืองหลวง", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "metropolis", th: "มหานคร", category: "สถานที่และภูมิศาสตร์", level: "B2", emoji: "" },
  { en: "suburb", th: "ชานเมือง", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "downtown", th: "ใจกลางเมือง", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "neighborhood", th: "ย่านที่อยู่อาศัย", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "district", th: "เขต", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "province", th: "จังหวัด", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "state", th: "รัฐ", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "region", th: "ภูมิภาค", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "country", th: "ประเทศ", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🌍" },
  { en: "nation", th: "ชาติ", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "continent", th: "ทวีป", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🌍" },
  { en: "hemisphere", th: "ซีกโลก", category: "สถานที่และภูมิศาสตร์", level: "B2", emoji: "" },
  { en: "border", th: "พรมแดน", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "boundary", th: "เขตแดน", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "territory", th: "ดินแดน", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "colony", th: "อาณานิคม", category: "สถานที่และภูมิศาสตร์", level: "B2", emoji: "" },
  { en: "mainland", th: "แผ่นดินใหญ่", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "urban area", th: "เขตเมือง", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "rural area", th: "เขตชนบท", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "countryside", th: "ชนบท", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🌾" },
  { en: "outskirts", th: "ชานเมือง/ชานเขตเมือง", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "landmark", th: "สถานที่สำคัญ", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "monument", th: "อนุสาวรีย์", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🗿" },
  { en: "statue", th: "รูปปั้น", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "fountain", th: "น้ำพุ", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "⛲" },
  { en: "plaza", th: "ลานกว้าง", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "intersection", th: "ทางแยก", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🚦" },
  { en: "roundabout", th: "วงเวียน", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "sidewalk", th: "ทางเท้า", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "pavement", th: "พื้นถนนที่ปูแล้ว", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "alley", th: "ตรอกซอย", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "avenue", th: "ถนนสายใหญ่", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "boulevard", th: "ถนนใหญ่ที่มีต้นไม้", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "highway", th: "ทางหลวง", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🛣️" },
  { en: "expressway", th: "ทางด่วน", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "road", th: "ถนน", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🛣️" },
  { en: "street", th: "ถนนในเมือง", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "" },
  { en: "peak", th: "ยอดเขา", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "archipelago", th: "หมู่เกาะ", category: "สถานที่และภูมิศาสตร์", level: "C1", emoji: "" },
  { en: "strait", th: "ช่องแคบ", category: "สถานที่และภูมิศาสตร์", level: "C1", emoji: "" },
  { en: "equator", th: "เส้นศูนย์สูตร", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "latitude", th: "เส้นละติจูด", category: "สถานที่และภูมิศาสตร์", level: "B2", emoji: "" },
  { en: "longitude", th: "เส้นลองจิจูด", category: "สถานที่และภูมิศาสตร์", level: "B2", emoji: "" },
  { en: "population", th: "ประชากร", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "capital", th: "เมืองหลวง", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "" },
  { en: "map", th: "แผนที่", category: "สถานที่และภูมิศาสตร์", level: "A1", emoji: "🗺️" },
  { en: "atlas", th: "สมุดแผนที่", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "compass", th: "เข็มทิศ", category: "สถานที่และภูมิศาสตร์", level: "A2", emoji: "🧭" },
  { en: "landscape", th: "ภูมิทัศน์", category: "สถานที่และภูมิศาสตร์", level: "B1", emoji: "" },
  { en: "bobcat", th: "แมวป่าบ็อบแคท", category: "สัตว์", level: "C1", emoji: "🐈" },
  { en: "lynx", th: "แมวป่าลิงซ์", category: "สัตว์", level: "C1", emoji: "🐈" },
  { en: "carbon cycle", th: "วัฏจักรคาร์บอน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🔄" },
  { en: "food chain", th: "ห่วงโซ่อาหาร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🔗" },
  { en: "food web", th: "สายใยอาหาร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🕸️" },
  { en: "sea level", th: "ระดับน้ำทะเล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌊" },
  { en: "coral bleaching", th: "ปะการังฟอกขาว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🪸" },
  { en: "ozone depletion", th: "การทำลายชั้นโอโซน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌫️" },
  { en: "topography", th: "ภูมิประเทศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🗺️" },
  { en: "terrain", th: "พื้นที่ภูมิประเทศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "⛰️" },
  { en: "biosphere", th: "ชีวมณฑล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌍" },
  { en: "geothermal energy", th: "พลังงานความร้อนใต้พิภพ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "♨️" },
  { en: "food processor", th: "เครื่องเตรียมอาหาร", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "🍲" },
  { en: "air fryer", th: "หม้อทอดไร้น้ำมัน", category: "บ้านและเครื่องใช้ในบ้าน", level: "B1", emoji: "🍟" },
  { en: "dish rack", th: "ที่คว่ำจาน", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🍽️" },
  { en: "ironing board", th: "โต๊ะรีดผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "👔" },
  { en: "laundry basket", th: "ตะกร้าผ้า", category: "บ้านและเครื่องใช้ในบ้าน", level: "A2", emoji: "🧺" },
  { en: "get away with", th: "ทำผิดแล้วรอดตัว", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "put up with", th: "ทนกับ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "run into", th: "บังเอิญเจอ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "bump into", th: "บังเอิญเจอโดยไม่ตั้งใจ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "drop by", th: "แวะมา", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "drop off", th: "ไปส่ง", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "pick out", th: "เลือกออกมา", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "pick on", th: "แกล้ง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "shut up", th: "หุบปาก", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "shut down", th: "ปิดระบบ", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "switch on", th: "เปิด(เครื่อง)", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "switch off", th: "ปิด(เครื่อง)", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "cut down on", th: "ลดปริมาณ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "cut off", th: "ตัดขาด", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "cut back on", th: "ลดการใช้จ่าย", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "give away", th: "แจกให้ฟรี", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "give back", th: "คืนให้", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "give in", th: "ยอมแพ้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "give out", th: "แจกจ่าย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "go back", th: "กลับไป", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" }
];
