const VOCAB_PART_3 = [
  { en: "dog", th: "หมา", category: "สัตว์", level: "A1", emoji: "🐶" },
  { en: "cat", th: "แมว", category: "สัตว์", level: "A1", emoji: "🐱" },
  { en: "bird", th: "นก", category: "สัตว์", level: "A1", emoji: "🐦" },
  { en: "rabbit", th: "กระต่าย", category: "สัตว์", level: "A1", emoji: "🐰" },
  { en: "hamster", th: "แฮมสเตอร์", category: "สัตว์", level: "A2", emoji: "🐹" },
  { en: "horse", th: "ม้า", category: "สัตว์", level: "A1", emoji: "🐴" },
  { en: "cow", th: "วัว", category: "สัตว์", level: "A1", emoji: "🐄" },
  { en: "pig", th: "หมู", category: "สัตว์", level: "A1", emoji: "🐷" },
  { en: "sheep", th: "แกะ", category: "สัตว์", level: "A1", emoji: "🐑" },
  { en: "goat", th: "แพะ", category: "สัตว์", level: "A1", emoji: "🐐" },
  { en: "turtle", th: "เต่า", category: "สัตว์", level: "A1", emoji: "🐢" },
  { en: "frog", th: "กบ", category: "สัตว์", level: "A1", emoji: "🐸" },
  { en: "snake", th: "งู", category: "สัตว์", level: "A1", emoji: "🐍" },
  { en: "mouse", th: "หนู", category: "สัตว์", level: "A1", emoji: "🐭" },
  { en: "monkey", th: "ลิง", category: "สัตว์", level: "A1", emoji: "🐒" },
  { en: "lion", th: "สิงโต", category: "สัตว์", level: "A1", emoji: "🦁" },
  { en: "tiger", th: "เสือโคร่ง", category: "สัตว์", level: "A1", emoji: "🐯" },
  { en: "elephant", th: "ช้าง", category: "สัตว์", level: "A1", emoji: "🐘" },
  { en: "bear", th: "หมี", category: "สัตว์", level: "A1", emoji: "🐻" },
  { en: "wolf", th: "หมาป่า", category: "สัตว์", level: "A2", emoji: "🐺" },
  { en: "fox", th: "สุนัขจิ้งจอก", category: "สัตว์", level: "A2", emoji: "🦊" },
  { en: "deer", th: "กวาง", category: "สัตว์", level: "A2", emoji: "🦌" },
  { en: "giraffe", th: "ยีราฟ", category: "สัตว์", level: "A1", emoji: "🦒" },
  { en: "zebra", th: "ม้าลาย", category: "สัตว์", level: "A1", emoji: "🦓" },
  { en: "kangaroo", th: "จิงโจ้", category: "สัตว์", level: "A1", emoji: "🦘" },
  { en: "koala", th: "หมีโคอาลา", category: "สัตว์", level: "A1", emoji: "🐨" },
  { en: "panda", th: "แพนด้า", category: "สัตว์", level: "A1", emoji: "🐼" },
  { en: "gorilla", th: "กอริลลา", category: "สัตว์", level: "A2", emoji: "🦍" },
  { en: "chimpanzee", th: "ชิมแปนซี", category: "สัตว์", level: "B1", emoji: "🐵" },
  { en: "orangutan", th: "อุรังอุตัง", category: "สัตว์", level: "B1", emoji: "🦧" },
  { en: "camel", th: "อูฐ", category: "สัตว์", level: "A2", emoji: "🐫" },
  { en: "hippopotamus", th: "ฮิปโปโปเตมัส", category: "สัตว์", level: "A2", emoji: "🦛" },
  { en: "rhinoceros", th: "แรด", category: "สัตว์", level: "A2", emoji: "🦏" },
  { en: "crocodile", th: "จระเข้", category: "สัตว์", level: "A2", emoji: "🐊" },
  { en: "alligator", th: "จระเข้อัลลิเกเตอร์", category: "สัตว์", level: "B1", emoji: "🐊" },
  { en: "lizard", th: "กิ้งก่า", category: "สัตว์", level: "A2", emoji: "🦎" },
  { en: "gecko", th: "จิ้งจก", category: "สัตว์", level: "B1", emoji: "🦎" },
  { en: "iguana", th: "อีกัวน่า", category: "สัตว์", level: "B1", emoji: "🦎" },
  { en: "chameleon", th: "กิ้งก่าคาเมเลียน", category: "สัตว์", level: "B1", emoji: "🦎" },
  { en: "eagle", th: "นกอินทรี", category: "สัตว์", level: "A2", emoji: "🦅" },
  { en: "owl", th: "นกฮูก", category: "สัตว์", level: "A2", emoji: "🦉" },
  { en: "parrot", th: "นกแก้ว", category: "สัตว์", level: "A1", emoji: "🦜" },
  { en: "peacock", th: "นกยูง", category: "สัตว์", level: "A2", emoji: "🦚" },
  { en: "penguin", th: "เพนกวิน", category: "สัตว์", level: "A1", emoji: "🐧" },
  { en: "ostrich", th: "นกกระจอกเทศ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "flamingo", th: "นกฟลามิงโก", category: "สัตว์", level: "B1", emoji: "🦩" },
  { en: "swan", th: "หงส์", category: "สัตว์", level: "A2", emoji: "🦢" },
  { en: "dove", th: "นกพิราบขาว", category: "สัตว์", level: "A2", emoji: "🕊️" },
  { en: "pigeon", th: "นกพิราบ", category: "สัตว์", level: "A2", emoji: "🐦" },
  { en: "sparrow", th: "นกกระจอก", category: "สัตว์", level: "B1", emoji: "" },
  { en: "crow", th: "อีกา", category: "สัตว์", level: "A2", emoji: "🐦‍⬛" },
  { en: "raven", th: "นกเรเวน", category: "สัตว์", level: "B2", emoji: "🐦‍⬛" },
  { en: "seagull", th: "นกนางนวล", category: "สัตว์", level: "A2", emoji: "" },
  { en: "bat", th: "ค้างคาว", category: "สัตว์", level: "A2", emoji: "🦇" },
  { en: "squirrel", th: "กระรอก", category: "สัตว์", level: "A2", emoji: "🐿️" },
  { en: "hedgehog", th: "เม่นแคระ", category: "สัตว์", level: "B1", emoji: "🦔" },
  { en: "raccoon", th: "แรคคูน", category: "สัตว์", level: "B1", emoji: "🦝" },
  { en: "skunk", th: "สกั๊งค์", category: "สัตว์", level: "B1", emoji: "🦨" },
  { en: "beaver", th: "บีเวอร์", category: "สัตว์", level: "B1", emoji: "🦫" },
  { en: "otter", th: "นาก", category: "สัตว์", level: "B1", emoji: "🦦" },
  { en: "mole", th: "ตุ่น", category: "สัตว์", level: "B1", emoji: "" },
  { en: "weasel", th: "พังพอน", category: "สัตว์", level: "B2", emoji: "" },
  { en: "badger", th: "แบดเจอร์", category: "สัตว์", level: "B2", emoji: "🦡" },
  { en: "mongoose", th: "พังพอนตัวเล็ก", category: "สัตว์", level: "B2", emoji: "" },
  { en: "meerkat", th: "เมียร์แคต", category: "สัตว์", level: "B1", emoji: "" },
  { en: "lemur", th: "ลีเมอร์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "sloth", th: "สลอธ", category: "สัตว์", level: "B1", emoji: "🦥" },
  { en: "armadillo", th: "อาร์มาดิลโล", category: "สัตว์", level: "B2", emoji: "" },
  { en: "anteater", th: "ตัวกินมด", category: "สัตว์", level: "B2", emoji: "" },
  { en: "wombat", th: "วอมแบท", category: "สัตว์", level: "B2", emoji: "" },
  { en: "platypus", th: "ตุ่นปากเป็ด", category: "สัตว์", level: "B2", emoji: "" },
  { en: "bison", th: "ไบซัน", category: "สัตว์", level: "B1", emoji: "🦬" },
  { en: "buffalo", th: "ควาย", category: "สัตว์", level: "A2", emoji: "🐃" },
  { en: "ox", th: "วัวตัวผู้", category: "สัตว์", level: "B1", emoji: "🐂" },
  { en: "donkey", th: "ลา", category: "สัตว์", level: "A2", emoji: "🫏" },
  { en: "mule", th: "ล่อ", category: "สัตว์", level: "B2", emoji: "" },
  { en: "llama", th: "ลามะ", category: "สัตว์", level: "B1", emoji: "🦙" },
  { en: "alpaca", th: "อัลปาก้า", category: "สัตว์", level: "B1", emoji: "🦙" },
  { en: "moose", th: "กวางมูส", category: "สัตว์", level: "B1", emoji: "🫎" },
  { en: "elk", th: "กวางเอลก์", category: "สัตว์", level: "B2", emoji: "🦌" },
  { en: "antelope", th: "แอนทีโลป", category: "สัตว์", level: "B2", emoji: "" },
  { en: "leopard", th: "เสือดาว", category: "สัตว์", level: "A2", emoji: "🐆" },
  { en: "cheetah", th: "เสือชีตาห์", category: "สัตว์", level: "A2", emoji: "🐆" },
  { en: "jaguar", th: "เสือจากัวร์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "panther", th: "เสือดำ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "hyena", th: "ไฮยีนา", category: "สัตว์", level: "B1", emoji: "" },
  { en: "wild boar", th: "หมูป่า", category: "สัตว์", level: "B1", emoji: "🐗" },
  { en: "bull", th: "วัวกระทิง", category: "สัตว์", level: "A2", emoji: "🐂" },
  { en: "calf", th: "ลูกวัว", category: "สัตว์", level: "B1", emoji: "🐄" },
  { en: "piglet", th: "ลูกหมู", category: "สัตว์", level: "A2", emoji: "🐷" },
  { en: "kitten", th: "ลูกแมว", category: "สัตว์", level: "A1", emoji: "🐱" },
  { en: "puppy", th: "ลูกสุนัข", category: "สัตว์", level: "A1", emoji: "🐶" },
  { en: "foal", th: "ลูกม้า", category: "สัตว์", level: "B2", emoji: "🐴" },
  { en: "cub", th: "ลูกสัตว์ป่า", category: "สัตว์", level: "B1", emoji: "" },
  { en: "rooster", th: "ไก่ตัวผู้", category: "สัตว์", level: "A2", emoji: "🐓" },
  { en: "hen", th: "แม่ไก่", category: "สัตว์", level: "A2", emoji: "🐔" },
  { en: "goose", th: "ห่าน", category: "สัตว์", level: "A2", emoji: "🪿" },
  { en: "guinea pig", th: "หนูตะเภา", category: "สัตว์", level: "A2", emoji: "🐹" },
  { en: "ferret", th: "เฟอร์เรต", category: "สัตว์", level: "B1", emoji: "" },
  { en: "parakeet", th: "นกหงส์หยก", category: "สัตว์", level: "B1", emoji: "" },
  { en: "canary", th: "นกคานารี", category: "สัตว์", level: "B1", emoji: "" },
  { en: "cockatoo", th: "นกกระตั้ว", category: "สัตว์", level: "B2", emoji: "" },
  { en: "toucan", th: "นกทูแคน", category: "สัตว์", level: "B1", emoji: "" },
  { en: "puffin", th: "นกพัฟฟิน", category: "สัตว์", level: "B2", emoji: "" },
  { en: "emu", th: "นกอีมู", category: "สัตว์", level: "B2", emoji: "" },
  { en: "quail", th: "นกกระทา", category: "สัตว์", level: "B2", emoji: "" },
  { en: "pheasant", th: "ไก่ฟ้า", category: "สัตว์", level: "B2", emoji: "" },
  { en: "partridge", th: "นกกระทาป่า", category: "สัตว์", level: "C1", emoji: "" },
  { en: "woodpecker", th: "นกหัวขวาน", category: "สัตว์", level: "B1", emoji: "" },
  { en: "hummingbird", th: "นกฮัมมิงเบิร์ด", category: "สัตว์", level: "B1", emoji: "" },
  { en: "kingfisher", th: "นกกระเต็น", category: "สัตว์", level: "B2", emoji: "" },
  { en: "cuckoo", th: "นกกาเหว่า", category: "สัตว์", level: "B2", emoji: "" },
  { en: "nightingale", th: "นกไนติงเกล", category: "สัตว์", level: "B2", emoji: "" },
  { en: "magpie", th: "นกสาลิกา", category: "สัตว์", level: "B2", emoji: "" },
  { en: "robin", th: "นกโรบิน", category: "สัตว์", level: "B2", emoji: "" },
  { en: "swallow", th: "นกนางแอ่น", category: "สัตว์", level: "B2", emoji: "" },
  { en: "stork", th: "นกกระสา", category: "สัตว์", level: "B1", emoji: "" },
  { en: "crane", th: "นกกระเรียน", category: "สัตว์", level: "B1", emoji: "" },
  { en: "heron", th: "นกยาง", category: "สัตว์", level: "B2", emoji: "" },
  { en: "pelican", th: "นกกระทุง", category: "สัตว์", level: "B1", emoji: "" },
  { en: "vulture", th: "แร้ง", category: "สัตว์", level: "B1", emoji: "" },
  { en: "falcon", th: "เหยี่ยวเพเรกริน", category: "สัตว์", level: "A2", emoji: "🦅" },
  { en: "hawk", th: "เหยี่ยว", category: "สัตว์", level: "A2", emoji: "🦅" },
  { en: "albatross", th: "นกอัลบาทรอส", category: "สัตว์", level: "C1", emoji: "" },
  { en: "shark", th: "ฉลาม", category: "สัตว์", level: "A1", emoji: "🦈" },
  { en: "whale", th: "ปลาวาฬ", category: "สัตว์", level: "A1", emoji: "🐳" },
  { en: "dolphin", th: "โลมา", category: "สัตว์", level: "A1", emoji: "🐬" },
  { en: "lobster", th: "กุ้งมังกร", category: "สัตว์", level: "A2", emoji: "🦞" },
  { en: "jellyfish", th: "แมงกะพรุน", category: "สัตว์", level: "A2", emoji: "🪼" },
  { en: "starfish", th: "ปลาดาว", category: "สัตว์", level: "A2", emoji: "" },
  { en: "seahorse", th: "ม้าน้ำ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "clam", th: "หอยกาบ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "mussel", th: "หอยแมลงภู่", category: "สัตว์", level: "B2", emoji: "" },
  { en: "snail", th: "หอยทาก", category: "สัตว์", level: "A2", emoji: "🐌" },
  { en: "slug", th: "ทาก", category: "สัตว์", level: "B2", emoji: "🐌" },
  { en: "eel", th: "ปลาไหล", category: "สัตว์", level: "B1", emoji: "" },
  { en: "salmon", th: "ปลาแซลมอน", category: "สัตว์", level: "A2", emoji: "🐟" },
  { en: "tuna", th: "ปลาทูน่า", category: "สัตว์", level: "A2", emoji: "🐟" },
  { en: "catfish", th: "ปลาดุก", category: "สัตว์", level: "B1", emoji: "🐟" },
  { en: "goldfish", th: "ปลาทอง", category: "สัตว์", level: "A1", emoji: "🐠" },
  { en: "clownfish", th: "ปลาการ์ตูน", category: "สัตว์", level: "A2", emoji: "🐠" },
  { en: "stingray", th: "ปลากระเบน", category: "สัตว์", level: "B1", emoji: "" },
  { en: "seal", th: "แมวน้ำ", category: "สัตว์", level: "A2", emoji: "🦭" },
  { en: "sea lion", th: "สิงโตทะเล", category: "สัตว์", level: "B1", emoji: "🦭" },
  { en: "walrus", th: "วอลรัส", category: "สัตว์", level: "B1", emoji: "" },
  { en: "manatee", th: "พะยูน", category: "สัตว์", level: "C1", emoji: "" },
  { en: "orca", th: "วาฬเพชฌฆาต", category: "สัตว์", level: "B1", emoji: "🐳" },
  { en: "sea urchin", th: "เม่นทะเล", category: "สัตว์", level: "B2", emoji: "" },
  { en: "barnacle", th: "เพรียง", category: "สัตว์", level: "C1", emoji: "" },
  { en: "sea anemone", th: "ดอกไม้ทะเล", category: "สัตว์", level: "B2", emoji: "" },
  { en: "ant", th: "มด", category: "สัตว์", level: "A1", emoji: "🐜" },
  { en: "bee", th: "ผึ้ง", category: "สัตว์", level: "A1", emoji: "🐝" },
  { en: "wasp", th: "ต่อ", category: "สัตว์", level: "A2", emoji: "" },
  { en: "hornet", th: "แตนต่อ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "butterfly", th: "ผีเสื้อ", category: "สัตว์", level: "A1", emoji: "🦋" },
  { en: "moth", th: "ผีเสื้อกลางคืน", category: "สัตว์", level: "A2", emoji: "" },
  { en: "beetle", th: "ด้วง", category: "สัตว์", level: "A2", emoji: "🪲" },
  { en: "ladybug", th: "เต่าทอง", category: "สัตว์", level: "A2", emoji: "🐞" },
  { en: "cockroach", th: "แมลงสาบ", category: "สัตว์", level: "A2", emoji: "🪳" },
  { en: "cricket", th: "จิ้งหรีด", category: "สัตว์", level: "A2", emoji: "🦗" },
  { en: "grasshopper", th: "ตั๊กแตน", category: "สัตว์", level: "A2", emoji: "🦗" },
  { en: "locust", th: "ตั๊กแตนปาทังก้า", category: "สัตว์", level: "B2", emoji: "🦗" },
  { en: "mantis", th: "ตั๊กแตนตำข้าว", category: "สัตว์", level: "B1", emoji: "" },
  { en: "dragonfly", th: "แมลงปอ", category: "สัตว์", level: "A2", emoji: "" },
  { en: "firefly", th: "หิ่งห้อย", category: "สัตว์", level: "B1", emoji: "" },
  { en: "mosquito", th: "ยุง", category: "สัตว์", level: "A1", emoji: "🦟" },
  { en: "fly", th: "แมลงวัน", category: "สัตว์", level: "A1", emoji: "🪰" },
  { en: "flea", th: "หมัด", category: "สัตว์", level: "B1", emoji: "" },
  { en: "tick", th: "เห็บ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "spider", th: "แมงมุม", category: "สัตว์", level: "A1", emoji: "🕷️" },
  { en: "scorpion", th: "แมงป่อง", category: "สัตว์", level: "A2", emoji: "🦂" },
  { en: "centipede", th: "ตะขาบ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "millipede", th: "กิ้งกือ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "termite", th: "ปลวก", category: "สัตว์", level: "B1", emoji: "" },
  { en: "silkworm", th: "ตัวไหม", category: "สัตว์", level: "B2", emoji: "🐛" },
  { en: "caterpillar", th: "หนอนผีเสื้อ", category: "สัตว์", level: "A2", emoji: "🐛" },
  { en: "worm", th: "ไส้เดือน", category: "สัตว์", level: "A1", emoji: "🪱" },
  { en: "python", th: "งูเหลือม", category: "สัตว์", level: "B1", emoji: "🐍" },
  { en: "cobra", th: "งูเห่า", category: "สัตว์", level: "B1", emoji: "🐍" },
  { en: "viper", th: "งูพิษ", category: "สัตว์", level: "B2", emoji: "🐍" },
  { en: "rattlesnake", th: "งูหางกระดิ่ง", category: "สัตว์", level: "B2", emoji: "🐍" },
  { en: "boa constrictor", th: "งูเหลือมยักษ์", category: "สัตว์", level: "C1", emoji: "🐍" },
  { en: "komodo dragon", th: "มังกรโคโมโด", category: "สัตว์", level: "C1", emoji: "🐉" },
  { en: "tortoise", th: "เต่าบก", category: "สัตว์", level: "A2", emoji: "🐢" },
  { en: "salamander", th: "ซาลาแมนเดอร์", category: "สัตว์", level: "B2", emoji: "" },
  { en: "newt", th: "นิวต์", category: "สัตว์", level: "C1", emoji: "" },
  { en: "toad", th: "คางคก", category: "สัตว์", level: "A2", emoji: "🐸" },
  { en: "tadpole", th: "ลูกอ๊อด", category: "สัตว์", level: "B1", emoji: "" },
  { en: "paw", th: "อุ้งเท้า", category: "สัตว์", level: "A2", emoji: "🐾" },
  { en: "claw", th: "กรงเล็บ", category: "สัตว์", level: "A2", emoji: "" },
  { en: "hoof", th: "กีบเท้า", category: "สัตว์", level: "B1", emoji: "" },
  { en: "beak", th: "จะงอยปาก", category: "สัตว์", level: "A2", emoji: "" },
  { en: "feather", th: "ขนนก", category: "สัตว์", level: "A2", emoji: "🪶" },
  { en: "fur", th: "ขนสัตว์", category: "สัตว์", level: "A2", emoji: "" },
  { en: "tail", th: "หาง", category: "สัตว์", level: "A1", emoji: "" },
  { en: "wing", th: "ปีก", category: "สัตว์", level: "A1", emoji: "" },
  { en: "gill", th: "เหงือกปลา", category: "สัตว์", level: "B1", emoji: "" },
  { en: "fish scale", th: "เกล็ดปลา", category: "สัตว์", level: "B1", emoji: "" },
  { en: "whisker", th: "หนวดสัตว์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "antler", th: "เขากวาง", category: "สัตว์", level: "B2", emoji: "" },
  { en: "horn", th: "เขาสัตว์", category: "สัตว์", level: "A2", emoji: "" },
  { en: "mane", th: "ขนแผงคอ", category: "สัตว์", level: "B2", emoji: "" },
  { en: "trunk", th: "งวงช้าง", category: "สัตว์", level: "B1", emoji: "" },
  { en: "pouch", th: "ถุงหน้าท้อง", category: "สัตว์", level: "B2", emoji: "" },
  { en: "shell", th: "เปลือกหอย", category: "สัตว์", level: "A2", emoji: "" },
  { en: "tentacle", th: "หนวดปลาหมึก", category: "สัตว์", level: "B2", emoji: "" },
  { en: "fin", th: "ครีบปลา", category: "สัตว์", level: "A2", emoji: "" },
  { en: "migrate", th: "อพยพย้ายถิ่น", category: "สัตว์", level: "B2", emoji: "" },
  { en: "hibernate", th: "จำศีล", category: "สัตว์", level: "B2", emoji: "" },
  { en: "camouflage", th: "การพรางตัว", category: "สัตว์", level: "B2", emoji: "" },
  { en: "predator", th: "ผู้ล่า", category: "สัตว์", level: "B1", emoji: "" },
  { en: "prey", th: "เหยื่อ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "herd", th: "ฝูงสัตว์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "flock", th: "ฝูงนก", category: "สัตว์", level: "B1", emoji: "" },
  { en: "pack", th: "ฝูงหมาป่า", category: "สัตว์", level: "B2", emoji: "" },
  { en: "swarm", th: "ฝูงแมลง", category: "สัตว์", level: "B2", emoji: "" },
  { en: "nest", th: "รังนก", category: "สัตว์", level: "A2", emoji: "" },
  { en: "den", th: "ถ้ำสัตว์", category: "สัตว์", level: "B2", emoji: "" },
  { en: "burrow", th: "โพรงสัตว์", category: "สัตว์", level: "B2", emoji: "" },
  { en: "cocoon", th: "รังไหม", category: "สัตว์", level: "B2", emoji: "" },
  { en: "molt", th: "ลอกคราบ", category: "สัตว์", level: "C1", emoji: "" },
  { en: "breed", th: "ผสมพันธุ์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "species", th: "ชนิดพันธุ์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "mammal", th: "สัตว์เลี้ยงลูกด้วยนม", category: "สัตว์", level: "B1", emoji: "" },
  { en: "herbivore", th: "สัตว์กินพืช", category: "สัตว์", level: "B1", emoji: "" },
  { en: "carnivore", th: "สัตว์กินเนื้อ", category: "สัตว์", level: "B1", emoji: "" },
  { en: "omnivore", th: "สัตว์กินทั้งพืชและเนื้อ", category: "สัตว์", level: "B2", emoji: "" },
  { en: "vertebrate", th: "สัตว์มีกระดูกสันหลัง", category: "สัตว์", level: "B2", emoji: "" },
  { en: "invertebrate", th: "สัตว์ไม่มีกระดูกสันหลัง", category: "สัตว์", level: "B2", emoji: "" },
  { en: "amphibian", th: "สัตว์สะเทินน้ำสะเทินบก", category: "สัตว์", level: "B2", emoji: "🐸" },
  { en: "reptile", th: "สัตว์เลื้อยคลาน", category: "สัตว์", level: "B1", emoji: "🦎" },
  { en: "livestock", th: "ปศุสัตว์", category: "สัตว์", level: "B1", emoji: "" },
  { en: "poultry", th: "สัตว์ปีก", category: "สัตว์", level: "B1", emoji: "" },
  { en: "queen bee", th: "นางพญาผึ้ง", category: "สัตว์", level: "B2", emoji: "🐝" },
  { en: "stallion", th: "ม้าตัวผู้", category: "สัตว์", level: "C1", emoji: "🐴" },
  { en: "mare", th: "ม้าตัวเมีย", category: "สัตว์", level: "C1", emoji: "🐴" },
  { en: "fawn", th: "ลูกกวาง", category: "สัตว์", level: "B2", emoji: "🦌" },
  { en: "joey", th: "ลูกจิงโจ้", category: "สัตว์", level: "C1", emoji: "🦘" },
  { en: "chick", th: "ลูกไก่", category: "สัตว์", level: "A1", emoji: "🐤" },
  { en: "mountain", th: "ภูเขา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "⛰️" },
  { en: "hill", th: "เนินเขา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🏞️" },
  { en: "valley", th: "หุบเขา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🏞️" },
  { en: "cliff", th: "หน้าผา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "canyon", th: "หุบเขาลึก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "plateau", th: "ที่ราบสูง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "plain", th: "ที่ราบ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "desert", th: "ทะเลทราย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🏜️" },
  { en: "forest", th: "ป่า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌲" },
  { en: "jungle", th: "ป่าดงดิบ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌴" },
  { en: "rainforest", th: "ป่าฝนเขตร้อน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌳" },
  { en: "meadow", th: "ทุ่งหญ้า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "prairie", th: "ทุ่งหญ้าแพรรี", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "savanna", th: "ทุ่งหญ้าสะวันนา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "tundra", th: "ทุนดรา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "glacier", th: "ธารน้ำแข็ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🧊" },
  { en: "iceberg", th: "ภูเขาน้ำแข็ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🧊" },
  { en: "volcano", th: "ภูเขาไฟ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌋" },
  { en: "crater", th: "ปากปล่องภูเขาไฟ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "cave", th: "ถ้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🕳️" },
  { en: "island", th: "เกาะ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🏝️" },
  { en: "peninsula", th: "คาบสมุทร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "coast", th: "ชายฝั่ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "shore", th: "ริมฝั่ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "beach", th: "ชายหาด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🏖️" },
  { en: "bay", th: "อ่าว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "gulf", th: "อ่าวใหญ่", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "lagoon", th: "ทะเลสาบน้ำเค็ม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "delta", th: "สามเหลี่ยมปากแม่น้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "river", th: "แม่น้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🏞️" },
  { en: "stream", th: "ลำธาร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "creek", th: "ลำห้วย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "waterfall", th: "น้ำตก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "" },
  { en: "lake", th: "ทะเลสาบ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "" },
  { en: "pond", th: "บ่อน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "" },
  { en: "swamp", th: "หนองบึง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "marsh", th: "ที่ลุ่มน้ำขัง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "wetland", th: "พื้นที่ชุ่มน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "oasis", th: "โอเอซิส", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "dune", th: "เนินทราย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "rock", th: "หิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🪨" },
  { en: "boulder", th: "ก้อนหินใหญ่", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🪨" },
  { en: "pebble", th: "ก้อนกรวด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "soil", th: "ดิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "mud", th: "โคลน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "" },
  { en: "sand", th: "ทราย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "" },
  { en: "clay", th: "ดินเหนียว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "tree", th: "ต้นไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌳" },
  { en: "oak tree", th: "ต้นโอ๊ก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌳" },
  { en: "pine tree", th: "ต้นสน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌲" },
  { en: "maple tree", th: "ต้นเมเปิล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🍁" },
  { en: "willow tree", th: "ต้นหลิว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🌳" },
  { en: "bamboo", th: "ไผ่", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🎋" },
  { en: "palm tree", th: "ต้นปาล์ม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌴" },
  { en: "cedar", th: "ต้นซีดาร์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌲" },
  { en: "birch", th: "ต้นเบิร์ช", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌳" },
  { en: "cactus", th: "กระบองเพชร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌵" },
  { en: "fern", th: "เฟิร์น", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌿" },
  { en: "moss", th: "มอส", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌿" },
  { en: "algae", th: "สาหร่ายน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "seaweed", th: "สาหร่ายทะเล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "grass", th: "หญ้า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌱" },
  { en: "weed", th: "วัชพืช", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "root", th: "ราก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "branch", th: "กิ่งไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "leaf", th: "ใบไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🍃" },
  { en: "bark", th: "เปลือกไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "trunk of a tree", th: "ลำต้นไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "seed", th: "เมล็ดพืช", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌱" },
  { en: "bud", th: "ตาดอก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌱" },
  { en: "blossom", th: "ดอกไม้บาน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌸" },
  { en: "petal", th: "กลีบดอกไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌸" },
  { en: "pollen", th: "เกสรดอกไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "flower", th: "ดอกไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌸" },
  { en: "rose", th: "ดอกกุหลาบ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌹" },
  { en: "tulip", th: "ดอกทิวลิป", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌷" },
  { en: "lily", th: "ดอกลิลลี่", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "orchid", th: "ดอกกล้วยไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌺" },
  { en: "sunflower", th: "ดอกทานตะวัน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌻" },
  { en: "daisy", th: "ดอกเดซี่", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌼" },
  { en: "lotus", th: "ดอกบัว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🪷" },
  { en: "jasmine", th: "ดอกมะลิ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "chrysanthemum", th: "ดอกเบญจมาศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "fungus", th: "เชื้อรา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🍄" },
  { en: "vine", th: "เถาวัลย์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "shrub", th: "พุ่มไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌳" },
  { en: "bush", th: "พุ่มไม้เตี้ย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌳" },
  { en: "hedge", th: "รั้วต้นไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "crop", th: "พืชผล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌾" },
  { en: "harvest", th: "การเก็บเกี่ยว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌾" },
  { en: "orchard", th: "สวนผลไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "sun", th: "ดวงอาทิตย์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "☀️" },
  { en: "moon", th: "ดวงจันทร์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌙" },
  { en: "star", th: "ดวงดาว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "⭐" },
  { en: "sky", th: "ท้องฟ้า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌌" },
  { en: "cloud", th: "เมฆ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "☁️" },
  { en: "rain", th: "ฝน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌧️" },
  { en: "drizzle", th: "ฝนปรอย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌦️" },
  { en: "shower", th: "ฝนโปรย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌦️" },
  { en: "storm", th: "พายุ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "⛈️" },
  { en: "thunderstorm", th: "พายุฝนฟ้าคะนอง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "⛈️" },
  { en: "thunder", th: "ฟ้าร้อง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "⛈️" },
  { en: "lightning", th: "ฟ้าแลบ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "⚡" },
  { en: "wind", th: "ลม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "💨" },
  { en: "breeze", th: "ลมพัดเบาๆ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🍃" },
  { en: "gale", th: "ลมแรงจัด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "💨" },
  { en: "hurricane", th: "พายุเฮอริเคน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌀" },
  { en: "typhoon", th: "พายุไต้ฝุ่น", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌀" },
  { en: "tornado", th: "พายุทอร์นาโด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌪️" },
  { en: "cyclone", th: "พายุไซโคลน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🌀" },
  { en: "fog", th: "หมอก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌫️" },
  { en: "mist", th: "หมอกบาง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌫️" },
  { en: "haze", th: "หมอกควัน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🌫️" },
  { en: "dew", th: "น้ำค้าง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "💧" },
  { en: "frost", th: "น้ำค้างแข็ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "❄️" },
  { en: "ice", th: "น้ำแข็ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🧊" },
  { en: "snow", th: "หิมะ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "❄️" },
  { en: "snowflake", th: "เกล็ดหิมะ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "❄️" },
  { en: "hail", th: "ลูกเห็บ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🧊" },
  { en: "humidity", th: "ความชื้น", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "climate", th: "ภูมิอากาศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "monsoon", th: "ฤดูมรสุม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌧️" },
  { en: "drought", th: "ภัยแล้ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "flood", th: "น้ำท่วม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌊" },
  { en: "heatwave", th: "คลื่นความร้อน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🔥" },
  { en: "rainbow", th: "สายรุ้ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌈" },
  { en: "sunshine", th: "แสงแดด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "☀️" },
  { en: "shade", th: "ร่มเงา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "shadow", th: "เงา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "" },
  { en: "earthquake", th: "แผ่นดินไหว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "tsunami", th: "สึนามิ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌊" },
  { en: "landslide", th: "ดินถล่ม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "avalanche", th: "หิมะถล่ม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "wildfire", th: "ไฟป่า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🔥" },
  { en: "eruption", th: "การปะทุของภูเขาไฟ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌋" },
  { en: "famine", th: "ทุพภิกขภัย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "environment", th: "สิ่งแวดล้อม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌍" },
  { en: "ecosystem", th: "ระบบนิเวศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "biodiversity", th: "ความหลากหลายทางชีวภาพ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "pollution", th: "มลพิษ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "air pollution", th: "มลพิษทางอากาศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "water pollution", th: "มลพิษทางน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "climate change", th: "การเปลี่ยนแปลงสภาพภูมิอากาศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "global warming", th: "ภาวะโลกร้อน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌡️" },
  { en: "greenhouse effect", th: "ปรากฏการณ์เรือนกระจก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "carbon emission", th: "การปล่อยคาร์บอน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "deforestation", th: "การตัดไม้ทำลายป่า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "reforestation", th: "การปลูกป่าทดแทน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌱" },
  { en: "conservation", th: "การอนุรักษ์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "recycling", th: "การรีไซเคิล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "♻️" },
  { en: "sustainability", th: "ความยั่งยืน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "renewable energy", th: "พลังงานหมุนเวียน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "solar energy", th: "พลังงานแสงอาทิตย์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "☀️" },
  { en: "wind energy", th: "พลังงานลม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "💨" },
  { en: "fossil fuel", th: "เชื้อเพลิงฟอสซิล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "natural resource", th: "ทรัพยากรธรรมชาติ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "habitat", th: "ถิ่นที่อยู่อาศัย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "extinction", th: "การสูญพันธุ์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "endangered species", th: "สัตว์ใกล้สูญพันธุ์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "erosion", th: "การกัดเซาะ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "sediment", th: "ตะกอน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "ozone layer", th: "ชั้นโอโซน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "atmosphere", th: "ชั้นบรรยากาศ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "ecology", th: "นิเวศวิทยา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "organic", th: "อินทรีย์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "pesticide", th: "ยาฆ่าแมลง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "fertilizer", th: "ปุ๋ย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "contamination", th: "การปนเปื้อน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "carbon footprint", th: "รอยเท้าคาร์บอน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "planet", th: "ดาวเคราะห์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🪐" },
  { en: "earth", th: "โลก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌍" },
  { en: "mars", th: "ดาวอังคาร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🔴" },
  { en: "venus", th: "ดาวศุกร์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "jupiter", th: "ดาวพฤหัสบดี", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🪐" },
  { en: "saturn", th: "ดาวเสาร์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🪐" },
  { en: "mercury", th: "ดาวพุธ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "neptune", th: "ดาวเนปจูน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "uranus", th: "ดาวยูเรนัส", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "pluto", th: "ดาวพลูโต", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "galaxy", th: "กาแล็กซี", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌌" },
  { en: "universe", th: "จักรวาล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌌" },
  { en: "comet", th: "ดาวหาง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "☄️" },
  { en: "meteor", th: "ดาวตก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "☄️" },
  { en: "asteroid", th: "ดาวเคราะห์น้อย", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "☄️" },
  { en: "satellite", th: "ดาวเทียม", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🛰️" },
  { en: "orbit", th: "วงโคจร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "eclipse", th: "สุริยุปราคา/จันทรุปราคา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "constellation", th: "กลุ่มดาว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "✨" },
  { en: "solar system", th: "ระบบสุริยะ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🪐" },
  { en: "gravity", th: "แรงโน้มถ่วง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "cosmos", th: "จักรวาล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌌" },
  { en: "telescope", th: "กล้องโทรทรรศน์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🔭" },
  { en: "horizon", th: "เส้นขอบฟ้า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "humidity level", th: "ระดับความชื้น", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "puddle", th: "แอ่งน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "💧" },
  { en: "stone", th: "ก้อนหิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🪨" },
  { en: "field", th: "ทุ่งนา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌾" },
  { en: "path", th: "ทางเดิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "summit", th: "ยอดเขา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "⛰️" },
  { en: "ridge", th: "สันเขา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "bedrock", th: "ชั้นหินแข็ง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "mineral", th: "แร่ธาตุ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "crystal", th: "ผลึก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "💎" },
  { en: "magma", th: "หินหนืด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🌋" },
  { en: "lava", th: "ลาวา", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌋" },
  { en: "tide", th: "น้ำขึ้นน้ำลง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌊" },
  { en: "wave", th: "คลื่น", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🌊" },
  { en: "current", th: "กระแสน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "ocean", th: "มหาสมุทร", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌊" },
  { en: "sea", th: "ทะเล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A1", emoji: "🌊" },
  { en: "reef", th: "แนวปะการัง", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "estuary", th: "ปากแม่น้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "geyser", th: "น้ำพุร้อนธรรมชาติ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "hot spring", th: "บ่อน้ำพุร้อน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "♨️" },
  { en: "permafrost", th: "ชั้นดินเยือกแข็งคงตัว", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C2", emoji: "" },
  { en: "biome", th: "เขตชีวภาพ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C2", emoji: "" },
  { en: "canopy", th: "เรือนยอดไม้", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "🌳" },
  { en: "undergrowth", th: "พุ่มไม้เตี้ยในป่า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "topsoil", th: "หน้าดิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "watershed", th: "พื้นที่ลุ่มน้ำ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "groundwater", th: "น้ำใต้ดิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "aquifer", th: "ชั้นน้ำใต้ดิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C2", emoji: "" },
  { en: "irrigation", th: "การชลประทาน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "fertile soil", th: "ดินอุดมสมบูรณ์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "barren land", th: "ดินแห้งแล้งไม่อุดมสมบูรณ์", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "rock formation", th: "โครงสร้างหิน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "limestone", th: "หินปูน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "granite", th: "หินแกรนิต", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "marble", th: "หินอ่อน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "fossil", th: "ฟอสซิล", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🦴" },
  { en: "sedimentary rock", th: "หินตะกอน", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C1", emoji: "" },
  { en: "igneous rock", th: "หินอัคนี", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "C2", emoji: "" },
  { en: "greenhouse gas", th: "แก๊สเรือนกระจก", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "" },
  { en: "acid rain", th: "ฝนกรด", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🌧️" },
  { en: "smog", th: "หมอกควันพิษ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B2", emoji: "🌫️" },
  { en: "nature reserve", th: "เขตอนุรักษ์ธรรมชาติ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "" },
  { en: "national park", th: "อุทยานแห่งชาติ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "🏞️" },
  { en: "wildlife", th: "สัตว์ป่า", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "A2", emoji: "" },
  { en: "vegetation", th: "พืชพรรณ", category: "ธรรมชาติ สภาพอากาศ และสิ่งแวดล้อม", level: "B1", emoji: "🌿" },
  { en: "polygon", th: "รูปหลายเหลี่ยม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "🔺" },
  { en: "diameter", th: "เส้นผ่านศูนย์กลาง", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "⭕" },
  { en: "radius", th: "รัศมี", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "⭕" },
  { en: "perimeter", th: "เส้นรอบรูป", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "📏" },
  { en: "vertex", th: "จุดยอด", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "📐" },
  { en: "fortnight", th: "ช่วงสองสัปดาห์", category: "เวลาและปฏิทิน", level: "B2", emoji: "📅" },
  { en: "millennium", th: "สหัสวรรษ", category: "เวลาและปฏิทิน", level: "B2", emoji: "📅" },
  { en: "curfew", th: "เคอร์ฟิว", category: "เวลาและปฏิทิน", level: "B2", emoji: "🌙" },
  { en: "rush hour", th: "ชั่วโมงเร่งด่วน", category: "เวลาและปฏิทิน", level: "B1", emoji: "🚗" },
  { en: "daylight saving time", th: "เวลาออมแสง", category: "เวลาและปฏิทิน", level: "C1", emoji: "☀️" },
  { en: "solstice", th: "วันครีษมายัน", category: "เวลาและปฏิทิน", level: "C1", emoji: "☀️" },
  { en: "equinox", th: "วันวิษุวัต", category: "เวลาและปฏิทิน", level: "C1", emoji: "🌗" },
  { en: "wildebeest", th: "วิลเดอบีสต์", category: "สัตว์", level: "C1", emoji: "🐃" },
  { en: "chinchilla", th: "ชินชิลล่า", category: "สัตว์", level: "B2", emoji: "🐹" },
  { en: "porcupine", th: "เม่นใหญ่", category: "สัตว์", level: "B1", emoji: "🦔" },
  { en: "gazelle", th: "ละมั่ง", category: "สัตว์", level: "B1", emoji: "🦌" },
  { en: "narwhal", th: "วาฬนาร์วาล", category: "สัตว์", level: "C1", emoji: "🐋" },
  { en: "manta ray", th: "ปลากระเบนราหู", category: "สัตว์", level: "B2", emoji: "🐟" },
  { en: "pufferfish", th: "ปลาปักเป้า", category: "สัตว์", level: "B1", emoji: "🐡" },
  { en: "hermit crab", th: "ปูเสฉวน", category: "สัตว์", level: "B1", emoji: "🦀" },
  { en: "prairie dog", th: "แพรี่ด็อก", category: "สัตว์", level: "C1", emoji: "🐿️" },
  { en: "tapir", th: "สมเสร็จ", category: "สัตว์", level: "C1", emoji: "🐖" }
];
