const VOCAB_PART_10 = [
  { en: "government", th: "รัฐบาล", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "🏛️" },
  { en: "democracy", th: "ประชาธิปไตย", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "🗳️" },
  { en: "constitution", th: "รัฐธรรมนูญ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "parliament", th: "รัฐสภา", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "🏛️" },
  { en: "congress", th: "สภาคองเกรส", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "senate", th: "วุฒิสภา", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "election", th: "การเลือกตั้ง", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "🗳️" },
  { en: "vote", th: "โหวต/ลงคะแนนเสียง", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "🗳️" },
  { en: "voter", th: "ผู้มีสิทธิเลือกตั้ง", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "president", th: "ประธานาธิบดี", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "" },
  { en: "prime minister", th: "นายกรัฐมนตรี", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "" },
  { en: "minister", th: "รัฐมนตรี", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "citizenship", th: "สัญชาติ/ความเป็นพลเมือง", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "nationality", th: "สัญชาติ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "law", th: "กฎหมาย", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "⚖️" },
  { en: "legal", th: "ถูกกฎหมาย", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "illegal", th: "ผิดกฎหมาย", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "justice", th: "ความยุติธรรม", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "⚖️" },
  { en: "court", th: "ศาล", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "⚖️" },
  { en: "jury", th: "คณะลูกขุน", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "trial", th: "การพิจารณาคดี", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "lawsuit", th: "คดีความ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "crime", th: "อาชญากรรม", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "🚨" },
  { en: "criminal", th: "อาชญากร", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "felony", th: "อาชญากรรมร้ายแรง", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "misdemeanor", th: "ความผิดลหุโทษ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "arrest", th: "จับกุม", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "🚔" },
  { en: "police", th: "ตำรวจ", category: "สังคม กฎหมาย และการปกครอง", level: "A1", emoji: "👮" },
  { en: "jail", th: "คุก", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "" },
  { en: "sentence", th: "คำพิพากษา/บทลงโทษ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "punishment", th: "การลงโทษ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "bail", th: "เงินประกันตัว", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "evidence", th: "หลักฐาน", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "testimony", th: "คำให้การ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "verdict", th: "คำตัดสินของศาล", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "appeal", th: "การอุทธรณ์", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "rights", th: "สิทธิ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "human rights", th: "สิทธิมนุษยชน", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "freedom", th: "เสรีภาพ", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "🕊️" },
  { en: "liberty", th: "เสรีภาพ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "equality", th: "ความเท่าเทียมกัน", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "inequality", th: "ความไม่เท่าเทียมกัน", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "discrimination", th: "การเลือกปฏิบัติ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "racism", th: "การเหยียดเชื้อชาติ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "sexism", th: "การเหยียดเพศ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "prejudice", th: "อคติ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "tolerance", th: "การยอมรับความแตกต่าง", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "diversity", th: "ความหลากหลาย", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "refugee", th: "ผู้ลี้ภัย", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "asylum", th: "การลี้ภัย", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "policy", th: "นโยบาย", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "politics", th: "การเมือง", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "" },
  { en: "political party", th: "พรรคการเมือง", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "campaign", th: "การรณรงค์หาเสียง", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "protest", th: "การประท้วง", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "📢" },
  { en: "demonstration", th: "การชุมนุมประท้วง", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "activist", th: "นักเคลื่อนไหวทางสังคม", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "activism", th: "การเคลื่อนไหวเพื่อสังคม", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "petition", th: "คำร้อง/หนังสือเรียกร้อง", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "corruption", th: "การทุจริตคอร์รัปชัน", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "bribery", th: "การติดสินบน", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "propaganda", th: "การโฆษณาชวนเชื่อ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "censorship", th: "การเซ็นเซอร์/ตรวจสอบสื่อ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "dictatorship", th: "ระบอบเผด็จการ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "monarchy", th: "ระบอบราชาธิปไตย", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "👑" },
  { en: "republic", th: "สาธารณรัฐ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "sovereignty", th: "อำนาจอธิปไตย", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "independence", th: "เอกราช/ความเป็นอิสระ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "treaty", th: "สนธิสัญญา", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "diplomacy", th: "การทูต", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "ambassador", th: "เอกอัครราชทูต", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "foreign policy", th: "นโยบายต่างประเทศ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "national security", th: "ความมั่นคงของชาติ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "terrorism", th: "การก่อการร้าย", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "war", th: "สงคราม", category: "สังคม กฎหมาย และการปกครอง", level: "A1", emoji: "" },
  { en: "peace", th: "สันติภาพ", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "☮️" },
  { en: "conflict", th: "ความขัดแย้ง", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "referendum", th: "การลงประชามติ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "taxation", th: "ระบบภาษี", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "welfare", th: "สวัสดิการ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "social security", th: "ประกันสังคม", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "public sector", th: "ภาครัฐ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "private sector", th: "ภาคเอกชน", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "bureaucracy", th: "ระบบราชการ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "legislation", th: "กฎหมาย/บทบัญญัติ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "amendment", th: "การแก้ไขเพิ่มเติมกฎหมาย", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "regulation", th: "กฎระเบียบ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "civil rights", th: "สิทธิพลเมือง", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "civil society", th: "ประชาสังคม", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "NGO", th: "องค์กรพัฒนาเอกชน", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "charity", th: "องค์กรการกุศล", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "poverty", th: "ความยากจน", category: "สังคม กฎหมาย และการปกครอง", level: "A2", emoji: "" },
  { en: "homelessness", th: "ภาวะไร้บ้าน", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "unemployment", th: "การว่างงาน", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "minority", th: "ชนกลุ่มน้อย", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "majority", th: "เสียงข้างมาก", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "social class", th: "ชนชั้นทางสังคม", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "social justice", th: "ความยุติธรรมทางสังคม", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "gender equality", th: "ความเท่าเทียมทางเพศ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "domestic violence", th: "ความรุนแรงในครอบครัว", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "abuse", th: "การล่วงละเมิด/การทำร้าย", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "neglect", th: "การละเลย", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "custody", th: "สิทธิ์ปกครองบุตร/การควบคุมตัว", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "property", th: "ทรัพย์สิน", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "ownership", th: "กรรมสิทธิ์", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "plaintiff", th: "โจทก์", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "defendant", th: "จำเลย", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "guilty", th: "มีความผิด", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "innocent", th: "บริสุทธิ์(ไม่มีความผิด)", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "probation", th: "การคุมประพฤติ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "parole", th: "การพักโทษ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "civic duty", th: "หน้าที่พลเมือง", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "public opinion", th: "ความคิดเห็นสาธารณะ", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "surveillance", th: "การเฝ้าระวัง/สอดแนม", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "privacy", th: "ความเป็นส่วนตัว", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "freedom of speech", th: "เสรีภาพในการพูด", category: "สังคม กฎหมาย และการปกครอง", level: "B2", emoji: "" },
  { en: "freedom of the press", th: "เสรีภาพสื่อมวลชน", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "authority", th: "อำนาจ/เจ้าหน้าที่รัฐ", category: "สังคม กฎหมาย และการปกครอง", level: "B1", emoji: "" },
  { en: "legislature", th: "ฝ่ายนิติบัญญัติ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "judiciary", th: "ฝ่ายตุลาการ", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "executive branch", th: "ฝ่ายบริหาร", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "human trafficking", th: "การค้ามนุษย์", category: "สังคม กฎหมาย และการปกครอง", level: "C1", emoji: "" },
  { en: "atom", th: "อะตอม", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "molecule", th: "โมเลกุล", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "electron", th: "อิเล็กตรอน", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "proton", th: "โปรตอน", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "neutron", th: "นิวตรอน", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "nucleus", th: "นิวเคลียส", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "element", th: "ธาตุ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "compound", th: "สารประกอบ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "chemical reaction", th: "ปฏิกิริยาเคมี", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "mixture", th: "สารผสม", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "solution", th: "สารละลาย", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "acid", th: "กรด", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "alkali", th: "ด่าง", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "pH", th: "ค่าพีเอช", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "catalyst", th: "ตัวเร่งปฏิกิริยา", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "enzyme", th: "เอนไซม์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "cell", th: "เซลล์", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "tissue", th: "เนื้อเยื่อ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "organ", th: "อวัยวะ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "organism", th: "สิ่งมีชีวิต", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "genetics", th: "พันธุศาสตร์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "gene", th: "ยีน", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "DNA", th: "ดีเอ็นเอ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "🧬" },
  { en: "RNA", th: "อาร์เอ็นเอ", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "chromosome", th: "โครโมโซม", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "evolution", th: "วิวัฒนาการ", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "natural selection", th: "การคัดเลือกโดยธรรมชาติ", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "photosynthesis", th: "การสังเคราะห์แสง", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "respiration", th: "การหายใจระดับเซลล์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "metabolism", th: "เมแทบอลิซึม/กระบวนการเผาผลาญ", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "microorganism", th: "จุลินทรีย์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "mutation", th: "การกลายพันธุ์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "heredity", th: "กรรมพันธุ์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "mass", th: "มวล", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "force", th: "แรง", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "energy", th: "พลังงาน", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "⚡" },
  { en: "velocity", th: "ความเร็ว(เชิงเวกเตอร์)", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "acceleration", th: "ความเร่ง", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "momentum", th: "โมเมนตัม", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "friction", th: "แรงเสียดทาน", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "density", th: "ความหนาแน่น", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "volume", th: "ปริมาตร", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "pressure", th: "ความดัน", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "heat", th: "ความร้อน", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "matter", th: "สสาร", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "liquid", th: "ของเหลว", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "gas", th: "แก๊ส", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "plasma", th: "พลาสมา(สถานะของสสาร)", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "frequency", th: "ความถี่", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "wavelength", th: "ความยาวคลื่น", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "sound wave", th: "คลื่นเสียง", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "radiation", th: "รังสี", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "electricity", th: "ไฟฟ้า", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "⚡" },
  { en: "electric current", th: "กระแสไฟฟ้า", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "voltage", th: "แรงดันไฟฟ้า", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "magnetism", th: "อำนาจแม่เหล็ก", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "magnetic field", th: "สนามแม่เหล็ก", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "circuit", th: "วงจรไฟฟ้า", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "conductor", th: "ตัวนำไฟฟ้า", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "insulator", th: "ฉนวนไฟฟ้า", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "nuclear energy", th: "พลังงานนิวเคลียร์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "radioactivity", th: "กัมมันตภาพรังสี", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "quantum", th: "ควอนตัม", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "relativity", th: "ทฤษฎีสัมพัทธภาพ", category: "วิทยาศาสตร์และวิชาการ", level: "C2", emoji: "" },
  { en: "hypothesis", th: "สมมติฐาน", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "theory", th: "ทฤษฎี", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "experiment", th: "การทดลอง", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "🧪" },
  { en: "observation", th: "การสังเกต", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "variable", th: "ตัวแปร", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "control group", th: "กลุ่มควบคุม", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "data", th: "ข้อมูล", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "analysis", th: "การวิเคราะห์", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "conclusion", th: "บทสรุป", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "research", th: "การวิจัย", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "laboratory", th: "ห้องปฏิบัติการ", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "🔬" },
  { en: "specimen", th: "ตัวอย่างศึกษา", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "sample", th: "ตัวอย่างที่ใช้ทดสอบ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "measurement", th: "การวัด", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "calculation", th: "การคำนวณ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "formula", th: "สูตร", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "equation", th: "สมการ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "method", th: "วิธีการ", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "methodology", th: "ระเบียบวิธีวิจัย", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "publication", th: "สิ่งตีพิมพ์", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "academic journal", th: "วารสารวิชาการ", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "citation", th: "การอ้างอิง", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "reference", th: "เอกสารอ้างอิง", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "bibliography", th: "บรรณานุกรม", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "academic", th: "ทางวิชาการ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "scholar", th: "นักวิชาการ", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "field of study", th: "สาขาวิชา", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "discipline", th: "สาขาวิชา/วินัย", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "astronomy", th: "ดาราศาสตร์", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "🔭" },
  { en: "geology", th: "ธรณีวิทยา", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "carbon dioxide", th: "คาร์บอนไดออกไซด์", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "oxygen", th: "ออกซิเจน", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "hydrogen", th: "ไฮโดรเจน", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "nitrogen", th: "ไนโตรเจน", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "water cycle", th: "วัฏจักรของน้ำ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "adaptation", th: "การปรับตัว", category: "วิทยาศาสตร์และวิชาการ", level: "B2", emoji: "" },
  { en: "statistics", th: "สถิติ", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "probability", th: "ความน่าจะเป็น", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "correlation", th: "ความสัมพันธ์เชิงสถิติ", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "causation", th: "ความสัมพันธ์เชิงเหตุผล", category: "วิทยาศาสตร์และวิชาการ", level: "C1", emoji: "" },
  { en: "innovation", th: "นวัตกรรม", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "invention", th: "สิ่งประดิษฐ์", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "💡" },
  { en: "discovery", th: "การค้นพบ", category: "วิทยาศาสตร์และวิชาการ", level: "A2", emoji: "" },
  { en: "scientific method", th: "วิธีการทางวิทยาศาสตร์", category: "วิทยาศาสตร์และวิชาการ", level: "B1", emoji: "" },
  { en: "palette", th: "จานสี", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "🎨" },
  { en: "portrait", th: "ภาพเหมือนบุคคล", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "landscape painting", th: "ภาพวาดทิวทัศน์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "still life", th: "ภาพวาดหุ่นนิ่ง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "abstract art", th: "ศิลปะนามธรรม", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "masterpiece", th: "ผลงานชิ้นเอก", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "exhibition", th: "นิทรรศการ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "art gallery", th: "หอศิลป์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🖼️" },
  { en: "sketch", th: "ภาพร่าง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "✏️" },
  { en: "illustration", th: "ภาพประกอบ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "mural", th: "ภาพจิตรกรรมฝาผนัง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "watercolor", th: "สีน้ำ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "oil painting", th: "ภาพสีน้ำมัน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "art critic", th: "นักวิจารณ์ศิลปะ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "curator", th: "ภัณฑารักษ์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "C1", emoji: "" },
  { en: "ceramics", th: "เครื่องปั้นดินเผา", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "collage", th: "ภาพปะติด", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "song", th: "เพลง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A1", emoji: "🎵" },
  { en: "melody", th: "ทำนองเพลง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "🎶" },
  { en: "harmony", th: "เสียงประสาน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "rhythm", th: "จังหวะ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "tempo", th: "จังหวะความเร็วของเพลง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "beat", th: "จังหวะเคาะ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🥁" },
  { en: "lyrics", th: "เนื้อเพลง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "chord", th: "คอร์ดดนตรี", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "musical scale", th: "บันไดเสียง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "orchestra", th: "วงออร์เคสตรา", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "🎻" },
  { en: "symphony", th: "ซิมโฟนี", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "concert", th: "คอนเสิร์ต", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🎤" },
  { en: "band", th: "วงดนตรี", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🎸" },
  { en: "choir", th: "คณะนักร้องประสานเสียง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "vocalist", th: "นักร้องนำ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "guitar", th: "กีตาร์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A1", emoji: "🎸" },
  { en: "piano", th: "เปียโน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A1", emoji: "🎹" },
  { en: "violin", th: "ไวโอลิน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🎻" },
  { en: "cello", th: "เชลโล", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "drum", th: "กลอง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🥁" },
  { en: "trumpet", th: "ทรัมเป็ต", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🎺" },
  { en: "saxophone", th: "แซกโซโฟน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "🎷" },
  { en: "flute", th: "ฟลุต/ขลุ่ยฝรั่ง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "clarinet", th: "คลาริเน็ต", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "harp", th: "พิณ/ฮาร์ป", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "ukulele", th: "อูคูเลเล่", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "amplifier", th: "เครื่องขยายเสียง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "genre", th: "แนวเพลง/แนวศิลปะ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "pop music", th: "เพลงป๊อป", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "rock music", th: "เพลงร็อก", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "jazz", th: "แจ๊ส", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "classical music", th: "ดนตรีคลาสสิก", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "hip hop", th: "ฮิปฮอป", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "opera", th: "อุปรากร/โอเปร่า", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "album", th: "อัลบั้มเพลง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "💿" },
  { en: "movie", th: "ภาพยนตร์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A1", emoji: "🎬" },
  { en: "screenplay", th: "บทภาพยนตร์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "scene", th: "ฉาก", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "plot", th: "โครงเรื่อง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "protagonist", th: "ตัวเอกของเรื่อง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "antagonist", th: "ตัวร้าย/ปฏิปักษ์ของเรื่อง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "audience", th: "ผู้ชม", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "stage", th: "เวที", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "performance", th: "การแสดง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "rehearsal", th: "การซ้อม", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "costume", th: "เครื่องแต่งกายสำหรับแสดง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "special effects", th: "เทคนิคพิเศษ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "animation", th: "แอนิเมชัน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "documentary", th: "สารคดี", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "sitcom", th: "ซิตคอม", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "📺" },
  { en: "comedy", th: "หนัง/ละครตลก", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "😂" },
  { en: "tragedy", th: "โศกนาฏกรรม", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "thriller", th: "หนังระทึกขวัญ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "" },
  { en: "horror movie", th: "หนังสยองขวัญ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "👻" },
  { en: "blockbuster", th: "ภาพยนตร์ทำเงินถล่มทลาย", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "box office", th: "รายได้จากการฉายภาพยนตร์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "premiere", th: "การฉายรอบปฐมทัศน์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "film critic", th: "นักวิจารณ์ภาพยนตร์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "award", th: "รางวัล", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🏆" },
  { en: "celebrity", th: "คนดัง/คนมีชื่อเสียง", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "⭐" },
  { en: "fandom", th: "กลุ่มแฟนคลับ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B2", emoji: "" },
  { en: "episode", th: "ตอนของซีรีส์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "📺" },
  { en: "subtitle", th: "คำบรรยายใต้ภาพ", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "" },
  { en: "stand-up comedy", th: "การแสดงเดี่ยวไมโครโฟน", category: "ศิลปะ ดนตรี และความบันเทิง", level: "B1", emoji: "🎤" },
  { en: "circus", th: "ละครสัตว์/คณะละครสัตว์", category: "ศิลปะ ดนตรี และความบันเทิง", level: "A2", emoji: "🎪" },
  { en: "give up", th: "ยอมแพ้/เลิกล้ม", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "🏳️" },
  { en: "look forward to", th: "ตั้งตารอ", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "get up", th: "ลุกขึ้น/ตื่นนอน", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "wake up", th: "ตื่นนอน", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "⏰" },
  { en: "turn off", th: "ปิด(เครื่องใช้ไฟฟ้า)", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "turn on", th: "เปิด(เครื่องใช้ไฟฟ้า)", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "turn down", th: "ปฏิเสธ/หรี่เสียงลง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "turn up", th: "มาปรากฏตัว/เร่งเสียงขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "put off", th: "เลื่อนออกไป", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "put on", th: "สวมใส่", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "take off", th: "ถอดออก/เครื่องบินขึ้นบิน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "✈️" },
  { en: "take up", th: "เริ่มทำงานอดิเรก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "bring up", th: "เลี้ยงดู/หยิบยกขึ้นมาพูด", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "bring back", th: "นำกลับมา", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "come across", th: "บังเอิญพบเจอ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "come up with", th: "คิดหาไอเดียหรือวิธีได้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "come back", th: "กลับมา", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "go on", th: "ดำเนินต่อไป/เกิดขึ้น", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "go over", th: "ทบทวน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "go through", th: "ประสบ/ผ่านพ้นเหตุการณ์", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "break down", th: "เสีย(เครื่องยนต์)/เสียใจร้องไห้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "break up", th: "เลิกกัน(ความสัมพันธ์)", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💔" },
  { en: "break out", th: "เกิดขึ้นอย่างฉับพลัน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "carry on", th: "ทำต่อไป", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "carry out", th: "ดำเนินการ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "call off", th: "ยกเลิก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "figure out", th: "คิดออก/หาคำตอบได้", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "find out", th: "ค้นพบ/หาข้อมูล", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "fill out", th: "กรอกแบบฟอร์ม", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "get along", th: "เข้ากันได้ดี", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "get over", th: "ทำใจได้/หายจาก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "get through", th: "ผ่านพ้นไปได้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "hang out", th: "ไปเที่ยวเล่นด้วยกัน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "hang up", th: "วางสายโทรศัพท์", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "📞" },
  { en: "keep up", th: "ตามให้ทัน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "look after", th: "ดูแล", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "look into", th: "ตรวจสอบ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "look up", th: "ค้นหาข้อมูล", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "make up", th: "คืนดีกัน/แต่งเรื่องขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "pass away", th: "เสียชีวิต", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "pick up", th: "หยิบขึ้นมา/ไปรับ", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "" },
  { en: "point out", th: "ชี้ให้เห็น", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "pull over", th: "จอดรถข้างทาง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "run out of", th: "ใช้หมด", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "set up", th: "จัดตั้ง/ติดตั้ง", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "show up", th: "มาปรากฏตัว", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "" },
  { en: "sort out", th: "จัดการให้เรียบร้อย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "stand out", th: "โดดเด่น", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "stand up for", th: "ปกป้องสิทธิหรือความคิดเห็น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "work out", th: "ออกกำลังกาย/หาทางออกได้", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💪" },
  { en: "break the ice", th: "ทำให้บรรยากาศเป็นกันเองมากขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "🧊" },
  { en: "hit the books", th: "ตั้งใจอ่านหนังสือหนัก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "📚" },
  { en: "under the weather", th: "รู้สึกไม่สบาย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "🤒" },
  { en: "piece of cake", th: "เรื่องง่ายมาก", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "🍰" },
  { en: "cost an arm and a leg", th: "มีราคาแพงมาก", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "once in a blue moon", th: "นานๆ ครั้ง แทบไม่เคยเกิดขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "let the cat out of the bag", th: "เผยความลับโดยไม่ตั้งใจ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "🐱" },
  { en: "kill two birds with one stone", th: "ยิงปืนนัดเดียวได้นกสองตัว", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "spill the beans", th: "เปิดเผยความลับ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "the ball is in your court", th: "ตอนนี้เป็นตาคุณต้องตัดสินใจ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "bite the bullet", th: "ยอมรับสิ่งที่ยากลำบากด้วยความอดทน", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "hit the sack", th: "เข้านอน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "🛏️" },
  { en: "speak of the devil", th: "พูดถึงก็มาพอดี", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "on the ball", th: "ว่องไวกระตือรือร้น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "through thick and thin", th: "ร่วมทุกข์ร่วมสุขไม่ว่าจะเกิดอะไรขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "a blessing in disguise", th: "โชคร้ายที่กลายเป็นโชคดี", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "barking up the wrong tree", th: "เข้าใจผิด/หาสาเหตุผิดที่", category: "สำนวนและ Phrasal Verbs", level: "C1", emoji: "" },
  { en: "beat around the bush", th: "พูดอ้อมค้อมไม่เข้าประเด็น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "break a leg", th: "ขอให้โชคดีก่อนแสดง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "call it a day", th: "เลิกงานสำหรับวันนี้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "cut corners", th: "ลดขั้นตอนเพื่อประหยัดเวลาหรือเงินจนเสียคุณภาพ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "get out of hand", th: "ควบคุมไม่ได้", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "hit the nail on the head", th: "พูดถูกจุด/ตรงประเด็นมาก", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "in the same boat", th: "อยู่ในสถานการณ์เดียวกัน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "keep an eye on", th: "คอยจับตาดู", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "👀" },
  { en: "make a long story short", th: "พูดสั้นๆ ให้เข้าใจง่าย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "miss the boat", th: "พลาดโอกาส", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "on the fence", th: "ยังไม่ตัดสินใจ/ลังเล", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "out of the blue", th: "อยู่ๆ ก็เกิดขึ้นโดยไม่คาดคิด", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "pull someone's leg", th: "ล้อเล่น/หลอกเล่นๆ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "see eye to eye", th: "มีความเห็นตรงกัน", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "the last straw", th: "ฟางเส้นสุดท้ายที่ทำให้ทนไม่ไหวอีกต่อไป", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "the tip of the iceberg", th: "เป็นเพียงส่วนเล็กๆ ของปัญหาใหญ่", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "🧊" },
  { en: "time flies", th: "เวลาผ่านไปเร็วมาก", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "⏳" },
  { en: "under the table", th: "ทำอย่างลับๆ ผิดกฎหมาย", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "up in the air", th: "ยังไม่แน่นอน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "water under the bridge", th: "เรื่องที่ผ่านไปแล้วให้มันผ่านไป", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "when pigs fly", th: "ไม่มีทางเกิดขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "🐷" },
  { en: "a piece of the pie", th: "ส่วนแบ่งผลประโยชน์", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "back to square one", th: "กลับไปเริ่มต้นใหม่", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "best of both worlds", th: "ได้ข้อดีจากทั้งสองทาง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "burn the midnight oil", th: "ทำงานหรืออ่านหนังสือดึกมาก", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "🕯️" },
  { en: "by the skin of your teeth", th: "รอดมาได้อย่างหวุดหวิด", category: "สำนวนและ Phrasal Verbs", level: "C1", emoji: "" },
  { en: "crystal clear", th: "ชัดเจนมาก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "easier said than done", th: "พูดง่ายกว่าทำ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "every cloud has a silver lining", th: "ในทุกเรื่องร้ายย่อมมีแง่ดีซ่อนอยู่", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "go the extra mile", th: "ทุ่มเทมากกว่าที่คาดหวัง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "" },
  { en: "hit the road", th: "ออกเดินทาง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "🚗" },
  { en: "it's raining cats and dogs", th: "ฝนตกหนักมาก", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "🌧️" },
  { en: "actions speak louder than words", th: "การกระทำสำคัญกว่าคำพูด", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "" },
  { en: "dress shoes", th: "รองเท้าหนังทางการ", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👞" },
  { en: "pointe shoes", th: "รองเท้าบัลเลต์ปลายแข็ง", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "🩰" },
  { en: "cargo pants", th: "กางเกงคาร์โก้", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👖" },
  { en: "capri pants", th: "กางเกงขาสามส่วน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👖" },
  { en: "culottes", th: "กางเกงขาม้าทรงกระโปรง", category: "เสื้อผ้าและเครื่องประดับ", level: "C1", emoji: "👗" },
  { en: "maxi dress", th: "เดรสยาว", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👗" },
  { en: "sundress", th: "เดรสใส่หน้าร้อน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👗" },
  { en: "cocktail dress", th: "ชุดเดรสค็อกเทล", category: "เสื้อผ้าและเครื่องประดับ", level: "B2", emoji: "👗" },
  { en: "wedding gown", th: "ชุดแต่งงาน", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "👰" },
  { en: "graduation gown", th: "ชุดครุย", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "🎓" },
  { en: "lab coat", th: "เสื้อกาวน์ห้องแล็บ", category: "เสื้อผ้าและเครื่องประดับ", level: "B1", emoji: "🥼" },
  { en: "bib", th: "ผ้ากันเปื้อนเด็ก", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "👶" },
  { en: "hair tie", th: "ยางรัดผม", category: "เสื้อผ้าและเครื่องประดับ", level: "A1", emoji: "💇" },
  { en: "bobby pin", th: "กิ๊บติดผม", category: "เสื้อผ้าและเครื่องประดับ", level: "A2", emoji: "💇" },
  { en: "ecstatic", th: "ดีใจสุดขีด", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🤩" },
  { en: "melancholy", th: "เศร้าหมองซึมเซา", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "😔" },
  { en: "nostalgic", th: "คิดถึงอดีต", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🥹" },
  { en: "apathetic", th: "เฉยเมยไม่สนใจ", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "😐" },
  { en: "resentful", th: "ไม่พอใจฝังใจ", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "😒" },
  { en: "vindictive", th: "มุ่งร้ายอาฆาตแค้น", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "😠" },
  { en: "gullible", th: "หลงเชื่อคนง่าย", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "😳" },
  { en: "assertive", th: "กล้าแสดงออก", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "💪" },
  { en: "meticulous", th: "พิถีพิถันละเอียด", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "🔍" },
  { en: "impulsive", th: "หุนหันพลันแล่น", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "⚡" },
  { en: "cynical", th: "มองโลกในแง่ร้ายแบบเยาะเย้ย", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "🙄" },
  { en: "skeptical", th: "ขี้สงสัยไม่เชื่อง่าย", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🤨" },
  { en: "sarcastic", th: "พูดจาเสียดสี", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "😏" },
  { en: "indecisive", th: "ลังเลตัดสินใจไม่ได้", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🤷" },
  { en: "thoughtful", th: "ช่างคิดเอาใจใส่", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "💭" },
  { en: "considerate", th: "เห็นอกเห็นใจผู้อื่น", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🤗" },
  { en: "forgiving", th: "ให้อภัยง่าย", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🕊️" },
  { en: "self-centered", th: "เห็นแก่ตัวเอง", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🪞" },
  { en: "down-to-earth", th: "เรียบง่ายติดดิน", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🌱" },
  { en: "level-headed", th: "มีสติควบคุมอารมณ์ได้", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🧠" },
  { en: "hot-tempered", th: "อารมณ์ร้อน", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🔥" },
  { en: "aloof", th: "เย็นชาไม่เข้าสังคม", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "🧊" },
  { en: "approachable", th: "เข้าถึงง่ายเป็นมิตร", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🙂" },
  { en: "sociable", th: "ชอบเข้าสังคม", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🗣️" },
  { en: "reserved", th: "เก็บตัวไม่ค่อยพูด", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🤐" },
  { en: "frank", th: "พูดตรงไปตรงมา", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🗨️" },
  { en: "candid", th: "ตรงไปตรงมาเปิดเผย", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🗨️" },
  { en: "discreet", th: "สุขุมรอบคอบเก็บความลับได้", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "🤫" },
  { en: "prudent", th: "รอบคอบระมัดระวัง", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "🧐" },
  { en: "daring", th: "กล้าเสี่ยง", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "🦸" },
  { en: "bashful", th: "ขี้อาย", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "😳" },
  { en: "possessive", th: "หวงมากเกินไป", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🫴" },
  { en: "clingy", th: "ติดคนอื่นมากเกินไป", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🫂" },
  { en: "independent", th: "พึ่งพาตัวเองได้", category: "อารมณ์และบุคลิกภาพ", level: "A2", emoji: "🚶" },
  { en: "resourceful", th: "หัวไวแก้ปัญหาเก่ง", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🧩" },
  { en: "disciplined", th: "มีระเบียบวินัย", category: "อารมณ์และบุคลิกภาพ", level: "B1", emoji: "📏" },
  { en: "tenacious", th: "ยึดมั่นไม่ยอมแพ้", category: "อารมณ์และบุคลิกภาพ", level: "C1", emoji: "🦾" },
  { en: "driven", th: "มุ่งมั่นทะเยอทะยาน", category: "อารมณ์และบุคลิกภาพ", level: "B2", emoji: "🎯" },
  { en: "blended family", th: "ครอบครัวผสม", category: "ครอบครัวและผู้คน", level: "B2", emoji: "👨‍👩‍👧‍👦" },
  { en: "nuclear family", th: "ครอบครัวเดี่ยว", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👨‍👩‍👧" },
  { en: "extended family", th: "ครอบครัวขยาย", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👪" },
  { en: "only son", th: "ลูกชายคนเดียว", category: "ครอบครัวและผู้คน", level: "A2", emoji: "👦" },
  { en: "only daughter", th: "ลูกสาวคนเดียว", category: "ครอบครัวและผู้คน", level: "A2", emoji: "👧" },
  { en: "great-grandchild", th: "เหลน", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👶" },
  { en: "great-uncle", th: "ปู่ทวดฝ่ายลุง", category: "ครอบครัวและผู้คน", level: "B2", emoji: "👴" },
  { en: "great-aunt", th: "ย่าทวดฝ่ายป้า", category: "ครอบครัวและผู้คน", level: "B2", emoji: "👵" },
  { en: "step-parent", th: "พ่อเลี้ยงหรือแม่เลี้ยง", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👨‍👧" },
  { en: "foster parent", th: "พ่อแม่อุปถัมภ์", category: "ครอบครัวและผู้คน", level: "B2", emoji: "👪" },
  { en: "foster child", th: "เด็กในอุปการะ", category: "ครอบครัวและผู้คน", level: "B2", emoji: "🧒" },
  { en: "surrogate mother", th: "แม่อุ้มบุญ", category: "ครอบครัวและผู้คน", level: "C1", emoji: "🤰" },
  { en: "birth mother", th: "แม่ผู้ให้กำเนิด", category: "ครอบครัวและผู้คน", level: "B2", emoji: "🤱" },
  { en: "adoptive parent", th: "พ่อแม่บุญธรรม", category: "ครอบครัวและผู้คน", level: "B2", emoji: "👪" },
  { en: "single parent", th: "พ่อหรือแม่เลี้ยงเดี่ยว", category: "ครอบครัวและผู้คน", level: "B1", emoji: "🧑‍👦" },
  { en: "homemaker", th: "แม่บ้านผู้ดูแลบ้าน", category: "ครอบครัวและผู้คน", level: "B1", emoji: "🏠" },
  { en: "life partner", th: "คู่ชีวิต", category: "ครอบครัวและผู้คน", level: "B1", emoji: "💑" },
  { en: "significant other", th: "คนสำคัญคนพิเศษ", category: "ครอบครัวและผู้คน", level: "B2", emoji: "💞" },
  { en: "blood relative", th: "ญาติทางสายเลือด", category: "ครอบครัวและผู้คน", level: "B2", emoji: "🩸" },
  { en: "distant relative", th: "ญาติห่างๆ", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👥" },
  { en: "next of kin", th: "ญาติที่ใกล้ชิดที่สุด", category: "ครอบครัวและผู้คน", level: "C1", emoji: "👥" },
  { en: "family tree", th: "แผนผังตระกูล", category: "ครอบครัวและผู้คน", level: "B1", emoji: "🌳" },
  { en: "family reunion", th: "การรวมญาติ", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👨‍👩‍👧‍👦" },
  { en: "family heirloom", th: "มรดกตกทอด", category: "ครอบครัวและผู้คน", level: "C1", emoji: "💍" },
  { en: "matchmaker", th: "คนจับคู่แต่งงาน", category: "ครอบครัวและผู้คน", level: "B2", emoji: "💘" },
  { en: "wedding anniversary", th: "วันครบรอบแต่งงาน", category: "ครอบครัวและผู้คน", level: "A2", emoji: "💍" },
  { en: "bridesmaid", th: "เพื่อนเจ้าสาว", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👰" },
  { en: "groomsman", th: "เพื่อนเจ้าบ่าว", category: "ครอบครัวและผู้คน", level: "B1", emoji: "🤵" },
  { en: "best man", th: "เพื่อนเจ้าบ่าวคนสำคัญ", category: "ครอบครัวและผู้คน", level: "B1", emoji: "🤵" },
  { en: "maid of honor", th: "เพื่อนเจ้าสาวคนสำคัญ", category: "ครอบครัวและผู้คน", level: "B1", emoji: "👰" },
  { en: "flower girl", th: "เด็กหญิงโปรยดอกไม้", category: "ครอบครัวและผู้คน", level: "A2", emoji: "💐" },
  { en: "ring bearer", th: "เด็กถือแหวนแต่งงาน", category: "ครอบครัวและผู้คน", level: "B1", emoji: "💍" },
  { en: "godparent", th: "พ่อแม่ทูนหัว", category: "ครอบครัวและผู้คน", level: "B2", emoji: "👪" },
  { en: "eyelid", th: "เปลือกตา", category: "ร่างกายและสุขภาพ", level: "B1", emoji: "👁️" },
  { en: "earlobe", th: "ติ่งหู", category: "ร่างกายและสุขภาพ", level: "B1", emoji: "👂" },
  { en: "collarbone", th: "กระดูกไหปลาร้า", category: "ร่างกายและสุขภาพ", level: "B2", emoji: "🦴" }
];
