const VOCAB_PART_2 = [
  { en: "apple", th: "แอปเปิ้ล", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍎" },
  { en: "banana", th: "กล้วย", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍌" },
  { en: "orange", th: "ส้ม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍊" },
  { en: "mango", th: "มะม่วง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥭" },
  { en: "papaya", th: "มะละกอ", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥭" },
  { en: "pineapple", th: "สับปะรด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍍" },
  { en: "watermelon", th: "แตงโม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍉" },
  { en: "grape", th: "องุ่น", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍇" },
  { en: "strawberry", th: "สตรอว์เบอร์รี", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍓" },
  { en: "blueberry", th: "บลูเบอร์รี", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🫐" },
  { en: "raspberry", th: "ราสป์เบอร์รี", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🫐" },
  { en: "blackberry", th: "แบล็กเบอร์รี", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "cherry", th: "เชอร์รี่", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍒" },
  { en: "peach", th: "ลูกพีช", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍑" },
  { en: "pear", th: "ลูกแพร์", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍐" },
  { en: "plum", th: "พลัม/ลูกพลัม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "kiwi", th: "กีวี", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥝" },
  { en: "lemon", th: "มะนาวเหลือง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍋" },
  { en: "lime", th: "มะนาว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍋" },
  { en: "coconut", th: "มะพร้าว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥥" },
  { en: "durian", th: "ทุเรียน", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥭" },
  { en: "rambutan", th: "เงาะ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "longan", th: "ลำไย", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "lychee", th: "ลิ้นจี่", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "guava", th: "ฝรั่ง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "dragon fruit", th: "แก้วมังกร", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "passion fruit", th: "เสาวรส", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "pomegranate", th: "ทับทิม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "grapefruit", th: "ส้มโอ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "cantaloupe", th: "แคนตาลูป", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "jackfruit", th: "ขนุน", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "tamarind", th: "มะขาม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "avocado", th: "อะโวคาโด", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥑" },
  { en: "mangosteen", th: "มังคุด", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "carrot", th: "แครอท", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥕" },
  { en: "potato", th: "มันฝรั่ง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥔" },
  { en: "tomato", th: "มะเขือเทศ", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍅" },
  { en: "onion", th: "หัวหอม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧅" },
  { en: "garlic", th: "กระเทียม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧄" },
  { en: "ginger", th: "ขิง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "cucumber", th: "แตงกวา", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥒" },
  { en: "cabbage", th: "กะหล่ำปลี", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥬" },
  { en: "lettuce", th: "ผักกาดหอม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥬" },
  { en: "spinach", th: "ผักโขม", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "broccoli", th: "บรอกโคลี", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥦" },
  { en: "cauliflower", th: "กะหล่ำดอก", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "eggplant", th: "มะเขือยาว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍆" },
  { en: "pumpkin", th: "ฟักทอง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🎃" },
  { en: "zucchini", th: "ซูกินี", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "bell pepper", th: "พริกหยวก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "chili pepper", th: "พริก", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🌶️" },
  { en: "mushroom", th: "เห็ด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍄" },
  { en: "corn", th: "ข้าวโพด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🌽" },
  { en: "pea", th: "ถั่วลันเตา", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "green bean", th: "ถั่วฝักยาว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "bean sprout", th: "ถั่วงอก", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "celery", th: "ขึ้นฉ่าย", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "asparagus", th: "หน่อไม้ฝรั่ง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "radish", th: "หัวไชเท้า", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "sweet potato", th: "มันเทศ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍠" },
  { en: "kale", th: "คะน้า", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "shallot", th: "หอมแดง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "spring onion", th: "ต้นหอม", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "bamboo shoot", th: "หน่อไม้", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "bitter gourd", th: "มะระ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "taro", th: "เผือก", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "water spinach", th: "ผักบุ้ง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "chicken", th: "เนื้อไก่", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍗" },
  { en: "beef", th: "เนื้อวัว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥩" },
  { en: "pork", th: "เนื้อหมู", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥓" },
  { en: "lamb", th: "เนื้อแกะ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🐑" },
  { en: "duck", th: "เนื้อเป็ด", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🦆" },
  { en: "fish", th: "ปลา", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🐟" },
  { en: "shrimp", th: "กุ้ง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍤" },
  { en: "crab", th: "ปู", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🦀" },
  { en: "squid", th: "ปลาหมึก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🦑" },
  { en: "octopus", th: "ปลาหมึกยักษ์", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🐙" },
  { en: "egg", th: "ไข่", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥚" },
  { en: "tofu", th: "เต้าหู้", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "sausage", th: "ไส้กรอก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🌭" },
  { en: "bacon", th: "เบคอน", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥓" },
  { en: "ham", th: "แฮม", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "turkey", th: "เนื้อไก่งวง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🦃" },
  { en: "oyster", th: "หอยนางรม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🦪" },
  { en: "scallop", th: "หอยเชลล์", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "meatball", th: "ลูกชิ้น", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "fried rice", th: "ข้าวผัด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍛" },
  { en: "pad thai", th: "ผัดไทย", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍜" },
  { en: "tom yum", th: "ต้มยำ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍲" },
  { en: "green curry", th: "แกงเขียวหวาน", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍛" },
  { en: "red curry", th: "แกงแดง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "massaman curry", th: "แกงมัสมั่น", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "papaya salad", th: "ส้มตำ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥗" },
  { en: "pho", th: "เฝอ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🍜" },
  { en: "sushi", th: "ซูชิ", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍣" },
  { en: "ramen", th: "ราเมง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍜" },
  { en: "dumpling", th: "เกี๊ยว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥟" },
  { en: "spring roll", th: "ปอเปี๊ยะ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "noodle soup", th: "ก๋วยเตี๋ยวน้ำ", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍜" },
  { en: "stir-fried noodles", th: "ผัดซีอิ๊ว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "green salad", th: "สลัดผัก", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥗" },
  { en: "sandwich", th: "แซนด์วิช", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥪" },
  { en: "pizza", th: "พิซซ่า", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍕" },
  { en: "pasta", th: "พาสต้า", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍝" },
  { en: "spaghetti", th: "สปาเก็ตตี้", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍝" },
  { en: "hamburger", th: "แฮมเบอร์เกอร์", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍔" },
  { en: "hot dog", th: "ฮอตดอก", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🌭" },
  { en: "steak", th: "สเต็ก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥩" },
  { en: "soup", th: "ซุป", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍲" },
  { en: "stew", th: "สตูว์", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🍲" },
  { en: "curry", th: "แกง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍛" },
  { en: "fried chicken", th: "ไก่ทอด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍗" },
  { en: "grilled fish", th: "ปลาย่าง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "omelette", th: "ไข่เจียว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍳" },
  { en: "rice porridge", th: "โจ๊ก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍚" },
  { en: "sticky rice", th: "ข้าวเหนียว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍚" },
  { en: "mango sticky rice", th: "ข้าวเหนียวมะม่วง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥭" },
  { en: "satay", th: "สะเต๊ะ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🍢" },
  { en: "dim sum", th: "ติ่มซำ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🥟" },
  { en: "curry puff", th: "กะหรี่พัฟ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "larb", th: "ลาบ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "basil stir-fry", th: "ผัดกะเพรา", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "barbecue", th: "บาร์บีคิว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍖" },
  { en: "hot pot", th: "สุกี้/หม้อไฟ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍲" },
  { en: "fried egg", th: "ไข่ดาว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍳" },
  { en: "boiled egg", th: "ไข่ต้ม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥚" },
  { en: "grilled pork", th: "หมูปิ้ง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "fish cake", th: "ทอดมัน", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "congee", th: "ข้าวต้ม", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍚" },
  { en: "coconut soup", th: "ต้มข่าไก่", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "boil", th: "ต้ม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "fry", th: "ทอด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "grill", th: "ย่าง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "steam", th: "นึ่ง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "bake", th: "อบ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "roast", th: "อบ/ปิ้ง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "stir-fry", th: "ผัด", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "simmer", th: "เคี่ยว", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "blanch", th: "ลวก", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "marinate", th: "หมัก", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "season", th: "ปรุงรส", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "chop", th: "สับ/หั่น", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "slice", th: "หั่นเป็นชิ้น", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "mince", th: "สับให้ละเอียด", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "peel", th: "ปอกเปลือก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "mix", th: "ผสม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "whisk", th: "ตี", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "deep-fry", th: "ทอดน้ำมันท่วม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "stew (cook slowly)", th: "ตุ๋น", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "toast", th: "ปิ้ง/ย่างขนมปัง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍞" },
  { en: "water", th: "น้ำเปล่า", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "💧" },
  { en: "tea", th: "ชา", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍵" },
  { en: "coffee", th: "กาแฟ", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "☕" },
  { en: "milk", th: "นม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥛" },
  { en: "juice", th: "น้ำผลไม้", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧃" },
  { en: "soda", th: "น้ำอัดลม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥤" },
  { en: "beer", th: "เบียร์", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍺" },
  { en: "wine", th: "ไวน์", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍷" },
  { en: "whiskey", th: "วิสกี้", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🥃" },
  { en: "cocktail", th: "ค็อกเทล", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🍹" },
  { en: "smoothie", th: "สมูทตี้", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "milkshake", th: "มิลค์เชค", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "hot chocolate", th: "ช็อกโกแลตร้อน", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "green tea", th: "ชาเขียว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍵" },
  { en: "black tea", th: "ชาดำ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "iced tea", th: "ชาเย็น", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧋" },
  { en: "lemonade", th: "น้ำมะนาว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "coconut water", th: "น้ำมะพร้าว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🥥" },
  { en: "herbal tea", th: "ชาสมุนไพร", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "energy drink", th: "เครื่องดื่มชูกำลัง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "champagne", th: "แชมเปญ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🍾" },
  { en: "latte", th: "ลาเต้", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "cappuccino", th: "คาปูชิโน", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "☕" },
  { en: "espresso", th: "เอสเพรสโซ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "soy milk", th: "นมถั่วเหลือง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "thai iced tea", th: "ชาไทย", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧋" },
  { en: "bubble tea", th: "ชานมไข่มุก", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧋" },
  { en: "sweet", th: "หวาน", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "sour", th: "เปรี้ยว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "salty", th: "เค็ม", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "bitter", th: "ขม", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "spicy", th: "เผ็ด", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🌶️" },
  { en: "savory", th: "รสอูมามิ/รสกลมกล่อม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "bland", th: "จืด", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "tangy", th: "เปรี้ยวอมหวาน", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "creamy", th: "รสครีมมี่", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "crispy", th: "กรอบ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "crunchy", th: "กรุบกรอบ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "juicy", th: "ฉ่ำน้ำ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "umami", th: "รสอูมามิ", category: "อาหารและเครื่องดื่ม", level: "C1", emoji: "" },
  { en: "fragrant", th: "หอม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "delicious", th: "อร่อย", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "😋" },
  { en: "salt", th: "เกลือ", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧂" },
  { en: "sugar", th: "น้ำตาล", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "black pepper", th: "พริกไทย", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "" },
  { en: "soy sauce", th: "ซอสถั่วเหลือง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "fish sauce", th: "น้ำปลา", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "oyster sauce", th: "ซอสหอยนางรม", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "vinegar", th: "น้ำส้มสายชู", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "cooking oil", th: "น้ำมันพืช", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "olive oil", th: "น้ำมันมะกอก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "butter", th: "เนย", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧈" },
  { en: "flour", th: "แป้ง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "rice", th: "ข้าว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍚" },
  { en: "noodle", th: "เส้นก๋วยเตี๋ยว", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍜" },
  { en: "bread", th: "ขนมปัง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍞" },
  { en: "cheese", th: "ชีส", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🧀" },
  { en: "yogurt", th: "โยเกิร์ต", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "honey", th: "น้ำผึ้ง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🍯" },
  { en: "chili sauce", th: "ซอสพริก", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "curry paste", th: "พริกแกง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "coconut milk", th: "กะทิ", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "basil", th: "โหระพา", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "🌿" },
  { en: "coriander", th: "ผักชี", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "mint leaf", th: "ใบสะระแหน่", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "lemongrass", th: "ตะไคร้", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "galangal", th: "ข่า", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "turmeric", th: "ขมิ้น", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "cumin", th: "ยี่หร่า", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "cinnamon", th: "อบเชย", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "star anise", th: "โป๊ยกั๊ก", category: "อาหารและเครื่องดื่ม", level: "C1", emoji: "" },
  { en: "vanilla", th: "วานิลลา", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "cornstarch", th: "แป้งข้าวโพด", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "baking powder", th: "ผงฟู", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "yeast", th: "ยีสต์", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "broth", th: "น้ำซุป", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "sesame oil", th: "น้ำมันงา", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "peanut", th: "ถั่วลิสง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "🥜" },
  { en: "cashew nut", th: "เม็ดมะม่วงหิมพานต์", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "almond", th: "อัลมอนด์", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "palm sugar", th: "น้ำตาลปี๊บ", category: "อาหารและเครื่องดื่ม", level: "B2", emoji: "" },
  { en: "breakfast", th: "อาหารเช้า", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍳" },
  { en: "lunch", th: "อาหารกลางวัน", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍱" },
  { en: "dinner", th: "อาหารเย็น", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍽️" },
  { en: "brunch", th: "มื้อสาย", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "snack", th: "ของว่าง", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍿" },
  { en: "appetizer", th: "อาหารเรียกน้ำย่อย", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "dessert", th: "ของหวาน", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍨" },
  { en: "main course", th: "อาหารจานหลัก", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "side dish", th: "กับข้าว", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "buffet", th: "บุฟเฟ่ต์", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "takeout", th: "อาหารสั่งกลับบ้าน", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "leftovers", th: "อาหารเหลือ", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "recipe", th: "สูตรอาหาร", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "📝" },
  { en: "ingredient", th: "ส่วนผสม", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "portion", th: "ปริมาณอาหารต่อหนึ่งที่", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "menu", th: "เมนูอาหาร", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "📋" },
  { en: "street food", th: "อาหารข้างทาง", category: "อาหารและเครื่องดื่ม", level: "A2", emoji: "" },
  { en: "fast food", th: "อาหารจานด่วน", category: "อาหารและเครื่องดื่ม", level: "A1", emoji: "🍔" },
  { en: "home-cooked food", th: "อาหารทำเอง", category: "อาหารและเครื่องดื่ม", level: "B1", emoji: "" },
  { en: "red", th: "สีแดง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🔴" },
  { en: "orange (color)", th: "สีส้ม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🟠" },
  { en: "yellow", th: "สีเหลือง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🟡" },
  { en: "green", th: "สีเขียว", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🟢" },
  { en: "blue", th: "สีฟ้า/สีน้ำเงิน", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🔵" },
  { en: "purple", th: "สีม่วง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🟣" },
  { en: "pink", th: "สีชมพู", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🩷" },
  { en: "brown", th: "สีน้ำตาล", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🟤" },
  { en: "black", th: "สีดำ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "⚫" },
  { en: "white", th: "สีขาว", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "⚪" },
  { en: "gray", th: "สีเทา", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "gold", th: "สีทอง", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "silver", th: "สีเงิน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "beige", th: "สีเบจ", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "maroon", th: "สีแดงเลือดหมู", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "navy blue", th: "สีกรมท่า", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "🔷" },
  { en: "turquoise", th: "สีเขียวอมฟ้า/สีเทอร์ควอยส์", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "teal", th: "สีเขียวน้ำทะเล", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "violet", th: "สีม่วงอ่อน", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "indigo", th: "สีคราม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "lavender", th: "สีม่วงลาเวนเดอร์", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "magenta", th: "สีบานเย็น", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "crimson", th: "สีแดงเข้ม", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "scarlet", th: "สีแดงสด", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "coral", th: "สีส้มอมชมพู", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "mint green", th: "สีเขียวมิ้นต์", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "olive", th: "สีเขียวมะกอก", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "khaki", th: "สีกากี", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "mustard yellow", th: "สีเหลืองมัสตาร์ด", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "burgundy", th: "สีแดงเลือดนก", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "charcoal", th: "สีเทาดำ", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "ivory", th: "สีงาช้าง", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "cream", th: "สีครีม", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "tan", th: "สีน้ำตาลอ่อน", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "bronze", th: "สีทองแดง", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "lime green", th: "สีเขียวมะนาว", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "sky blue", th: "สีฟ้าคราม", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "royal blue", th: "สีน้ำเงินเข้ม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "hot pink", th: "สีชมพูสด", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "dark green", th: "สีเขียวเข้ม", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "light blue", th: "สีฟ้าอ่อน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "colorful", th: "มีสีสัน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "🌈" },
  { en: "colorless", th: "ไม่มีสี", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "multicolored", th: "หลากสี", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "pastel color", th: "สีพาสเทล", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "bright color", th: "สีสดใส", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "dark shade", th: "สีเข้ม", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "light shade", th: "สีอ่อน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "shade (of color)", th: "เฉดสี", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "pale (color)", th: "สีซีด", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "vivid", th: "สีสดจัด", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "faded", th: "สีซีดจาง", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "transparent", th: "โปร่งใส", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "opaque", th: "ทึบแสง", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "shiny", th: "เป็นเงา", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "matte", th: "ด้าน (ไม่มัน)", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "glossy", th: "มันวาว", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "circle", th: "วงกลม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "⭕" },
  { en: "square", th: "สี่เหลี่ยมจัตุรัส", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🟥" },
  { en: "triangle", th: "สามเหลี่ยม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🔺" },
  { en: "rectangle", th: "สี่เหลี่ยมผืนผ้า", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "▭" },
  { en: "oval", th: "วงรี", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "diamond shape", th: "สี่เหลี่ยมข้าวหลามตัด", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "🔶" },
  { en: "star shape", th: "รูปดาว", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "⭐" },
  { en: "heart shape", th: "รูปหัวใจ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "❤️" },
  { en: "pentagon", th: "รูปห้าเหลี่ยม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "hexagon", th: "รูปหกเหลี่ยม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "⬡" },
  { en: "octagon", th: "รูปแปดเหลี่ยม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "cube", th: "ลูกบาศก์", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "🧊" },
  { en: "sphere", th: "ทรงกลม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "cylinder", th: "ทรงกระบอก", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "cone", th: "ทรงกรวย", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "pyramid shape", th: "ทรงปิรามิด", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "cross shape", th: "รูปกากบาท", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "arrow shape", th: "รูปลูกศร", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "➡️" },
  { en: "spiral", th: "รูปก้นหอย", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "zigzag", th: "รูปฟันปลา", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "curve", th: "เส้นโค้ง", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "straight line", th: "เส้นตรง", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "dot", th: "จุด", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "point", th: "จุด (คณิตศาสตร์)", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "corner", th: "มุม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "edge (shape)", th: "ขอบ", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "side", th: "ด้าน (ของรูปทรง)", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "angle", th: "มุม (องศา)", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "round (shape)", th: "กลม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "flat (shape)", th: "แบน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "symmetrical", th: "สมมาตร", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "three-dimensional", th: "สามมิติ", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "two-dimensional", th: "สองมิติ", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "semicircle", th: "ครึ่งวงกลม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "crescent shape", th: "รูปพระจันทร์เสี้ยว", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "🌙" },
  { en: "one", th: "หนึ่ง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "two", th: "สอง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "three", th: "สาม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "four", th: "สี่", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "five", th: "ห้า", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "six", th: "หก", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "seven", th: "เจ็ด", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "eight", th: "แปด", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "nine", th: "เก้า", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "ten", th: "สิบ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "eleven", th: "สิบเอ็ด", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "twelve", th: "สิบสอง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "twenty", th: "ยี่สิบ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "thirty", th: "สามสิบ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "forty", th: "สี่สิบ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "fifty", th: "ห้าสิบ", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "hundred", th: "ร้อย", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "thousand", th: "พัน", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "million", th: "ล้าน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "billion", th: "พันล้าน", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "zero", th: "ศูนย์", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "first", th: "ที่หนึ่ง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🥇" },
  { en: "second (ordinal)", th: "ที่สอง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🥈" },
  { en: "third", th: "ที่สาม", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "🥉" },
  { en: "fourth", th: "ที่สี่", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "fifth", th: "ที่ห้า", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "tenth", th: "ที่สิบ", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "half", th: "ครึ่ง", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "½" },
  { en: "quarter", th: "หนึ่งในสี่", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "¼" },
  { en: "double", th: "สองเท่า", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "triple", th: "สามเท่า", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "dozen", th: "โหล", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "pair", th: "คู่", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "several", th: "หลาย", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "a few", th: "สองสามอัน", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "many", th: "มาก (นับได้)", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "much", th: "มาก (นับไม่ได้)", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "a lot of", th: "จำนวนมาก", category: "สี รูปทรง และตัวเลข", level: "A1", emoji: "" },
  { en: "plenty of", th: "มากมาย", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "enough", th: "พอ", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "extra", th: "เพิ่มเติม", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "entire", th: "ทั้งหมด", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "whole", th: "ทั้งลูก/ทั้งก้อน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "multiple", th: "หลายอัน", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "countless", th: "นับไม่ถ้วน", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "" },
  { en: "approximately", th: "โดยประมาณ", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "exactly", th: "อย่างแน่นอน", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "average", th: "ค่าเฉลี่ย", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "total", th: "ผลรวม", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "" },
  { en: "sum", th: "ผลบวก", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "percent", th: "เปอร์เซ็นต์", category: "สี รูปทรง และตัวเลข", level: "A2", emoji: "%" },
  { en: "fraction", th: "เศษส่วน", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "decimal", th: "ทศนิยม", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "even number", th: "เลขคู่", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "odd number", th: "เลขคี่", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "negative number", th: "จำนวนลบ", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "positive number", th: "จำนวนบวก", category: "สี รูปทรง และตัวเลข", level: "B1", emoji: "" },
  { en: "Monday", th: "วันจันทร์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "Tuesday", th: "วันอังคาร", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "Wednesday", th: "วันพุธ", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "Thursday", th: "วันพฤหัสบดี", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "Friday", th: "วันศุกร์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "Saturday", th: "วันเสาร์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "Sunday", th: "วันอาทิตย์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "January", th: "มกราคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "February", th: "กุมภาพันธ์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "March", th: "มีนาคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "April", th: "เมษายน", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "May", th: "พฤษภาคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "June", th: "มิถุนายน", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "July", th: "กรกฎาคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "August", th: "สิงหาคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "September", th: "กันยายน", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "October", th: "ตุลาคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "November", th: "พฤศจิกายน", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "December", th: "ธันวาคม", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "spring", th: "ฤดูใบไม้ผลิ", category: "เวลาและปฏิทิน", level: "A2", emoji: "🌸" },
  { en: "summer", th: "ฤดูร้อน", category: "เวลาและปฏิทิน", level: "A1", emoji: "☀️" },
  { en: "autumn", th: "ฤดูใบไม้ร่วง", category: "เวลาและปฏิทิน", level: "A2", emoji: "🍂" },
  { en: "winter", th: "ฤดูหนาว", category: "เวลาและปฏิทิน", level: "A1", emoji: "❄️" },
  { en: "rainy season", th: "ฤดูฝน", category: "เวลาและปฏิทิน", level: "A1", emoji: "🌧️" },
  { en: "cool season", th: "ฤดูหนาว (เมืองไทย)", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "hot season", th: "ฤดูร้อน (เมืองไทย)", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "today", th: "วันนี้", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "tomorrow", th: "พรุ่งนี้", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "yesterday", th: "เมื่อวาน", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "the day after tomorrow", th: "มะรืนนี้", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "the day before yesterday", th: "วานซืน", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "morning", th: "เช้า", category: "เวลาและปฏิทิน", level: "A1", emoji: "🌅" },
  { en: "afternoon", th: "บ่าย", category: "เวลาและปฏิทิน", level: "A1", emoji: "🌤️" },
  { en: "evening", th: "เย็น", category: "เวลาและปฏิทิน", level: "A1", emoji: "🌆" },
  { en: "night", th: "กลางคืน", category: "เวลาและปฏิทิน", level: "A1", emoji: "🌙" },
  { en: "midnight", th: "เที่ยงคืน", category: "เวลาและปฏิทิน", level: "A2", emoji: "🌃" },
  { en: "noon", th: "เที่ยงวัน", category: "เวลาและปฏิทิน", level: "A2", emoji: "🌞" },
  { en: "dawn", th: "รุ่งอรุณ", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "dusk", th: "โพล้เพล้", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "sunrise", th: "พระอาทิตย์ขึ้น", category: "เวลาและปฏิทิน", level: "A2", emoji: "🌅" },
  { en: "sunset", th: "พระอาทิตย์ตก", category: "เวลาและปฏิทิน", level: "A2", emoji: "🌇" },
  { en: "hour", th: "ชั่วโมง", category: "เวลาและปฏิทิน", level: "A1", emoji: "⏰" },
  { en: "minute", th: "นาที", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "second (time)", th: "วินาที", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "week", th: "สัปดาห์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "weekend", th: "วันหยุดสุดสัปดาห์", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "weekday", th: "วันธรรมดา", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "month", th: "เดือน", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "year", th: "ปี", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "decade", th: "ทศวรรษ", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "century", th: "ศตวรรษ", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "moment", th: "ชั่วขณะ", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "instant", th: "ทันที", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "period of time", th: "ช่วงเวลา", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "duration", th: "ระยะเวลา", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "schedule", th: "ตารางเวลา", category: "เวลาและปฏิทิน", level: "A2", emoji: "🗓️" },
  { en: "calendar", th: "ปฏิทิน", category: "เวลาและปฏิทิน", level: "A1", emoji: "📅" },
  { en: "date", th: "วันที่", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "deadline", th: "กำหนดส่ง", category: "เวลาและปฏิทิน", level: "B1", emoji: "⏳" },
  { en: "anniversary", th: "วันครบรอบ", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "birthday", th: "วันเกิด", category: "เวลาและปฏิทิน", level: "A1", emoji: "🎂" },
  { en: "public holiday", th: "วันหยุดราชการ", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "festival", th: "เทศกาล", category: "เวลาและปฏิทิน", level: "A2", emoji: "🎉" },
  { en: "New Year", th: "ปีใหม่", category: "เวลาและปฏิทิน", level: "A1", emoji: "🎆" },
  { en: "Christmas", th: "คริสต์มาส", category: "เวลาและปฏิทิน", level: "A1", emoji: "🎄" },
  { en: "Songkran", th: "สงกรานต์", category: "เวลาและปฏิทิน", level: "A1", emoji: "💦" },
  { en: "leap year", th: "ปีอธิกสุรทิน", category: "เวลาและปฏิทิน", level: "B2", emoji: "" },
  { en: "fiscal year", th: "ปีงบประมาณ", category: "เวลาและปฏิทิน", level: "B2", emoji: "" },
  { en: "semester", th: "ภาคการศึกษา", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "term (school)", th: "เทอม", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "era", th: "ยุคสมัย", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "o'clock", th: "นาฬิกา (บอกเวลา)", category: "เวลาและปฏิทิน", level: "A1", emoji: "🕐" },
  { en: "a.m.", th: "ก่อนเที่ยง", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "p.m.", th: "หลังเที่ยง", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "early", th: "เช้า/เร็ว", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "late", th: "สาย/ช้า", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "on time", th: "ตรงเวลา", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "punctual", th: "ตรงต่อเวลา", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "overdue", th: "เลยกำหนด", category: "เวลาและปฏิทิน", level: "B2", emoji: "" },
  { en: "ahead of schedule", th: "ก่อนกำหนด", category: "เวลาและปฏิทิน", level: "B2", emoji: "" },
  { en: "behind schedule", th: "ล่าช้ากว่ากำหนด", category: "เวลาและปฏิทิน", level: "B2", emoji: "" },
  { en: "in advance", th: "ล่วงหน้า", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "later", th: "ทีหลัง", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "soon", th: "เร็วๆ นี้", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "now", th: "ตอนนี้", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "ago", th: "ที่แล้ว", category: "เวลาและปฏิทิน", level: "A1", emoji: "" },
  { en: "since (time)", th: "ตั้งแต่", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "until", th: "จนกระทั่ง", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "during", th: "ระหว่าง", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "meanwhile", th: "ในระหว่างนั้น", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "nowadays", th: "สมัยนี้", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "recently", th: "เมื่อเร็วๆ นี้", category: "เวลาและปฏิทิน", level: "A2", emoji: "" },
  { en: "timeline", th: "ไทม์ไลน์", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "timer", th: "ตัวจับเวลา", category: "เวลาและปฏิทิน", level: "A2", emoji: "⏲️" },
  { en: "alarm clock", th: "นาฬิกาปลุก", category: "เวลาและปฏิทิน", level: "A1", emoji: "⏰" },
  { en: "stopwatch", th: "นาฬิกาจับเวลา", category: "เวลาและปฏิทิน", level: "B1", emoji: "⏱️" },
  { en: "countdown", th: "การนับถอยหลัง", category: "เวลาและปฏิทิน", level: "B1", emoji: "" },
  { en: "time zone", th: "เขตเวลา", category: "เวลาและปฏิทิน", level: "B1", emoji: "🌐" },
  { en: "trapezoid", th: "สี่เหลี่ยมคางหมู", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "🔷" },
  { en: "rhombus", th: "สี่เหลี่ยมขนมเปียกปูน", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "🔷" },
  { en: "parallelogram", th: "สี่เหลี่ยมด้านขนาน", category: "สี รูปทรง และตัวเลข", level: "B2", emoji: "🔷" }
];
