const VOCAB_PART_5 = [
  { en: "car", th: "รถยนต์", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚗" },
  { en: "bus", th: "รถบัส", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚌" },
  { en: "taxi", th: "รถแท็กซี่", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚕" },
  { en: "truck", th: "รถบรรทุก", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚚" },
  { en: "motorcycle", th: "รถจักรยานยนต์", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🏍️" },
  { en: "bicycle", th: "จักรยาน", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚲" },
  { en: "scooter", th: "สกู๊ตเตอร์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛵" },
  { en: "train", th: "รถไฟ", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚆" },
  { en: "subway", th: "รถไฟใต้ดิน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚇" },
  { en: "tram", th: "รถราง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚊" },
  { en: "ship", th: "เรือเดินสมุทร", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚢" },
  { en: "boat", th: "เรือ", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🛶" },
  { en: "ferry", th: "เรือข้ามฟาก", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "⛴️" },
  { en: "yacht", th: "เรือยอทช์", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛥️" },
  { en: "sailboat", th: "เรือใบ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "⛵" },
  { en: "canoe", th: "เรือแคนู", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛶" },
  { en: "kayak", th: "เรือคายัค", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛶" },
  { en: "airplane", th: "เครื่องบิน", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "✈️" },
  { en: "jet", th: "เครื่องบินไอพ่น", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "✈️" },
  { en: "helicopter", th: "เฮลิคอปเตอร์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚁" },
  { en: "hot air balloon", th: "บอลลูนอากาศร้อน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🎈" },
  { en: "cable car", th: "กระเช้าไฟฟ้า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚡" },
  { en: "monorail", th: "รถไฟรางเดี่ยว", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🚝" },
  { en: "tuk-tuk", th: "ตุ๊กตุ๊ก", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛺" },
  { en: "rickshaw", th: "รถลาก", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🛺" },
  { en: "van", th: "รถตู้", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚐" },
  { en: "minivan", th: "รถมินิแวน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚐" },
  { en: "pickup truck", th: "รถกระบะ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛻" },
  { en: "trailer", th: "รถพ่วง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚛" },
  { en: "caravan", th: "รถบ้าน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚐" },
  { en: "sports car", th: "รถสปอร์ต", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🏎️" },
  { en: "convertible", th: "รถเปิดประทุน", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🚗" },
  { en: "limousine", th: "รถลีมูซีน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚙" },
  { en: "fire truck", th: "รถดับเพลิง", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚒" },
  { en: "police car", th: "รถตำรวจ", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚓" },
  { en: "cargo ship", th: "เรือขนส่งสินค้า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚢" },
  { en: "container ship", th: "เรือคอนเทนเนอร์", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🚢" },
  { en: "submarine", th: "เรือดำน้ำ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "" },
  { en: "hovercraft", th: "โฮเวอร์คราฟต์", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "" },
  { en: "glider", th: "เครื่องร่อน", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "" },
  { en: "seaplane", th: "เครื่องบินทะเล", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "" },
  { en: "spaceship", th: "ยานอวกาศ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚀" },
  { en: "rocket", th: "จรวด", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚀" },
  { en: "unicycle", th: "จักรยานล้อเดียว", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "" },
  { en: "tricycle", th: "รถสามล้อ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "" },
  { en: "golf cart", th: "รถกอล์ฟ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "" },
  { en: "forklift", th: "รถยก", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "" },
  { en: "bulldozer", th: "รถปราบดิน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "" },
  { en: "tractor", th: "รถแทรกเตอร์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚜" },
  { en: "double-decker bus", th: "รถบัสสองชั้น", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚌" },
  { en: "sleeper bus", th: "รถบัสนอน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚌" },
  { en: "electric car", th: "รถยนต์ไฟฟ้า", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚗" },
  { en: "hybrid car", th: "รถยนต์ไฮบริด", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚗" },
  { en: "sidecar", th: "รถพ่วงข้าง", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "" },
  { en: "hearse", th: "รถศพ", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "" },
  { en: "snowmobile", th: "รถแล่นบนหิมะ", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "" },
  { en: "jet ski", th: "เจ็ตสกี", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛥️" },
  { en: "speedboat", th: "เรือเร็ว", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚤" },
  { en: "rowboat", th: "เรือพาย", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚣" },
  { en: "passport", th: "หนังสือเดินทาง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛂" },
  { en: "visa", th: "วีซ่า", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛂" },
  { en: "boarding pass", th: "บัตรขึ้นเครื่อง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎫" },
  { en: "ticket", th: "ตั๋ว", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🎫" },
  { en: "itinerary", th: "กำหนดการเดินทาง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🗓️" },
  { en: "driver's license", th: "ใบขับขี่", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🪪" },
  { en: "ID card", th: "บัตรประจำตัว", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🪪" },
  { en: "luggage tag", th: "ป้ายติดกระเป๋า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏷️" },
  { en: "customs declaration form", th: "แบบฟอร์มสำแดงศุลกากร", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "📄" },
  { en: "travel insurance", th: "ประกันการเดินทาง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "📄" },
  { en: "e-ticket", th: "ตั๋วอิเล็กทรอนิกส์", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🎫" },
  { en: "immigration form", th: "แบบฟอร์มตรวจคนเข้าเมือง", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "📄" },
  { en: "entry stamp", th: "ตราประทับเข้าเมือง", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "📄" },
  { en: "transit visa", th: "วีซ่าผ่านแดน", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "🛂" },
  { en: "work permit", th: "ใบอนุญาตทำงาน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "📄" },
  { en: "residence permit", th: "ใบอนุญาตพำนัก", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "📄" },
  { en: "consulate", th: "สถานกงสุล", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏛️" },
  { en: "vaccination certificate", th: "ใบรับรองการฉีดวัคซีน", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "💉" },
  { en: "health declaration", th: "แบบฟอร์มสุขภาพ", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "📄" },
  { en: "landing card", th: "บัตรขาเข้า", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "📄" },
  { en: "boarding time", th: "เวลาขึ้นเครื่อง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🕐" },
  { en: "seat number", th: "หมายเลขที่นั่ง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎫" },
  { en: "baggage allowance", th: "น้ำหนักกระเป๋าที่อนุญาต", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🧳" },
  { en: "excess baggage", th: "กระเป๋าน้ำหนักเกิน", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🧳" },
  { en: "travel voucher", th: "บัตรกำนัลการเดินทาง", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🎟️" },
  { en: "round-trip ticket", th: "ตั๋วไป-กลับ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎫" },
  { en: "one-way ticket", th: "ตั๋วเที่ยวเดียว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎫" },
  { en: "student visa", th: "วีซ่านักเรียน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛂" },
  { en: "tourist visa", th: "วีซ่านักท่องเที่ยว", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛂" },
  { en: "terminal", th: "อาคารผู้โดยสาร", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛫" },
  { en: "check-in counter", th: "เคาน์เตอร์เช็คอิน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛄" },
  { en: "baggage claim", th: "จุดรับกระเป๋า", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🧳" },
  { en: "security checkpoint", th: "จุดตรวจความปลอดภัย", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛃" },
  { en: "customs", th: "ศุลกากร", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛃" },
  { en: "immigration", th: "ตรวจคนเข้าเมือง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛂" },
  { en: "duty-free shop", th: "ร้านค้าปลอดภาษี", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛍️" },
  { en: "departure lounge", th: "ห้องรอผู้โดยสารขาออก", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛋️" },
  { en: "arrival hall", th: "ห้องโถงผู้โดยสารขาเข้า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏢" },
  { en: "runway", th: "ทางวิ่งเครื่องบิน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛬" },
  { en: "control tower", th: "หอควบคุมการบิน", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🗼" },
  { en: "boarding", th: "การขึ้นเครื่อง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛫" },
  { en: "layover", th: "การแวะพักระหว่างทาง", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "⏳" },
  { en: "connecting flight", th: "เที่ยวบินต่อเครื่อง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "✈️" },
  { en: "direct flight", th: "เที่ยวบินตรง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "✈️" },
  { en: "delay", th: "ความล่าช้า", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "⏱️" },
  { en: "flight cancellation", th: "การยกเลิกเที่ยวบิน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "❌" },
  { en: "flight attendant", th: "พนักงานต้อนรับบนเครื่องบิน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "👩‍✈️" },
  { en: "pilot", th: "นักบิน", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "👨‍✈️" },
  { en: "co-pilot", th: "นักบินผู้ช่วย", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "👨‍✈️" },
  { en: "air traffic controller", th: "เจ้าหน้าที่ควบคุมการจราจรทางอากาศ", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "🗼" },
  { en: "ground crew", th: "เจ้าหน้าที่ภาคพื้นดิน", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "👷" },
  { en: "luggage cart", th: "รถเข็นกระเป๋า", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛒" },
  { en: "conveyor belt", th: "สายพานลำเลียง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "⚙️" },
  { en: "overhead compartment", th: "ช่องเก็บสัมภาระเหนือศีรษะ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🧳" },
  { en: "aisle seat", th: "ที่นั่งริมทางเดิน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "💺" },
  { en: "window seat", th: "ที่นั่งริมหน้าต่าง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "💺" },
  { en: "emergency exit", th: "ทางออกฉุกเฉิน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚪" },
  { en: "life jacket", th: "เสื้อชูชีพ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🦺" },
  { en: "seatbelt", th: "เข็มขัดนิรภัย", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🔒" },
  { en: "tray table", th: "โต๊ะพับ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🍽️" },
  { en: "platform", th: "ชานชาลา", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚉" },
  { en: "ticket booth", th: "ห้องจำหน่ายตั๋ว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎫" },
  { en: "ticket machine", th: "เครื่องจำหน่ายตั๋ว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎫" },
  { en: "timetable", th: "ตารางเวลาเดินรถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🕐" },
  { en: "express train", th: "รถไฟด่วน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚄" },
  { en: "local train", th: "รถไฟธรรมดา", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚆" },
  { en: "sleeper car", th: "ตู้นอน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛌" },
  { en: "dining car", th: "ตู้เสบียง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🍽️" },
  { en: "bus stop", th: "ป้ายรถเมล์", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚏" },
  { en: "bus terminal", th: "สถานีขนส่ง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚌" },
  { en: "taxi stand", th: "จุดจอดแท็กซี่", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚕" },
  { en: "dock", th: "ท่าเทียบเรือ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "⚓" },
  { en: "pier", th: "สะพานท่าเรือ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🌉" },
  { en: "traffic light", th: "สัญญาณไฟจราจร", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚦" },
  { en: "traffic jam", th: "รถติด", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚗" },
  { en: "motorway", th: "ทางด่วน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛣️" },
  { en: "crosswalk", th: "ทางม้าลาย", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🚸" },
  { en: "pedestrian", th: "คนเดินเท้า", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚶" },
  { en: "speed limit", th: "จำกัดความเร็ว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚧" },
  { en: "speed bump", th: "เนินชะลอความเร็ว", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚧" },
  { en: "road sign", th: "ป้ายจราจร", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚧" },
  { en: "stop sign", th: "ป้ายหยุด", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🛑" },
  { en: "one-way street", th: "ถนนเดินรถทางเดียว", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "↪️" },
  { en: "lane", th: "ช่องทางเดินรถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛣️" },
  { en: "overpass", th: "สะพานลอยข้ามถนน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🌉" },
  { en: "underpass", th: "ทางลอด", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚇" },
  { en: "parking meter", th: "เครื่องเก็บค่าจอดรถ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🅿️" },
  { en: "parking garage", th: "อาคารจอดรถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🅿️" },
  { en: "license plate", th: "ป้ายทะเบียนรถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚗" },
  { en: "rearview mirror", th: "กระจกมองหลัง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚗" },
  { en: "steering wheel", th: "พวงมาลัย", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚗" },
  { en: "brake", th: "เบรก", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚗" },
  { en: "accelerator", th: "คันเร่ง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚗" },
  { en: "gearbox", th: "เกียร์", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚗" },
  { en: "clutch", th: "คลัตช์", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🚗" },
  { en: "windshield", th: "กระจกหน้ารถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚗" },
  { en: "windshield wiper", th: "ที่ปัดน้ำฝน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚗" },
  { en: "headlight", th: "ไฟหน้ารถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "💡" },
  { en: "taillight", th: "ไฟท้ายรถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "💡" },
  { en: "airbag", th: "ถุงลมนิรภัย", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🎈" },
  { en: "tire", th: "ยางรถ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛞" },
  { en: "spare tire", th: "ยางอะไหล่", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛞" },
  { en: "flat tire", th: "ยางแบน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛞" },
  { en: "traffic police", th: "ตำรวจจราจร", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "👮" },
  { en: "U-turn", th: "การกลับรถ", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🔄" },
  { en: "detour", th: "ทางเลี่ยง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚧" },
  { en: "road construction", th: "งานก่อสร้างถนน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚧" },
  { en: "pothole", th: "หลุมบนถนน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🕳️" },
  { en: "curb", th: "ขอบทางเท้า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛣️" },
  { en: "median strip", th: "เกาะกลางถนน", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "🛣️" },
  { en: "toll booth", th: "ด่านเก็บเงิน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚧" },
  { en: "toll road", th: "ถนนที่ต้องเสียค่าผ่านทาง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛣️" },
  { en: "traffic sign", th: "ป้ายสัญญาณจราจร", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚧" },
  { en: "speedometer", th: "มาตรวัดความเร็ว", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚗" },
  { en: "guesthouse", th: "เกสต์เฮาส์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🏠" },
  { en: "resort", th: "รีสอร์ท", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🏝️" },
  { en: "inn", th: "โรงแรมขนาดเล็ก", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏨" },
  { en: "bed and breakfast", th: "ที่พักพร้อมอาหารเช้า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛏️" },
  { en: "reception desk", th: "แผนกต้อนรับ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛎️" },
  { en: "room key", th: "กุญแจห้อง", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🔑" },
  { en: "room service", th: "บริการรูมเซอร์วิส", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛎️" },
  { en: "checkout", th: "การเช็คเอาท์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🧳" },
  { en: "check-in", th: "การเช็คอิน", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🧳" },
  { en: "single room", th: "ห้องเดี่ยว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛏️" },
  { en: "double room", th: "ห้องคู่", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛏️" },
  { en: "suite", th: "ห้องสวีท", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛏️" },
  { en: "lobby", th: "ล็อบบี้", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🏨" },
  { en: "concierge", th: "พนักงานอำนวยความสะดวก", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🛎️" },
  { en: "bellboy", th: "พนักงานยกกระเป๋า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛎️" },
  { en: "amenities", th: "สิ่งอำนวยความสะดวก", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏨" },
  { en: "reservation", th: "การจอง", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "📅" },
  { en: "booking confirmation", th: "ใบยืนยันการจอง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "📄" },
  { en: "minibar", th: "มินิบาร์", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🍾" },
  { en: "housekeeping", th: "แม่บ้านโรงแรม", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🧹" },
  { en: "wake-up call", th: "บริการปลุก", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "☎️" },
  { en: "vacancy", th: "ห้องว่าง", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏨" },
  { en: "no vacancy", th: "ห้องเต็ม", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏨" },
  { en: "dormitory", th: "หอพักรวม", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🛏️" },
  { en: "campsite", th: "ลานกางเต็นท์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "⛺" },
  { en: "cabin", th: "กระท่อม", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛖" },
  { en: "villa", th: "วิลล่า", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🏡" },
  { en: "tourist", th: "นักท่องเที่ยว", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🧳" },
  { en: "tour guide", th: "ไกด์นำเที่ยว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🗺️" },
  { en: "tour group", th: "กลุ่มทัวร์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "👥" },
  { en: "sightseeing", th: "การเที่ยวชมสถานที่", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "📸" },
  { en: "souvenir", th: "ของที่ระลึก", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🎁" },
  { en: "backpacker", th: "นักท่องเที่ยวแบกเป้", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🎒" },
  { en: "traveler", th: "นักเดินทาง", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🧳" },
  { en: "vacation", th: "วันหยุดพักผ่อน", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🏖️" },
  { en: "holiday", th: "วันหยุด", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🏖️" },
  { en: "cruise", th: "การล่องเรือ", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🛳️" },
  { en: "expedition", th: "การสำรวจ", category: "การเดินทางและการขนส่ง", level: "B2", emoji: "🧭" },
  { en: "adventure travel", th: "การท่องเที่ยวผจญภัย", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🧭" },
  { en: "camping", th: "การตั้งแคมป์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "⛺" },
  { en: "road trip", th: "การเดินทางโดยรถยนต์", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚗" },
  { en: "honeymoon", th: "ฮันนีมูน", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "💑" },
  { en: "pilgrimage", th: "การแสวงบุญ", category: "การเดินทางและการขนส่ง", level: "C1", emoji: "🙏" },
  { en: "excursion", th: "การไปเที่ยวระยะสั้น", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "🚌" },
  { en: "day trip", th: "ทริปวันเดียว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🚌" },
  { en: "guided tour", th: "ทัวร์นำเที่ยว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🗺️" },
  { en: "travel agency", th: "บริษัทนำเที่ยว", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🏢" },
  { en: "brochure", th: "โบรชัวร์", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "📖" },
  { en: "luggage", th: "สัมภาระ", category: "การเดินทางและการขนส่ง", level: "A1", emoji: "🧳" },
  { en: "sunscreen", th: "ครีมกันแดด", category: "การเดินทางและการขนส่ง", level: "A2", emoji: "🧴" },
  { en: "travel guidebook", th: "หนังสือแนะนำการท่องเที่ยว", category: "การเดินทางและการขนส่ง", level: "B1", emoji: "📖" },
  { en: "football", th: "ฟุตบอล", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "⚽" },
  { en: "basketball", th: "บาสเกตบอล", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏀" },
  { en: "volleyball", th: "วอลเลย์บอล", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏐" },
  { en: "baseball", th: "เบสบอล", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "⚾" },
  { en: "softball", th: "ซอฟต์บอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥎" },
  { en: "tennis", th: "เทนนิส", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🎾" },
  { en: "table tennis", th: "ปิงปอง", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏓" },
  { en: "badminton", th: "แบดมินตัน", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏸" },
  { en: "golf", th: "กอล์ฟ", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "⛳" },
  { en: "swimming", th: "ว่ายน้ำ", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏊" },
  { en: "diving", th: "การดำน้ำ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🤿" },
  { en: "cycling", th: "การปั่นจักรยาน", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🚴" },
  { en: "running", th: "การวิ่ง", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏃" },
  { en: "athletics", th: "กรีฑา", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏃" },
  { en: "gymnastics", th: "ยิมนาสติก", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🤸" },
  { en: "boxing", th: "มวยสากล", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥊" },
  { en: "wrestling", th: "มวยปล้ำ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤼" },
  { en: "judo", th: "ยูโด", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥋" },
  { en: "karate", th: "คาราเต้", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥋" },
  { en: "taekwondo", th: "เทควันโด", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥋" },
  { en: "kung fu", th: "กังฟู", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥋" },
  { en: "muay thai", th: "มวยไทย", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥊" },
  { en: "fencing", th: "ฟันดาบ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤺" },
  { en: "archery", th: "ยิงธนู", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏹" },
  { en: "shooting", th: "กีฬายิงปืน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎯" },
  { en: "weightlifting", th: "ยกน้ำหนัก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏋️" },
  { en: "powerlifting", th: "เพาเวอร์ลิฟติ้ง", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🏋️" },
  { en: "bodybuilding", th: "เพาะกาย", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "💪" },
  { en: "rowing", th: "พายเรือ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🚣" },
  { en: "sailing", th: "แล่นเรือใบ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⛵" },
  { en: "surfing", th: "โต้คลื่น", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏄" },
  { en: "windsurfing", th: "วินด์เซิร์ฟ", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🏄" },
  { en: "skiing", th: "เล่นสกี", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "⛷️" },
  { en: "snowboarding", th: "สโนว์บอร์ด", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏂" },
  { en: "ice skating", th: "เล่นสเก็ตน้ำแข็ง", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "⛸️" },
  { en: "figure skating", th: "สเก็ตลีลา", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⛸️" },
  { en: "ice hockey", th: "ฮอกกี้น้ำแข็ง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏒" },
  { en: "field hockey", th: "ฮอกกี้สนาม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏑" },
  { en: "rugby", th: "รักบี้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏉" },
  { en: "handball", th: "แฮนด์บอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤾" },
  { en: "water polo", th: "โปโลน้ำ", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🤽" },
  { en: "polo", th: "โปโล", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🏇" },
  { en: "horse racing", th: "แข่งม้า", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏇" },
  { en: "equestrian", th: "ขี่ม้า", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏇" },
  { en: "motor racing", th: "แข่งรถ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏁" },
  { en: "formula one", th: "ฟอร์มูล่าวัน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏎️" },
  { en: "rally racing", th: "แข่งรถแรลลี่", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🏁" },
  { en: "skateboarding", th: "เล่นสเก็ตบอร์ด", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🛹" },
  { en: "rock climbing", th: "ปีนหน้าผา", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧗" },
  { en: "mountaineering", th: "ปีนเขา", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏔️" },
  { en: "hiking", th: "เดินป่า", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥾" },
  { en: "trekking", th: "เดินป่าระยะไกล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥾" },
  { en: "bowling", th: "โบว์ลิ่ง", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎳" },
  { en: "billiards", th: "บิลเลียด", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎱" },
  { en: "snooker", th: "สนุกเกอร์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎱" },
  { en: "darts", th: "ปาลูกดอก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎯" },
  { en: "marathon", th: "มาราธอน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏃" },
  { en: "triathlon", th: "ไตรกีฬา", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🏊" },
  { en: "pentathlon", th: "เพนตากีฬา", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🏅" },
  { en: "football boots", th: "รองเท้าฟุตบอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "👟" },
  { en: "shin guards", th: "สนับแข้ง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🦵" },
  { en: "basketball hoop", th: "ห่วงบาสเกตบอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏀" },
  { en: "tennis racket", th: "ไม้เทนนิส", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎾" },
  { en: "badminton racket", th: "ไม้แบดมินตัน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏸" },
  { en: "shuttlecock", th: "ลูกขนไก่", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏸" },
  { en: "golf club", th: "ไม้กอล์ฟ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⛳" },
  { en: "golf ball", th: "ลูกกอล์ฟ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "⛳" },
  { en: "baseball bat", th: "ไม้เบสบอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚾" },
  { en: "baseball glove", th: "ถุงมือเบสบอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚾" },
  { en: "boxing gloves", th: "นวมชกมวย", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥊" },
  { en: "punching bag", th: "กระสอบทราย", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥊" },
  { en: "dumbbell", th: "ดัมเบล", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏋️" },
  { en: "barbell", th: "บาร์เบล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏋️" },
  { en: "treadmill", th: "ลู่วิ่ง", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏃" },
  { en: "yoga mat", th: "เสื่อโยคะ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧘" },
  { en: "knee pads", th: "สนับเข่า", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🦵" },
  { en: "elbow pads", th: "สนับข้อศอก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "💪" },
  { en: "wetsuit", th: "ชุดดำน้ำ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤿" },
  { en: "snorkel", th: "ท่อหายใจดำน้ำ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤿" },
  { en: "flippers", th: "ตีนกบ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤿" },
  { en: "surfboard", th: "กระดานโต้คลื่น", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏄" },
  { en: "skateboard", th: "สเก็ตบอร์ด", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🛹" },
  { en: "ice skates", th: "รองเท้าสเก็ตน้ำแข็ง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⛸️" },
  { en: "ski poles", th: "ไม้ค้ำสกี", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "⛷️" },
  { en: "skis", th: "สกี", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎿" },
  { en: "snowboard", th: "สโนว์บอร์ด", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏂" },
  { en: "climbing rope", th: "เชือกปีนเขา", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧗" },
  { en: "climbing harness", th: "สายรัดปีนเขา", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🧗" },
  { en: "fishing rod", th: "คันเบ็ด", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎣" },
  { en: "fishing net", th: "แหจับปลา", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎣" },
  { en: "bow and arrow", th: "ธนูและลูกธนู", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏹" },
  { en: "dartboard", th: "เป้าปาลูกดอก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎯" },
  { en: "chessboard", th: "กระดานหมากรุก", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "♟️" },
  { en: "playing cards", th: "ไพ่", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🃏" },
  { en: "dice", th: "ลูกเต๋า", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🎲" },
  { en: "gym ball", th: "ลูกบอลออกกำลังกาย", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚽" },
  { en: "jump rope", th: "เชือกกระโดด", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🪢" },
  { en: "resistance band", th: "ยางยืดออกกำลังกาย", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏋️" },
  { en: "racket bag", th: "กระเป๋าไม้แร็กเก็ต", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎒" },
  { en: "goalpost", th: "เสาประตู", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥅" },
  { en: "soccer ball", th: "ลูกฟุตบอล", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "⚽" },
  { en: "basketball jersey", th: "เสื้อบาสเกตบอล", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏀" },
  { en: "swimming goggles", th: "แว่นตาว่ายน้ำ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥽" },
  { en: "swimming cap", th: "หมวกว่ายน้ำ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏊" },
  { en: "life buoy", th: "ห่วงชูชีพ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🛟" },
  { en: "kite", th: "ว่าว", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🪁" },
  { en: "frisbee", th: "จานร่อน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🥏" },
  { en: "hula hoop", th: "ห่วงฮูลาฮูป", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎡" },
  { en: "pogo stick", th: "ไม้กระโดด", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🪀" },
  { en: "yo-yo", th: "โยโย่", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🪀" },
  { en: "slingshot", th: "หนังสติ๊ก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎯" },
  { en: "badminton net", th: "ตาข่ายแบดมินตัน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏸" },
  { en: "volleyball net", th: "ตาข่ายวอลเลย์บอล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏐" },
  { en: "cricket bat", th: "ไม้คริกเก็ต", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🏏" },
  { en: "hockey stick", th: "ไม้ฮอกกี้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏒" },
  { en: "rugby ball", th: "ลูกรักบี้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏉" },
  { en: "wristband", th: "สายรัดข้อมือ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "⌚" },
  { en: "sports bag", th: "กระเป๋ากีฬา", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎒" },
  { en: "goalkeeper", th: "ผู้รักษาประตู", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧤" },
  { en: "striker", th: "กองหน้า", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚽" },
  { en: "midfielder", th: "กองกลาง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚽" },
  { en: "defender", th: "กองหลัง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚽" },
  { en: "referee", th: "กรรมการ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧑‍⚖️" },
  { en: "umpire", th: "กรรมการตัดสิน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧑‍⚖️" },
  { en: "coach", th: "โค้ช", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🧑‍🏫" },
  { en: "captain", th: "กัปตันทีม", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎽" },
  { en: "team", th: "ทีม", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "👥" },
  { en: "player", th: "นักกีฬา", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏃" },
  { en: "athlete", th: "นักกีฬาอาชีพ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏅" },
  { en: "spectator", th: "ผู้ชม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "👀" },
  { en: "cheerleader", th: "เชียร์ลีดเดอร์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "📣" },
  { en: "caddie", th: "เด็กแบกถุงกอล์ฟ", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "⛳" },
  { en: "lifeguard", th: "เจ้าหน้าที่ช่วยชีวิต", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏊" },
  { en: "jockey", th: "จ๊อกกี้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏇" },
  { en: "scorer", th: "ผู้บันทึกคะแนน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "📋" },
  { en: "substitute", th: "ผู้เล่นสำรอง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🔄" },
  { en: "champion", th: "แชมป์", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏆" },
  { en: "runner-up", th: "รองแชมป์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🥈" },
  { en: "opponent", th: "คู่แข่ง", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🤼" },
  { en: "teammate", th: "เพื่อนร่วมทีม", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "👥" },
  { en: "trainer", th: "ผู้ฝึกสอน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏋️" },
  { en: "physiotherapist", th: "นักกายภาพบำบัด", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🏥" },
  { en: "sports commentator", th: "ผู้บรรยายกีฬา", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🎙️" },
  { en: "linesman", th: "ผู้ตัดสินเส้น", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🚩" },
  { en: "pitcher", th: "ผู้ขว้างลูก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚾" },
  { en: "batter", th: "ผู้ตี", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "⚾" },
  { en: "quarterback", th: "ควอเตอร์แบ็ก", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🏈" },
  { en: "forward", th: "ตัวรุก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏀" },
  { en: "chess", th: "หมากรุกสากล", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "♟️" },
  { en: "checkers", th: "หมากฮอส", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "⚫" },
  { en: "poker", th: "โป๊กเกอร์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🃏" },
  { en: "board game", th: "เกมกระดาน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎲" },
  { en: "jigsaw puzzle", th: "จิ๊กซอว์", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧩" },
  { en: "video game", th: "วิดีโอเกม", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🎮" },
  { en: "card game", th: "เกมไพ่", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🃏" },
  { en: "hide and seek", th: "ซ่อนหา", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🙈" },
  { en: "tag", th: "เกมไล่จับ", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🏃" },
  { en: "marbles", th: "ลูกแก้ว", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🔵" },
  { en: "kite flying", th: "เล่นว่าว", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🪁" },
  { en: "tug of war", th: "ชักเย่อ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🪢" },
  { en: "charades", th: "เกมทายท่าทาง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎭" },
  { en: "scrabble", th: "เกมสแครบเบิล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🔤" },
  { en: "crossword puzzle", th: "ปริศนาอักษรไขว้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧩" },
  { en: "sudoku", th: "ซูโดกุ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🔢" },
  { en: "domino", th: "โดมิโน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🁣" },
  { en: "backgammon", th: "แบ็คแกมมอน", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🎲" },
  { en: "mahjong", th: "ไพ่นกกระจอก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🀄" },
  { en: "bingo", th: "บิงโก", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🔢" },
  { en: "monopoly", th: "เกมเศรษฐี", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎲" },
  { en: "solitaire", th: "เกมไพ่คนเดียว", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🃏" },
  { en: "trivia quiz", th: "เกมตอบคำถาม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "❓" },
  { en: "role-playing game", th: "เกมสวมบทบาท", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎭" },
  { en: "arcade game", th: "เกมตู้", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🕹️" },
  { en: "puzzle", th: "ปริศนา", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧩" },
  { en: "rubik's cube", th: "ลูกบาศก์รูบิก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧩" },
  { en: "dodgeball", th: "ดอดจ์บอล", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏐" },
  { en: "leapfrog", th: "กระโดดกบ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🐸" },
  { en: "hopscotch", th: "เดินกระต่ายขาเดียว", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🦵" },
  { en: "painting", th: "การวาดภาพสี", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🎨" },
  { en: "drawing", th: "การวาดภาพ", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "✏️" },
  { en: "sketching", th: "การร่างภาพ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "✏️" },
  { en: "sculpture", th: "ประติมากรรม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🗿" },
  { en: "pottery", th: "การปั้นเครื่องปั้นดินเผา", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🏺" },
  { en: "knitting", th: "การถักไหมพรม", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧶" },
  { en: "sewing", th: "การเย็บผ้า", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧵" },
  { en: "embroidery", th: "การปักผ้า", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧵" },
  { en: "origami", th: "การพับกระดาษ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "📄" },
  { en: "calligraphy", th: "การเขียนพู่กัน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🖌️" },
  { en: "photography", th: "การถ่ายภาพ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "📷" },
  { en: "gardening", th: "การทำสวน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🌱" },
  { en: "baking", th: "การอบขนม", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧁" },
  { en: "stamp collecting", th: "การสะสมแสตมป์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "📮" },
  { en: "coin collecting", th: "การสะสมเหรียญ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🪙" },
  { en: "model building", th: "การประกอบโมเดล", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🛠️" },
  { en: "woodworking", th: "งานไม้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🪚" },
  { en: "candle making", th: "การทำเทียน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🕯️" },
  { en: "scrapbooking", th: "การทำสมุดภาพ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "📔" },
  { en: "beadwork", th: "งานลูกปัด", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "📿" },
  { en: "quilting", th: "การเย็บผ้าห่มแบบต่อชิ้น", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🧵" },
  { en: "crocheting", th: "การถักโครเชต์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧶" },
  { en: "jewelry making", th: "การทำเครื่องประดับ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "💍" },
  { en: "knitting needles", th: "ไม้ถักไหมพรม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🧶" },
  { en: "sewing machine", th: "จักรเย็บผ้า", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧵" },
  { en: "easel", th: "ขาตั้งวาดภาพ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🎨" },
  { en: "canvas", th: "ผ้าใบวาดภาพ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🖼️" },
  { en: "potter's wheel", th: "แป้นหมุนปั้นดิน", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🏺" },
  { en: "camera", th: "กล้องถ่ายรูป", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "📷" },
  { en: "tripod", th: "ขาตั้งกล้อง", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "📷" },
  { en: "gardening tools", th: "เครื่องมือทำสวน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🧰" },
  { en: "trowel", th: "เกรียงพรวนดิน", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🌱" },
  { en: "watering can", th: "บัวรดน้ำ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🪴" },
  { en: "flower pot", th: "กระถางดอกไม้", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🪴" },
  { en: "birdwatching", th: "การดูนก", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🐦" },
  { en: "stargazing", th: "การดูดาว", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🔭" },
  { en: "binoculars", th: "กล้องส่องทางไกล", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🔭" },
  { en: "fishing", th: "การตกปลา", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🎣" },
  { en: "hunting", th: "การล่าสัตว์", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏹" },
  { en: "camping stove", th: "เตาแคมปิ้ง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🔥" },
  { en: "tent", th: "เต็นท์", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "⛺" },
  { en: "sleeping bag", th: "ถุงนอน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🛏️" },
  { en: "scrapbook", th: "สมุดรวมภาพ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "📔" },
  { en: "karaoke", th: "คาราโอเกะ", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎤" },
  { en: "dancing", th: "การเต้นรำ", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "💃" },
  { en: "singing", th: "การร้องเพลง", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🎤" },
  { en: "playing guitar", th: "การเล่นกีตาร์", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎸" },
  { en: "playing piano", th: "การเล่นเปียโน", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎹" },
  { en: "collecting antiques", th: "การสะสมของโบราณ", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🏺" },
  { en: "collecting stickers", th: "การสะสมสติกเกอร์", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🏷️" },
  { en: "wine tasting", th: "การชิมไวน์", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🍷" },
  { en: "cooking", th: "การทำอาหาร", category: "กีฬาและงานอดิเรก", level: "A1", emoji: "🍳" },
  { en: "baking cakes", th: "การทำเค้ก", category: "กีฬาและงานอดิเรก", level: "A2", emoji: "🎂" },
  { en: "flower arranging", th: "การจัดดอกไม้", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "💐" },
  { en: "bonsai", th: "บอนไซ", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🌳" },
  { en: "terrarium", th: "สวนในขวดแก้ว", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🪴" },
  { en: "aquarium keeping", th: "การเลี้ยงปลาสวยงาม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🐠" },
  { en: "pet training", th: "การฝึกสัตว์เลี้ยง", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🐕" },
  { en: "skydiving", th: "การกระโดดร่ม", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🪂" },
  { en: "paragliding", th: "การเล่นร่มร่อน", category: "กีฬาและงานอดิเรก", level: "B2", emoji: "🪂" },
  { en: "bungee jumping", th: "การกระโดดบันจี้จัมพ์", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🤸" },
  { en: "geocaching", th: "การล่าสมบัติด้วยจีพีเอส", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🗺️" },
  { en: "metal detecting", th: "การหาโลหะด้วยเครื่องตรวจจับ", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🔍" },
  { en: "kite making", th: "การทำว่าว", category: "กีฬาและงานอดิเรก", level: "B1", emoji: "🪁" },
  { en: "amateur radio", th: "วิทยุสมัครเล่น", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "📻" },
  { en: "whittling", th: "การแกะสลักไม้", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🔪" },
  { en: "leatherworking", th: "งานเครื่องหนัง", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🧵" },
  { en: "needlepoint", th: "การปักผ้าใบ", category: "กีฬาและงานอดิเรก", level: "C1", emoji: "🧵" },
  { en: "go down", th: "ลดลง", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "go off", th: "ดังขึ้น(นาฬิกาปลุก)", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "go up", th: "เพิ่มขึ้น", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "go without", th: "อยู่โดยไม่มี", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "hold on", th: "รอสักครู่", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "hold up", th: "ทำให้ล่าช้า", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "hold back", th: "ยับยั้งไว้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "break in", th: "งัดเข้าไป", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "break into", th: "บุกรุกเข้าไป", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "break away", th: "แยกตัวออกไป", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "bring about", th: "ทำให้เกิดขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "bring down", th: "ทำให้ลดลง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "bring out", th: "นำออกมา", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "bring together", th: "นำมารวมกัน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "build up", th: "สร้างขึ้นทีละน้อย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "call back", th: "โทรกลับ", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "call for", th: "เรียกร้อง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "call in", th: "เรียกเข้ามา", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "call out", th: "เรียกออกมา", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "carry away", th: "พาไป(อารมณ์พาไป)", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "catch up", th: "ตามให้ทัน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "catch on", th: "เป็นที่นิยม", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "check in", th: "เช็คอิน", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "check out", th: "เช็คเอาท์", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "cheer up", th: "ทำให้ร่าเริงขึ้น", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "clean up", th: "ทำความสะอาด", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "clear up", th: "ทำให้กระจ่าง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "close down", th: "ปิดกิจการ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "come about", th: "เกิดขึ้น", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "come along", th: "มาด้วยกัน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" }
];
