const VOCAB_PART_7 = [
  { en: "smartphone", th: "สมาร์ตโฟน", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📱" },
  { en: "laptop", th: "แล็ปท็อป", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "💻" },
  { en: "desktop computer", th: "คอมพิวเตอร์ตั้งโต๊ะ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🖥️" },
  { en: "smartwatch", th: "สมาร์ตวอทช์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "⌚" },
  { en: "headphones", th: "หูฟัง", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🎧" },
  { en: "earbuds", th: "หูฟังอินเอียร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🎧" },
  { en: "wireless earbuds", th: "หูฟังไร้สาย", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🎧" },
  { en: "keyboard", th: "คีย์บอร์ด", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "⌨️" },
  { en: "monitor", th: "จอมอนิเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🖥️" },
  { en: "printer", th: "เครื่องพิมพ์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🖨️" },
  { en: "scanner", th: "เครื่องสแกน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "webcam", th: "เว็บแคม", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📷" },
  { en: "microphone", th: "ไมโครโฟน", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🎤" },
  { en: "speaker", th: "ลำโพง", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🔊" },
  { en: "charger", th: "ที่ชาร์จ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🔌" },
  { en: "power bank", th: "พาวเวอร์แบงก์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔋" },
  { en: "USB drive", th: "แฟลชไดรฟ์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💾" },
  { en: "external hard drive", th: "ฮาร์ดดิสก์ภายนอก", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "💾" },
  { en: "memory card", th: "การ์ดหน่วยความจำ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💾" },
  { en: "SIM card", th: "ซิมการ์ด", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📶" },
  { en: "router", th: "เราเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📡" },
  { en: "Wi-Fi router", th: "เราเตอร์ไวไฟ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📡" },
  { en: "modem", th: "โมเด็ม", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "drone", th: "โดรน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🚁" },
  { en: "digital camera", th: "กล้องดิจิทัล", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📷" },
  { en: "gaming console", th: "เครื่องเล่นเกม", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🎮" },
  { en: "VR headset", th: "แว่นเสมือนจริง", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🥽" },
  { en: "e-reader", th: "เครื่องอ่านอีบุ๊ก", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "📖" },
  { en: "remote control", th: "รีโมตคอนโทรล", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🎛️" },
  { en: "charging cable", th: "สายชาร์จ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔌" },
  { en: "HDMI cable", th: "สาย HDMI", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "adapter", th: "อะแดปเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔌" },
  { en: "docking station", th: "แท่นเชื่อมต่อ", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "stylus", th: "ปากกาสไตลัส", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "touchscreen", th: "จอสัมผัส", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📱" },
  { en: "motherboard", th: "เมนบอร์ด", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "processor", th: "โปรเซสเซอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "CPU", th: "ซีพียู", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "GPU", th: "การ์ดจอ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "RAM", th: "แรม", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "hard drive", th: "ฮาร์ดดิสก์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💾" },
  { en: "solid state drive", th: "เอสเอสดี", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "💾" },
  { en: "cooling fan", th: "พัดลมระบายความร้อน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "circuit board", th: "แผงวงจร", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "sensor", th: "เซนเซอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "microchip", th: "ไมโครชิป", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "satellite dish", th: "จานดาวเทียม", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "📡" },
  { en: "antenna", th: "เสาอากาศ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "📡" },
  { en: "smart speaker", th: "ลำโพงอัจฉริยะ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🔊" },
  { en: "smart TV", th: "สมาร์ตทีวี", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📺" },
  { en: "smart home device", th: "อุปกรณ์บ้านอัจฉริยะ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🏠" },
  { en: "security camera", th: "กล้องวงจรปิด", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📹" },
  { en: "fingerprint scanner", th: "เครื่องสแกนลายนิ้วมือ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "👆" },
  { en: "barcode scanner", th: "เครื่องสแกนบาร์โค้ด", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "3D printer", th: "เครื่องพิมพ์สามมิติ", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "🖨️" },
  { en: "server", th: "เซิร์ฟเวอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "data center", th: "ศูนย์ข้อมูล", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "internet", th: "อินเทอร์เน็ต", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🌐" },
  { en: "website", th: "เว็บไซต์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🌐" },
  { en: "webpage", th: "หน้าเว็บ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "web browser", th: "เว็บเบราว์เซอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "email", th: "อีเมล", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📧" },
  { en: "email address", th: "ที่อยู่อีเมล", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📧" },
  { en: "password", th: "รหัสผ่าน", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🔒" },
  { en: "username", th: "ชื่อผู้ใช้", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "" },
  { en: "login", th: "เข้าสู่ระบบ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "" },
  { en: "logout", th: "ออกจากระบบ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "" },
  { en: "download", th: "ดาวน์โหลด", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "⬇️" },
  { en: "upload", th: "อัปโหลด", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "⬆️" },
  { en: "computer file", th: "ไฟล์คอมพิวเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📄" },
  { en: "folder", th: "โฟลเดอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📁" },
  { en: "software", th: "ซอฟต์แวร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "application", th: "แอปพลิเคชัน", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "" },
  { en: "mobile app", th: "แอปมือถือ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📱" },
  { en: "operating system", th: "ระบบปฏิบัติการ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "software update", th: "การอัปเดตซอฟต์แวร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "install", th: "ติดตั้ง", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "uninstall", th: "ถอนการติดตั้ง", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "computer virus", th: "ไวรัสคอมพิวเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🦠" },
  { en: "antivirus software", th: "ซอฟต์แวร์ป้องกันไวรัส", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🛡️" },
  { en: "firewall", th: "ไฟร์วอลล์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🔥" },
  { en: "malware", th: "มัลแวร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "hacker", th: "แฮกเกอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💻" },
  { en: "cybersecurity", th: "ความปลอดภัยทางไซเบอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "🔐" },
  { en: "encryption", th: "การเข้ารหัส", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "🔐" },
  { en: "cloud storage", th: "พื้นที่จัดเก็บข้อมูลบนคลาวด์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "☁️" },
  { en: "data backup", th: "การสำรองข้อมูล", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "database", th: "ฐานข้อมูล", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "algorithm", th: "อัลกอริทึม", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "artificial intelligence", th: "ปัญญาประดิษฐ์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🤖" },
  { en: "machine learning", th: "การเรียนรู้ของเครื่อง", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "chatbot", th: "แชตบอต", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🤖" },
  { en: "virtual reality", th: "ความเป็นจริงเสมือน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🥽" },
  { en: "augmented reality", th: "ความเป็นจริงเสริม", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "programming", th: "การเขียนโปรแกรม", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "computer code", th: "โค้ดคอมพิวเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "coding", th: "การเขียนโค้ด", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "software developer", th: "นักพัฒนาซอฟต์แวร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "software bug", th: "บั๊ก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🐛" },
  { en: "debug", th: "แก้บั๊ก", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "script", th: "สคริปต์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "user interface", th: "ส่วนติดต่อผู้ใช้", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "homepage", th: "หน้าแรก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "hyperlink", th: "ไฮเปอร์ลิงก์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔗" },
  { en: "bookmark", th: "บุ๊กมาร์ก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔖" },
  { en: "browser cookie", th: "คุกกี้เบราว์เซอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "cache", th: "แคช", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "broadband", th: "บรอดแบนด์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "bandwidth", th: "แบนด์วิดท์", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "streaming", th: "การสตรีมมิง", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "buffering", th: "การบัฟเฟอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "notification", th: "การแจ้งเตือน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔔" },
  { en: "pop-up window", th: "หน้าต่างป๊อปอัป", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "spam email", th: "อีเมลขยะ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📧" },
  { en: "phishing", th: "การฟิชชิง", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "🎣" },
  { en: "firmware", th: "เฟิร์มแวร์", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "" },
  { en: "device driver", th: "ไดรเวอร์อุปกรณ์", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "plugin", th: "ปลั๊กอิน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "browser extension", th: "ส่วนขยายเบราว์เซอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "template", th: "เทมเพลต", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "dashboard", th: "แดชบอร์ด", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "settings", th: "การตั้งค่า", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "⚙️" },
  { en: "configuration", th: "การกำหนดค่า", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "computer network", th: "เครือข่ายคอมพิวเตอร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "local area network", th: "เครือข่ายท้องถิ่น", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "IP address", th: "ที่อยู่ไอพี", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "domain name", th: "ชื่อโดเมน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "web address", th: "ที่อยู่เว็บไซต์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "web hosting", th: "การให้บริการเว็บโฮสติ้ง", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "online shopping", th: "การช้อปปิ้งออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🛒" },
  { en: "digital signature", th: "ลายเซ็นดิจิทัล", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "two-factor authentication", th: "การยืนยันตัวตนสองขั้นตอน", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "🔐" },
  { en: "biometric scan", th: "การสแกนชีวมิติ", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "" },
  { en: "QR code", th: "คิวอาร์โค้ด", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📱" },
  { en: "GPS", th: "จีพีเอส", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🛰️" },
  { en: "geolocation", th: "การระบุตำแหน่งทางภูมิศาสตร์", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "📍" },
  { en: "voice recognition", th: "การรู้จำเสียง", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "facial recognition", th: "การจดจำใบหน้า", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "text recognition", th: "การรู้จำข้อความ", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "" },
  { en: "autocomplete", th: "การเติมข้อความอัตโนมัติ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "spell checker", th: "ตัวตรวจการสะกดคำ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "social media", th: "โซเชียลมีเดีย", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📱" },
  { en: "online profile", th: "โปรไฟล์ออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "online post", th: "โพสต์ออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "like button", th: "ปุ่มไลก์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "👍" },
  { en: "comment section", th: "ช่องแสดงความคิดเห็น", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💬" },
  { en: "share button", th: "ปุ่มแชร์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "" },
  { en: "follower", th: "ผู้ติดตาม", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "hashtag", th: "แฮชแท็ก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "#️⃣" },
  { en: "news feed", th: "ฟีดข่าว", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "social media story", th: "สตอรี่", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "live stream", th: "ไลฟ์สด", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📡" },
  { en: "video call", th: "วิดีโอคอล", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📹" },
  { en: "voice call", th: "สายเสียง", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📞" },
  { en: "online chat", th: "แชทออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "💬" },
  { en: "instant message", th: "ข้อความทันที", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "text message", th: "ข้อความ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "💬" },
  { en: "group chat", th: "แชทกลุ่ม", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "💬" },
  { en: "emoji", th: "อิโมจิ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "😀" },
  { en: "sticker", th: "สติกเกอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "" },
  { en: "internet meme", th: "มีม", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "viral video", th: "วิดีโอไวรัล", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "social media influencer", th: "อินฟลูเอนเซอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "subscriber", th: "ผู้ติดตามช่อง", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "subscription", th: "การสมัครสมาชิก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "push notification", th: "การแจ้งเตือนแบบพุช", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🔔" },
  { en: "direct message", th: "ข้อความส่วนตัว", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "block user", th: "บล็อกผู้ใช้", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🚫" },
  { en: "mute notification", th: "ปิดเสียงแจ้งเตือน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🔇" },
  { en: "online report", th: "รายงานเนื้อหา", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "photo tag", th: "การแท็กรูปภาพ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "mention", th: "การกล่าวถึง", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "trending topic", th: "หัวข้อกำลังฮิต", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "content creator", th: "ผู้สร้างเนื้อหา", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "podcast", th: "พอดแคสต์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🎙️" },
  { en: "blog", th: "บล็อก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "blogger", th: "บล็อกเกอร์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "video blog", th: "วล็อก", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "online forum", th: "เว็บบอร์ด", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "online community", th: "ชุมชนออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "screen time", th: "เวลาหน้าจอ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "digital detox", th: "การล้างพิษดิจิทัล", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "" },
  { en: "telephone", th: "โทรศัพท์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "☎️" },
  { en: "mobile phone", th: "โทรศัพท์มือถือ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📱" },
  { en: "landline phone", th: "โทรศัพท์บ้าน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "☎️" },
  { en: "phone call", th: "การโทรศัพท์", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📞" },
  { en: "missed call", th: "สายที่ไม่ได้รับ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📞" },
  { en: "voicemail", th: "ข้อความเสียง", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "SMS", th: "เอสเอ็มเอส", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💬" },
  { en: "MMS", th: "เอ็มเอ็มเอส", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "international roaming", th: "โรมมิงระหว่างประเทศ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "mobile signal", th: "สัญญาณมือถือ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📶" },
  { en: "network coverage", th: "พื้นที่ให้บริการเครือข่าย", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "prepaid SIM card", th: "ซิมเติมเงิน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📶" },
  { en: "postpaid plan", th: "แพ็กเกจรายเดือน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "mobile data plan", th: "แพ็กเกจอินเทอร์เน็ตมือถือ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "📶" },
  { en: "Wi-Fi", th: "ไวไฟ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "📶" },
  { en: "Wi-Fi hotspot", th: "จุดปล่อยสัญญาณไวไฟ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📶" },
  { en: "Bluetooth", th: "บลูทูธ", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🔵" },
  { en: "fiber optic internet", th: "อินเทอร์เน็ตใยแก้วนำแสง", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "telecommunications", th: "โทรคมนาคม", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "satellite communication", th: "การสื่อสารผ่านดาวเทียม", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "🛰️" },
  { en: "call center", th: "ศูนย์บริการลูกค้าทางโทรศัพท์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "technical support", th: "ฝ่ายสนับสนุนทางเทคนิค", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "telephone operator", th: "พนักงานรับสายโทรศัพท์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "video conference", th: "การประชุมทางวิดีโอ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "📹" },
  { en: "online meeting", th: "การประชุมออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💻" },
  { en: "screen sharing", th: "การแชร์หน้าจอ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🖥️" },
  { en: "file sharing", th: "การแชร์ไฟล์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "data transfer", th: "การถ่ายโอนข้อมูล", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "file compression", th: "การบีบอัดไฟล์", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "zip file", th: "ไฟล์ซิป", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🗜️" },
  { en: "pdf file", th: "ไฟล์พีดีเอฟ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📄" },
  { en: "spreadsheet software", th: "โปรแกรมสเปรดชีต", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "word processor", th: "โปรแกรมประมวลผลคำ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "slideshow presentation", th: "การนำเสนอสไลด์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "e-book", th: "อีบุ๊ก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📖" },
  { en: "podcast episode", th: "ตอนพอดแคสต์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "online course", th: "คอร์สออนไลน์", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "webinar", th: "เว็บบินาร์", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "💻" },
  { en: "digital nomad", th: "ดิจิทัลโนแมด", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "" },
  { en: "virtual assistant", th: "ผู้ช่วยเสมือน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "smart plug", th: "ปลั๊กอัจฉริยะ", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🔌" },
  { en: "wearable device", th: "อุปกรณ์สวมใส่", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "fitness tracker", th: "เครื่องติดตามการออกกำลังกาย", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "charging port", th: "พอร์ตชาร์จ", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔌" },
  { en: "screen resolution", th: "ความละเอียดหน้าจอ", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "pixel", th: "พิกเซล", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "touchpad", th: "ทัชแพด", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "" },
  { en: "laptop bag", th: "กระเป๋าโน้ตบุ๊ก", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "💼" },
  { en: "tech support", th: "ฝ่ายช่วยเหลือด้านเทคนิค", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "software license", th: "ใบอนุญาตซอฟต์แวร์", category: "เทคโนโลยีและการสื่อสาร", level: "B2", emoji: "" },
  { en: "open source software", th: "ซอฟต์แวร์โอเพนซอร์ส", category: "เทคโนโลยีและการสื่อสาร", level: "C1", emoji: "" },
  { en: "user manual", th: "คู่มือผู้ใช้", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "📖" },
  { en: "troubleshooting", th: "การแก้ไขปัญหา", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "🔧" },
  { en: "system crash", th: "ระบบล่ม", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "reboot", th: "รีบูตเครื่อง", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔄" },
  { en: "factory reset", th: "การรีเซ็ตค่าจากโรงงาน", category: "เทคโนโลยีและการสื่อสาร", level: "B1", emoji: "" },
  { en: "airplane mode", th: "โหมดเครื่องบิน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "✈️" },
  { en: "do not disturb mode", th: "โหมดห้ามรบกวน", category: "เทคโนโลยีและการสื่อสาร", level: "A2", emoji: "🔕" },
  { en: "dark mode", th: "โหมดมืด", category: "เทคโนโลยีและการสื่อสาร", level: "A1", emoji: "🌙" },
  { en: "money", th: "เงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💰" },
  { en: "cash", th: "เงินสด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💵" },
  { en: "coin", th: "เหรียญ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🪙" },
  { en: "banknote", th: "ธนบัตร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💵" },
  { en: "currency", th: "สกุลเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💱" },
  { en: "exchange rate", th: "อัตราแลกเปลี่ยน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "💱" },
  { en: "bank account", th: "บัญชีธนาคาร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏦" },
  { en: "savings account", th: "บัญชีออมทรัพย์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🏦" },
  { en: "checking account", th: "บัญชีกระแสรายวัน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "🏦" },
  { en: "ATM", th: "ตู้เอทีเอ็ม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏧" },
  { en: "debit card", th: "บัตรเดบิต", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💳" },
  { en: "credit card", th: "บัตรเครดิต", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💳" },
  { en: "credit limit", th: "วงเงินเครดิต", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "interest rate", th: "อัตราดอกเบี้ย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "interest", th: "ดอกเบี้ย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "loan", th: "เงินกู้", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "mortgage", th: "สินเชื่อบ้าน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "🏠" },
  { en: "debt", th: "หนี้สิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "deposit", th: "เงินฝาก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "withdrawal", th: "การถอนเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "bank transfer", th: "การโอนเงินผ่านธนาคาร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "wire transfer", th: "การโอนเงินด่วน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "online banking", th: "ธนาคารออนไลน์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💻" },
  { en: "mobile banking", th: "โมบายแบงกิ้ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📱" },
  { en: "PIN code", th: "รหัสพิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "" },
  { en: "bank statement", th: "ใบแจ้งยอดบัญชี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📄" },
  { en: "account balance", th: "ยอดคงเหลือในบัญชี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "overdraft", th: "เงินเบิกเกินบัญชี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "insurance", th: "ประกันภัย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🛡️" },
  { en: "investment", th: "การลงทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📈" },
  { en: "investor", th: "นักลงทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "stock", th: "หุ้น", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📈" },
  { en: "stock market", th: "ตลาดหุ้น", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📈" },
  { en: "share", th: "หุ้น", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "bond", th: "พันธบัตร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "mutual fund", th: "กองทุนรวม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "dividend", th: "เงินปันผล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "investment portfolio", th: "พอร์ตการลงทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "cryptocurrency", th: "สกุลเงินดิจิทัล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "bitcoin", th: "บิตคอยน์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "digital wallet", th: "กระเป๋าเงินดิจิทัล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📱" },
  { en: "budget", th: "งบประมาณ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "savings", th: "เงินออม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💰" },
  { en: "expense", th: "ค่าใช้จ่าย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "income", th: "รายได้", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💵" },
  { en: "tax", th: "ภาษี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "income tax", th: "ภาษีเงินได้", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "value-added tax", th: "ภาษีมูลค่าเพิ่ม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "tax refund", th: "เงินคืนภาษี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "receipt", th: "ใบเสร็จรับเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🧾" },
  { en: "invoice", th: "ใบแจ้งหนี้", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🧾" },
  { en: "bill", th: "ใบเรียกเก็บเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🧾" },
  { en: "payment", th: "การชำระเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💳" },
  { en: "installment", th: "การผ่อนชำระ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "financial statement", th: "งบการเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "balance sheet", th: "งบดุล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "profit", th: "กำไร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📈" },
  { en: "loss", th: "ขาดทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📉" },
  { en: "revenue", th: "รายได้รวม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "asset", th: "สินทรัพย์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "liability", th: "หนี้สินทางธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "financial audit", th: "การตรวจสอบบัญชี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "bankruptcy", th: "การล้มละลาย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "inflation", th: "เงินเฟ้อ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📈" },
  { en: "economy", th: "เศรษฐกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "economic growth", th: "การเติบโตทางเศรษฐกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "📈" },
  { en: "gross domestic product", th: "ผลิตภัณฑ์มวลรวมในประเทศ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "recession", th: "ภาวะเศรษฐกิจถดถอย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "📉" },
  { en: "retirement fund", th: "กองทุนเกษียณอายุ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "shop", th: "ร้านค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏪" },
  { en: "store", th: "ร้าน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏬" },
  { en: "department store", th: "ห้างสรรพสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏬" },
  { en: "customer", th: "ลูกค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "" },
  { en: "seller", th: "ผู้ขาย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "buyer", th: "ผู้ซื้อ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "price", th: "ราคา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💲" },
  { en: "discount", th: "ส่วนลด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏷️" },
  { en: "sale", th: "การลดราคา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏷️" },
  { en: "clearance sale", th: "การเคลียร์สต๊อก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "🏷️" },
  { en: "coupon", th: "คูปอง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🎟️" },
  { en: "voucher", th: "บัตรกำนัล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🎟️" },
  { en: "gift card", th: "บัตรของขวัญ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🎁" },
  { en: "price tag", th: "ป้ายราคา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏷️" },
  { en: "barcode", th: "บาร์โค้ด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "shopping cart", th: "รถเข็นช้อปปิ้ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🛒" },
  { en: "shopping basket", th: "ตะกร้าช้อปปิ้ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🧺" },
  { en: "checkout counter", th: "จุดชำระเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "cash register", th: "เครื่องคิดเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "shopping bag", th: "ถุงช้อปปิ้ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🛍️" },
  { en: "delivery", th: "การจัดส่ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "📦" },
  { en: "shipping", th: "การขนส่ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🚚" },
  { en: "free shipping", th: "จัดส่งฟรี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📦" },
  { en: "online store", th: "ร้านค้าออนไลน์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🛒" },
  { en: "product warranty", th: "การรับประกันสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "return policy", th: "นโยบายการคืนสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "exchange policy", th: "นโยบายการแลกเปลี่ยนสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "clothing size", th: "ขนาดเสื้อผ้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "" },
  { en: "fitting room", th: "ห้องลองเสื้อผ้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "brand", th: "แบรนด์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "" },
  { en: "brand name", th: "ชื่อยี่ห้อ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "product", th: "สินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "📦" },
  { en: "merchandise", th: "สินค้าที่จำหน่าย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "quality", th: "คุณภาพ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "quantity", th: "ปริมาณ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "wholesale", th: "การขายส่ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "retail", th: "การขายปลีก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "retailer", th: "ผู้ค้าปลีก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "supplier", th: "ผู้จัดหาสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "vendor", th: "ผู้ขาย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "stock inventory", th: "สินค้าคงคลัง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "out of stock", th: "สินค้าหมด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "bargain", th: "ของถูก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💰" },
  { en: "negotiate a price", th: "ต่อรองราคา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "haggle", th: "ต่อรองราคาสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "membership card", th: "บัตรสมาชิก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💳" },
  { en: "loyalty program", th: "โปรแกรมสะสมแต้ม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "subscription box", th: "กล่องสมัครสมาชิก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📦" },
  { en: "packaging", th: "บรรจุภัณฑ์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📦" },
  { en: "product label", th: "ฉลากสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "catalog", th: "แคตตาล็อก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "advertisement", th: "โฆษณา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📢" },
  { en: "flash sale", th: "การลดราคาแบบฉับพลัน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "⚡" },
  { en: "seasonal sale", th: "การลดราคาตามฤดูกาล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "company", th: "บริษัท", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏢" },
  { en: "business", th: "ธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "💼" },
  { en: "chief executive officer", th: "ประธานเจ้าหน้าที่บริหาร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "office", th: "สำนักงาน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "🏢" },
  { en: "business meeting", th: "การประชุมธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "contract", th: "สัญญา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📄" },
  { en: "business agreement", th: "ข้อตกลงทางธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "negotiation", th: "การเจรจาต่อรอง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "business deal", th: "ดีลธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "partnership", th: "หุ้นส่วนธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "merger", th: "การควบรวมกิจการ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "acquisition", th: "การเข้าซื้อกิจการ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "stakeholder", th: "ผู้มีส่วนได้ส่วนเสีย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "client", th: "ลูกค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "client service", th: "การบริการลูกค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "business plan", th: "แผนธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📋" },
  { en: "business proposal", th: "ข้อเสนอทางธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "business report", th: "รายงานธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📊" },
  { en: "memo", th: "บันทึกข้อความ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📝" },
  { en: "job interview", th: "การสัมภาษณ์งาน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "job offer", th: "ข้อเสนองาน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "salary negotiation", th: "การต่อรองเงินเดือน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "job promotion", th: "การเลื่อนตำแหน่ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "termination", th: "การเลิกจ้าง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "project", th: "โครงการ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A1", emoji: "" },
  { en: "leadership", th: "ภาวะผู้นำ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "business strategy", th: "กลยุทธ์ทางธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "marketing", th: "การตลาด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📢" },
  { en: "advertising", th: "การโฆษณา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "📢" },
  { en: "brand awareness", th: "การรับรู้แบรนด์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "target market", th: "ตลาดเป้าหมาย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "🎯" },
  { en: "competitor", th: "คู่แข่ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "market share", th: "ส่วนแบ่งตลาด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "supply chain", th: "ห่วงโซ่อุปทาน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "logistics", th: "โลจิสติกส์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "🚚" },
  { en: "manufacturer", th: "ผู้ผลิต", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "distributor", th: "ผู้จัดจำหน่าย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "franchise", th: "แฟรนไชส์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "trademark", th: "เครื่องหมายการค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "patent", th: "สิทธิบัตร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "copyright", th: "ลิขสิทธิ์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "business license", th: "ใบอนุญาตประกอบธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "government regulation", th: "กฎระเบียบของรัฐบาล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "regulatory compliance", th: "การปฏิบัติตามกฎระเบียบ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "industry", th: "อุตสาหกรรม", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "business sector", th: "ภาคธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "trade", th: "การค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "import", th: "การนำเข้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "export", th: "การส่งออก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "import tariff", th: "ภาษีนำเข้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "customs duty", th: "ภาษีศุลกากร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "net worth", th: "มูลค่าสุทธิ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "cash flow", th: "กระแสเงินสด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "💵" },
  { en: "shareholder meeting", th: "การประชุมผู้ถือหุ้น", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "annual report", th: "รายงานประจำปี", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📊" },
  { en: "quarterly earnings", th: "ผลกำไรรายไตรมาส", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "business expense", th: "ค่าใช้จ่ายทางธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "overhead cost", th: "ค่าใช้จ่ายในการดำเนินงาน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "gross profit", th: "กำไรขั้นต้น", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "net profit", th: "กำไรสุทธิ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "break-even point", th: "จุดคุ้มทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "return on investment", th: "ผลตอบแทนจากการลงทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "venture capital", th: "เงินทุนร่วมลงทุน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "angel investor", th: "นักลงทุนเทวดา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "crowdfunding", th: "การระดมทุนจากมวลชน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "business loan", th: "สินเชื่อธุรกิจ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "collateral", th: "หลักประกัน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "C1", emoji: "" },
  { en: "credit score", th: "คะแนนเครดิต", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "financial advisor", th: "ที่ปรึกษาทางการเงิน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "insurance policy", th: "กรมธรรม์ประกันภัย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "📄" },
  { en: "insurance premium", th: "เบี้ยประกันภัย", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "insurance claim", th: "การเคลมประกัน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "life insurance", th: "ประกันชีวิต", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "health insurance", th: "ประกันสุขภาพ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "car insurance", th: "ประกันรถยนต์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🚗" },
  { en: "currency exchange", th: "การแลกเปลี่ยนเงินตรา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "💱" },
  { en: "foreign exchange", th: "การแลกเปลี่ยนเงินตราต่างประเทศ", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "wholesale price", th: "ราคาขายส่ง", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "retail price", th: "ราคาขายปลีก", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "markup", th: "การบวกกำไร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "profit margin", th: "อัตรากำไร", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "supply and demand", th: "อุปสงค์และอุปทาน", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B2", emoji: "" },
  { en: "market competition", th: "การแข่งขันในตลาด", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "consumer", th: "ผู้บริโภค", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "" },
  { en: "consumer rights", th: "สิทธิผู้บริโภค", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "online marketplace", th: "ตลาดออนไลน์", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "A2", emoji: "🛒" },
  { en: "auction", th: "การประมูล", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "🔨" },
  { en: "bidding", th: "การเสนอราคา", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "trade fair", th: "งานแสดงสินค้า", category: "ธุรกิจ เงิน และการช้อปปิ้ง", level: "B1", emoji: "" },
  { en: "get off", th: "ลงจาก(รถ)", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "get on", th: "ขึ้น(รถ)", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "get rid of", th: "กำจัดทิ้ง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "get together", th: "มารวมตัวกัน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "give up on", th: "ยอมแพ้กับ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "go ahead", th: "เชิญเลย/ดำเนินการต่อ", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "go away", th: "ไปให้พ้น", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "go by", th: "ผ่านไป(เวลา)", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "go for", th: "เลือกเอา", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "grow up", th: "เติบโตขึ้น", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "hand in", th: "ส่งงาน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "hand out", th: "แจกจ่าย", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "hand over", th: "ส่งมอบให้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "hang on", th: "รอเดี๋ยว", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "head off", th: "ออกเดินทาง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "hold off", th: "ยับยั้งชั่วคราว", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "keep away", th: "อยู่ให้ห่าง", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "keep on", th: "ทำต่อไป", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "keep out", th: "ห้ามเข้า", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "knock down", th: "ทุบทำลาย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "knock out", th: "ทำให้สลบ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "lay off", th: "เลิกจ้างงาน", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "lead to", th: "นำไปสู่", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "leave behind", th: "ทิ้งไว้ข้างหลัง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "leave out", th: "ละเว้นไม่รวม", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "let down", th: "ทำให้ผิดหวัง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "let in", th: "ให้เข้ามา", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "let off", th: "ปล่อยไปไม่ลงโทษ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "live up to", th: "ทำได้ตามที่คาดหวัง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "log in", th: "เข้าสู่ระบบ", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "log out", th: "ออกจากระบบ", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "look down on", th: "ดูถูก", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "look out", th: "ระวัง", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "look over", th: "ตรวจดูอย่างคร่าวๆ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "look up to", th: "เคารพนับถือ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "make out", th: "มองเห็นได้ลางๆ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "make up for", th: "ชดเชยให้", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "move in", th: "ย้ายเข้า", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "move on", th: "ก้าวต่อไป", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "move out", th: "ย้ายออก", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "narrow down", th: "ทำให้แคบลง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "pass on", th: "ส่งต่อ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "pass out", th: "หมดสติ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "pay back", th: "จ่ายคืน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "pay off", th: "ได้ผลตอบแทน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "play down", th: "ลดความสำคัญลง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "put across", th: "สื่อสารให้เข้าใจ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" }
];
