const VOCAB_PART_6 = [
  { en: "veterinarian", th: "สัตวแพทย์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🐾" },
  { en: "psychiatrist", th: "จิตแพทย์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧠" },
  { en: "psychologist", th: "นักจิตวิทยา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧠" },
  { en: "paramedic", th: "เจ้าหน้าที่พยาบาลฉุกเฉิน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🚑" },
  { en: "midwife", th: "พยาบาลผดุงครรภ์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🤱" },
  { en: "radiologist", th: "รังสีแพทย์", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🩻" },
  { en: "optometrist", th: "นักทัศนมาตร", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "👓" },
  { en: "chiropractor", th: "หมอจัดกระดูก", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🦴" },
  { en: "nutritionist", th: "นักโภชนาการ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🥗" },
  { en: "pediatrician", th: "กุมารแพทย์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "👶" },
  { en: "cardiologist", th: "แพทย์โรคหัวใจ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "❤️" },
  { en: "dermatologist", th: "แพทย์ผิวหนัง", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🧴" },
  { en: "anesthesiologist", th: "วิสัญญีแพทย์", category: "อาชีพและที่ทำงาน", level: "C1", emoji: "💉" },
  { en: "orthodontist", th: "ทันตแพทย์จัดฟัน", category: "อาชีพและที่ทำงาน", level: "C1", emoji: "🦷" },
  { en: "lawyer", th: "ทนายความ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "⚖️" },
  { en: "judge", th: "ผู้พิพากษา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "⚖️" },
  { en: "attorney", th: "ทนายความ (สหรัฐฯ)", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "⚖️" },
  { en: "paralegal", th: "ผู้ช่วยทนายความ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📑" },
  { en: "notary", th: "ผู้รับรองเอกสาร", category: "อาชีพและที่ทำงาน", level: "C1", emoji: "📜" },
  { en: "prosecutor", th: "อัยการ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "⚖️" },
  { en: "electrician", th: "ช่างไฟฟ้า", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🔌" },
  { en: "plumber", th: "ช่างประปา", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🔧" },
  { en: "carpenter", th: "ช่างไม้", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🪚" },
  { en: "mechanic", th: "ช่างเครื่องยนต์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🔩" },
  { en: "welder", th: "ช่างเชื่อม", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🔥" },
  { en: "mason", th: "ช่างก่ออิฐ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧱" },
  { en: "painter", th: "ช่างทาสี", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎨" },
  { en: "locksmith", th: "ช่างกุญแจ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🔑" },
  { en: "blacksmith", th: "ช่างตีเหล็ก", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "⚒️" },
  { en: "roofer", th: "ช่างมุงหลังคา", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🏠" },
  { en: "plasterer", th: "ช่างปูนฉาบ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🧱" },
  { en: "glazier", th: "ช่างกระจก", category: "อาชีพและที่ทำงาน", level: "C1", emoji: "🪟" },
  { en: "upholsterer", th: "ช่างบุเบาะ", category: "อาชีพและที่ทำงาน", level: "C1", emoji: "🛋️" },
  { en: "machinist", th: "ช่างกลึง", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "⚙️" },
  { en: "engineer", th: "วิศวกร", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🛠️" },
  { en: "architect", th: "สถาปนิก", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏛️" },
  { en: "surveyor", th: "นักสำรวจ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📐" },
  { en: "civil engineer", th: "วิศวกรโยธา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏗️" },
  { en: "mechanical engineer", th: "วิศวกรเครื่องกล", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "⚙️" },
  { en: "electrical engineer", th: "วิศวกรไฟฟ้า", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "⚡" },
  { en: "foreman", th: "หัวหน้าคนงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "👷" },
  { en: "contractor", th: "ผู้รับเหมา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏗️" },
  { en: "actor", th: "นักแสดงชาย", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎭" },
  { en: "actress", th: "นักแสดงหญิง", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎭" },
  { en: "musician", th: "นักดนตรี", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎵" },
  { en: "singer", th: "นักร้อง", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🎤" },
  { en: "dancer", th: "นักเต้น", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💃" },
  { en: "artist", th: "ศิลปิน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎨" },
  { en: "sculptor", th: "ประติมากร", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🗿" },
  { en: "photographer", th: "ช่างภาพ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📷" },
  { en: "director", th: "ผู้กำกับ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎬" },
  { en: "producer", th: "ผู้อำนวยการสร้าง", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎬" },
  { en: "composer", th: "นักแต่งเพลง", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎼" },
  { en: "DJ", th: "ดีเจ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎧" },
  { en: "comedian", th: "นักแสดงตลก", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🤣" },
  { en: "animator", th: "นักสร้างแอนิเมชัน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎞️" },
  { en: "illustrator", th: "นักวาดภาพประกอบ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🖌️" },
  { en: "programmer", th: "โปรแกรมเมอร์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💻" },
  { en: "software engineer", th: "วิศวกรซอฟต์แวร์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💻" },
  { en: "web developer", th: "นักพัฒนาเว็บ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🌐" },
  { en: "data scientist", th: "นักวิทยาศาสตร์ข้อมูล", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📊" },
  { en: "IT support", th: "เจ้าหน้าที่ไอที", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🖥️" },
  { en: "network administrator", th: "ผู้ดูแลระบบเครือข่าย", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🌐" },
  { en: "system analyst", th: "นักวิเคราะห์ระบบ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "💻" },
  { en: "UX designer", th: "นักออกแบบ UX", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🎨" },
  { en: "database administrator", th: "ผู้ดูแลฐานข้อมูล", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🗄️" },
  { en: "cybersecurity analyst", th: "นักวิเคราะห์ความปลอดภัยไซเบอร์", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🔒" },
  { en: "scientist", th: "นักวิทยาศาสตร์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🔬" },
  { en: "biologist", th: "นักชีววิทยา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧬" },
  { en: "chemist", th: "นักเคมี", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧪" },
  { en: "physicist", th: "นักฟิสิกส์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "⚛️" },
  { en: "geologist", th: "นักธรณีวิทยา", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🪨" },
  { en: "astronomer", th: "นักดาราศาสตร์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🔭" },
  { en: "researcher", th: "นักวิจัย", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🔬" },
  { en: "lab technician", th: "ช่างเทคนิคห้องปฏิบัติการ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧪" },
  { en: "meteorologist", th: "นักอุตุนิยมวิทยา", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🌦️" },
  { en: "zoologist", th: "นักสัตววิทยา", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🦓" },
  { en: "waiter", th: "พนักงานเสิร์ฟชาย", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🍽️" },
  { en: "waitress", th: "พนักงานเสิร์ฟหญิง", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🍽️" },
  { en: "chef", th: "เชฟ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "👨‍🍳" },
  { en: "cook", th: "พ่อครัว", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🍳" },
  { en: "bartender", th: "บาร์เทนเดอร์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🍸" },
  { en: "barista", th: "บาริสต้า", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "☕" },
  { en: "receptionist", th: "พนักงานต้อนรับ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💁" },
  { en: "housekeeper", th: "แม่บ้าน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🧺" },
  { en: "hairdresser", th: "ช่างทำผม", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💇" },
  { en: "barber", th: "ช่างตัดผม", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💈" },
  { en: "beautician", th: "ช่างเสริมสวย", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💅" },
  { en: "hotel manager", th: "ผู้จัดการโรงแรม", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏨" },
  { en: "farmer", th: "เกษตรกร", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🌾" },
  { en: "fisherman", th: "ชาวประมง", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎣" },
  { en: "rancher", th: "เจ้าของฟาร์มปศุสัตว์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🐄" },
  { en: "beekeeper", th: "คนเลี้ยงผึ้ง", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🐝" },
  { en: "gardener", th: "คนสวน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🌻" },
  { en: "forester", th: "เจ้าหน้าที่ป่าไม้", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🌲" },
  { en: "manager", th: "ผู้จัดการ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💼" },
  { en: "accountant", th: "นักบัญชี", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📊" },
  { en: "secretary", th: "เลขานุการ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🗂️" },
  { en: "clerk", th: "เสมียน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🗃️" },
  { en: "salesperson", th: "พนักงานขาย", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🛍️" },
  { en: "marketer", th: "นักการตลาด", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📣" },
  { en: "consultant", th: "ที่ปรึกษา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧑‍💼" },
  { en: "auditor", th: "ผู้ตรวจสอบบัญชี", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📑" },
  { en: "banker", th: "นายธนาคาร", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🏦" },
  { en: "cashier", th: "แคชเชียร์", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "💵" },
  { en: "CEO", th: "ประธานเจ้าหน้าที่บริหาร", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "👔" },
  { en: "entrepreneur", th: "ผู้ประกอบการ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💡" },
  { en: "economist", th: "นักเศรษฐศาสตร์", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📈" },
  { en: "analyst", th: "นักวิเคราะห์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📊" },
  { en: "HR manager", th: "ผู้จัดการฝ่ายทรัพยากรบุคคล", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "👥" },
  { en: "recruiter", th: "ผู้สรรหาบุคลากร", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧑‍💼" },
  { en: "supervisor", th: "หัวหน้างาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧑‍💼" },
  { en: "police officer", th: "ตำรวจ", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "👮" },
  { en: "firefighter", th: "นักดับเพลิง", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🚒" },
  { en: "soldier", th: "ทหาร", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🪖" },
  { en: "diplomat", th: "นักการทูต", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🌍" },
  { en: "politician", th: "นักการเมือง", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏛️" },
  { en: "mayor", th: "นายกเทศมนตรี", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏛️" },
  { en: "civil servant", th: "ข้าราชการ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "postman", th: "บุรุษไปรษณีย์", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "📮" },
  { en: "librarian", th: "บรรณารักษ์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📚" },
  { en: "teacher", th: "ครู", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🍎" },
  { en: "journalist", th: "นักข่าว", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📰" },
  { en: "editor", th: "บรรณาธิการ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📝" },
  { en: "reporter", th: "ผู้สื่อข่าว", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎙️" },
  { en: "broadcaster", th: "ผู้ประกาศข่าว", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📺" },
  { en: "translator", th: "นักแปล", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🈯" },
  { en: "interpreter", th: "ล่าม", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🗣️" },
  { en: "driver", th: "คนขับรถ", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🚗" },
  { en: "taxi driver", th: "คนขับแท็กซี่", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🚕" },
  { en: "truck driver", th: "คนขับรถบรรทุก", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🚚" },
  { en: "sailor", th: "กะลาสีเรือ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "⚓" },
  { en: "bus driver", th: "คนขับรถบัส", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🚌" },
  { en: "tailor", th: "ช่างตัดเสื้อ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🧵" },
  { en: "cleaner", th: "แม่บ้านทำความสะอาด", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🧹" },
  { en: "security guard", th: "พนักงานรักษาความปลอดภัย", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💂" },
  { en: "janitor", th: "ภารโรง", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🧹" },
  { en: "model", th: "นางแบบ/นายแบบ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💃" },
  { en: "real estate agent", th: "นายหน้าอสังหาริมทรัพย์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏠" },
  { en: "insurance agent", th: "ตัวแทนประกันภัย", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📋" },
  { en: "event planner", th: "นักวางแผนงานอีเวนต์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎉" },
  { en: "fashion designer", th: "นักออกแบบแฟชั่น", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "👗" },
  { en: "graphic designer", th: "นักออกแบบกราฟิก", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🖥️" },
  { en: "astronaut", th: "นักบินอวกาศ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🚀" },
  { en: "archaeologist", th: "นักโบราณคดี", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏺" },
  { en: "historian", th: "นักประวัติศาสตร์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📜" },
  { en: "philosopher", th: "นักปรัชญา", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🤔" },
  { en: "linguist", th: "นักภาษาศาสตร์", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🗣️" },
  { en: "statistician", th: "นักสถิติ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📊" },
  { en: "mathematician", th: "นักคณิตศาสตร์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🔢" },
  { en: "actuary", th: "นักคณิตศาสตร์ประกันภัย", category: "อาชีพและที่ทำงาน", level: "C1", emoji: "📈" },
  { en: "stockbroker", th: "นายหน้าซื้อขายหุ้น", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📈" },
  { en: "property manager", th: "ผู้จัดการอสังหาริมทรัพย์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "personal trainer", th: "เทรนเนอร์ส่วนตัว", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏋️" },
  { en: "tutor", th: "ติวเตอร์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📖" },
  { en: "interview", th: "การสัมภาษณ์งาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎤" },
  { en: "resume", th: "ประวัติย่อ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📄" },
  { en: "cover letter", th: "จดหมายสมัครงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "✉️" },
  { en: "salary", th: "เงินเดือน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💰" },
  { en: "wage", th: "ค่าจ้าง", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💵" },
  { en: "promotion", th: "การเลื่อนตำแหน่ง", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📈" },
  { en: "demotion", th: "การลดตำแหน่ง", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "📉" },
  { en: "employee", th: "ลูกจ้าง", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🧑‍💼" },
  { en: "employer", th: "นายจ้าง", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🧑‍💼" },
  { en: "coworker", th: "เพื่อนร่วมงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "👥" },
  { en: "boss", th: "เจ้านาย", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "👔" },
  { en: "staff", th: "พนักงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🧑‍💼" },
  { en: "personnel", th: "บุคลากร", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧑‍💼" },
  { en: "workforce", th: "กำลังแรงงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "👥" },
  { en: "department", th: "แผนก", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🏢" },
  { en: "headquarters", th: "สำนักงานใหญ่", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "branch office", th: "สำนักงานสาขา", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "meeting", th: "การประชุม", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "🗓️" },
  { en: "conference call", th: "การประชุมทางโทรศัพท์", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📞" },
  { en: "overtime", th: "การทำงานล่วงเวลา", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "⏱️" },
  { en: "shift", th: "กะการทำงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🕒" },
  { en: "night shift", th: "กะกลางคืน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🌙" },
  { en: "break room", th: "ห้องพักพนักงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "☕" },
  { en: "cubicle", th: "ห้องทำงานส่วนตัวเล็กๆ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🗄️" },
  { en: "filing cabinet", th: "ตู้เก็บเอกสาร", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🗄️" },
  { en: "whiteboard", th: "ไวท์บอร์ด", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "⬜" },
  { en: "projector", th: "เครื่องฉายภาพ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📽️" },
  { en: "photocopier", th: "เครื่องถ่ายเอกสาร", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🖨️" },
  { en: "stapler", th: "ที่เย็บกระดาษ", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "📎" },
  { en: "paperclip", th: "คลิปหนีบกระดาษ", category: "อาชีพและที่ทำงาน", level: "A1", emoji: "📎" },
  { en: "business card", th: "นามบัตร", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💳" },
  { en: "conference room", th: "ห้องประชุม", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🏢" },
  { en: "teamwork", th: "การทำงานเป็นทีม", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🤝" },
  { en: "freelance", th: "อาชีพอิสระ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💻" },
  { en: "internship", th: "การฝึกงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎓" },
  { en: "apprenticeship", th: "การฝึกงานแบบฝึกทักษะ", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🛠️" },
  { en: "probation period", th: "ช่วงทดลองงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📋" },
  { en: "retirement", th: "การเกษียณอายุ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏖️" },
  { en: "pension", th: "เงินบำนาญ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💰" },
  { en: "workload", th: "ภาระงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📚" },
  { en: "performance review", th: "การประเมินผลงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📊" },
  { en: "job application", th: "ใบสมัครงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "📝" },
  { en: "qualification", th: "คุณสมบัติ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎓" },
  { en: "work experience", th: "ประสบการณ์ทำงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💼" },
  { en: "training program", th: "โปรแกรมฝึกอบรม", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🎓" },
  { en: "onboarding", th: "การปฐมนิเทศพนักงานใหม่", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "👋" },
  { en: "layoff", th: "การเลิกจ้าง", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📉" },
  { en: "resignation", th: "การลาออก", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "✍️" },
  { en: "recruitment", th: "การสรรหาบุคลากร", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧑‍💼" },
  { en: "candidate", th: "ผู้สมัคร", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🙋" },
  { en: "workplace", th: "สถานที่ทำงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🏢" },
  { en: "timesheet", th: "บันทึกเวลาทำงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🕒" },
  { en: "payroll", th: "บัญชีเงินเดือน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💵" },
  { en: "bonus", th: "โบนัส", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "🎁" },
  { en: "commission", th: "ค่านายหน้า", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💰" },
  { en: "labor union", th: "สหภาพแรงงาน", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "✊" },
  { en: "strike", th: "การนัดหยุดงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "✊" },
  { en: "telecommute", th: "การทำงานทางไกล", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🏠" },
  { en: "remote work", th: "การทำงานระยะไกล", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏠" },
  { en: "work-life balance", th: "ความสมดุลระหว่างงานกับชีวิต", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "⚖️" },
  { en: "minimum wage", th: "ค่าแรงขั้นต่ำ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "💵" },
  { en: "full-time job", th: "งานประจำ", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💼" },
  { en: "part-time job", th: "งานพาร์ทไทม์", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "💼" },
  { en: "self-employed", th: "ประกอบอาชีพอิสระ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🧑‍💼" },
  { en: "unemployed", th: "ว่างงาน", category: "อาชีพและที่ทำงาน", level: "A2", emoji: "😟" },
  { en: "unemployment benefit", th: "เงินช่วยเหลือคนว่างงาน", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "💰" },
  { en: "job fair", th: "งานมหกรรมจัดหางาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "networking", th: "การสร้างเครือข่าย", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🤝" },
  { en: "apprentice", th: "ผู้ฝึกงาน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🛠️" },
  { en: "subordinate", th: "ผู้ใต้บังคับบัญชา", category: "อาชีพและที่ทำงาน", level: "B2", emoji: "🧑‍💼" },
  { en: "corporation", th: "บริษัทมหาชน", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "enterprise", th: "กิจการ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🏢" },
  { en: "startup", th: "บริษัทสตาร์ทอัพ", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🚀" },
  { en: "nonprofit organization", th: "องค์กรไม่แสวงหาผลกำไร", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "🤲" },
  { en: "shareholder", th: "ผู้ถือหุ้น", category: "อาชีพและที่ทำงาน", level: "B1", emoji: "📈" },
  { en: "professor", th: "ศาสตราจารย์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "👨‍🏫" },
  { en: "lecturer", th: "อาจารย์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "👨‍🏫" },
  { en: "principal", th: "ผู้อำนวยการโรงเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "vice principal", th: "รองผู้อำนวยการโรงเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "headmaster", th: "ครูใหญ่ชาย", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "headmistress", th: "ครูใหญ่หญิง", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "dean", th: "คณบดี", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "school counselor", th: "ที่ปรึกษาโรงเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧑‍🏫" },
  { en: "school librarian", th: "บรรณารักษ์โรงเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📚" },
  { en: "schoolmate", th: "เพื่อนร่วมโรงเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🧑‍🤝‍🧑" },
  { en: "student", th: "นักเรียน/นักศึกษา", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🎒" },
  { en: "pupil", th: "นักเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🧒" },
  { en: "graduate", th: "บัณฑิต", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "undergraduate", th: "นักศึกษาปริญญาตรี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "postgraduate", th: "นักศึกษาระดับบัณฑิตศึกษา", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "freshman", th: "นักศึกษาปีหนึ่ง", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "sophomore", th: "นักศึกษาปีสอง", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "junior", th: "นักศึกษาปีสาม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "senior", th: "นักศึกษาปีสุดท้าย", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "mathematics", th: "คณิตศาสตร์", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "➕" },
  { en: "science", th: "วิทยาศาสตร์", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🔬" },
  { en: "English", th: "ภาษาอังกฤษ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🇬🇧" },
  { en: "Thai language", th: "ภาษาไทย", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🇹🇭" },
  { en: "history", th: "ประวัติศาสตร์", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📜" },
  { en: "geography", th: "ภูมิศาสตร์", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗺️" },
  { en: "biology", th: "ชีววิทยา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧬" },
  { en: "chemistry", th: "เคมี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧪" },
  { en: "physics", th: "ฟิสิกส์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "⚛️" },
  { en: "art", th: "ศิลปะ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🎨" },
  { en: "music", th: "ดนตรี", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🎵" },
  { en: "physical education", th: "พลศึกษา", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🏃" },
  { en: "computer science", th: "วิทยาการคอมพิวเตอร์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "💻" },
  { en: "literature", th: "วรรณคดี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📖" },
  { en: "social studies", th: "สังคมศึกษา", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🌍" },
  { en: "civics", th: "หน้าที่พลเมือง", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🏛️" },
  { en: "economics", th: "เศรษฐศาสตร์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📈" },
  { en: "philosophy", th: "ปรัชญา", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🤔" },
  { en: "psychology", th: "จิตวิทยา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧠" },
  { en: "foreign language", th: "ภาษาต่างประเทศ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗣️" },
  { en: "home economics", th: "คหกรรมศาสตร์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🍳" },
  { en: "health education", th: "สุขศึกษา", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "❤️" },
  { en: "religious studies", th: "ศาสนศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🙏" },
  { en: "drama", th: "นาฏศิลป์/ละคร", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🎭" },
  { en: "design and technology", th: "การออกแบบและเทคโนโลยี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "⚙️" },
  { en: "agriculture", th: "เกษตรกรรม", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🌾" },
  { en: "accounting", th: "การบัญชี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📊" },
  { en: "business studies", th: "ธุรกิจศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "💼" },
  { en: "environmental science", th: "วิทยาศาสตร์สิ่งแวดล้อม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🌱" },
  { en: "chemistry lab", th: "ห้องปฏิบัติการเคมี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧪" },
  { en: "chalk", th: "ชอล์ก", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "✏️" },
  { en: "chalkboard", th: "กระดานดำ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "⬛" },
  { en: "classroom", th: "ห้องเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🏫" },
  { en: "textbook", th: "หนังสือเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📘" },
  { en: "notebook", th: "สมุด", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📓" },
  { en: "pencil", th: "ดินสอ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "✏️" },
  { en: "pen", th: "ปากกา", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🖊️" },
  { en: "eraser", th: "ยางลบ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🧼" },
  { en: "ruler", th: "ไม้บรรทัด", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📏" },
  { en: "schoolbag", th: "กระเป๋านักเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🎒" },
  { en: "locker", th: "ตู้ล็อกเกอร์", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗄️" },
  { en: "school desk", th: "โต๊ะเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🪑" },
  { en: "school chair", th: "เก้าอี้เรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🪑" },
  { en: "bulletin board", th: "บอร์ดประกาศ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📌" },
  { en: "globe", th: "ลูกโลก", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🌍" },
  { en: "microscope", th: "กล้องจุลทรรศน์", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🔬" },
  { en: "calculator", th: "เครื่องคิดเลข", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🖩" },
  { en: "glue stick", th: "กาวแท่ง", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🖇️" },
  { en: "crayon", th: "สีเทียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🖍️" },
  { en: "marker pen", th: "ปากกาเมจิก", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🖊️" },
  { en: "scissors", th: "กรรไกร", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "✂️" },
  { en: "pencil case", th: "กล่องดินสอ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "✏️" },
  { en: "homework", th: "การบ้าน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📔" },
  { en: "worksheet", th: "ใบงาน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📄" },
  { en: "exercise book", th: "สมุดแบบฝึกหัด", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📕" },
  { en: "dictionary", th: "พจนานุกรม", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📖" },
  { en: "flashcard", th: "บัตรคำ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🃏" },
  { en: "kindergarten", th: "อนุบาล", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🧸" },
  { en: "preschool", th: "ก่อนวัยเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🧸" },
  { en: "elementary school", th: "โรงเรียนประถมศึกษา", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🏫" },
  { en: "primary school", th: "โรงเรียนประถม", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🏫" },
  { en: "middle school", th: "โรงเรียนมัธยมต้น", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "secondary school", th: "โรงเรียนมัธยมศึกษา", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "high school", th: "โรงเรียนมัธยมปลาย", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "vocational school", th: "โรงเรียนอาชีวศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "college", th: "วิทยาลัย", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🎓" },
  { en: "graduate school", th: "บัณฑิตวิทยาลัย", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "bachelor's degree", th: "ปริญญาตรี", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "master's degree", th: "ปริญญาโท", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "doctorate", th: "ปริญญาเอก", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "diploma", th: "ประกาศนียบัตร", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📜" },
  { en: "exam", th: "การสอบ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📝" },
  { en: "examination", th: "การสอบไล่", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📝" },
  { en: "test", th: "แบบทดสอบ", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "📝" },
  { en: "quiz", th: "แบบทดสอบสั้น", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "❓" },
  { en: "midterm exam", th: "การสอบกลางภาค", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📝" },
  { en: "final exam", th: "การสอบปลายภาค", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📝" },
  { en: "entrance exam", th: "การสอบเข้า", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📝" },
  { en: "grade", th: "เกรด", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🅰️" },
  { en: "GPA", th: "เกรดเฉลี่ยสะสม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📊" },
  { en: "transcript", th: "ใบแสดงผลการเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📄" },
  { en: "report card", th: "สมุดพก", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📋" },
  { en: "score", th: "คะแนน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "💯" },
  { en: "mark", th: "คะแนน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "✔️" },
  { en: "certificate", th: "ประกาศนียบัตรรับรอง", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📜" },
  { en: "credential", th: "หลักฐานคุณวุฒิ", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "📜" },
  { en: "retake exam", th: "การสอบซ่อม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🔁" },
  { en: "pop quiz", th: "การทดสอบกะทันหัน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "❗" },
  { en: "standardized test", th: "การทดสอบมาตรฐาน", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "📝" },
  { en: "oral exam", th: "การสอบปากเปล่า", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🗣️" },
  { en: "written exam", th: "การสอบข้อเขียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "✍️" },
  { en: "curriculum", th: "หลักสูตร", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📘" },
  { en: "school term", th: "ภาคเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗓️" },
  { en: "syllabus", th: "รายละเอียดรายวิชา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📄" },
  { en: "lecture", th: "การบรรยาย", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎙️" },
  { en: "seminar", th: "การสัมมนา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧑‍🏫" },
  { en: "workshop", th: "การอบรมเชิงปฏิบัติการ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🛠️" },
  { en: "tutorial", th: "บทเรียนสอนเสริม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📖" },
  { en: "assignment", th: "งานที่ได้รับมอบหมาย", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📝" },
  { en: "thesis", th: "วิทยานิพนธ์", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "📚" },
  { en: "dissertation", th: "ดุษฎีนิพนธ์", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "📚" },
  { en: "research paper", th: "งานวิจัย", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "📄" },
  { en: "essay", th: "เรียงความ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "✍️" },
  { en: "scholarship", th: "ทุนการศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "tuition fee", th: "ค่าเล่าเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "💰" },
  { en: "student loan", th: "เงินกู้ยืมเพื่อการศึกษา", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "💰" },
  { en: "academic year", th: "ปีการศึกษา", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗓️" },
  { en: "school year", th: "ปีการศึกษา (โรงเรียน)", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗓️" },
  { en: "class schedule", th: "ตารางเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🗓️" },
  { en: "attendance", th: "การเข้าเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "✅" },
  { en: "absence", th: "การขาดเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "❌" },
  { en: "detention", th: "การกักตัวหลังเลิกเรียน", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "⏳" },
  { en: "suspension", th: "การพักการเรียน", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🚫" },
  { en: "expulsion", th: "การไล่ออกจากโรงเรียน", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🚪" },
  { en: "graduation", th: "การสำเร็จการศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "graduation ceremony", th: "พิธีรับปริญญา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "alumni", th: "ศิษย์เก่า", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "faculty", th: "คณะวิชา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏛️" },
  { en: "academic department", th: "ภาควิชา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏛️" },
  { en: "extracurricular activity", th: "กิจกรรมนอกหลักสูตร", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎨" },
  { en: "field trip", th: "ทัศนศึกษา", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🚌" },
  { en: "study group", th: "กลุ่มติว", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "👥" },
  { en: "group project", th: "โครงงานกลุ่ม", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "👥" },
  { en: "presentation", th: "การนำเสนอ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📊" },
  { en: "plagiarism", th: "การลอกเลียนผลงาน", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🚫" },
  { en: "literacy", th: "การรู้หนังสือ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📖" },
  { en: "numeracy", th: "ความสามารถด้านตัวเลข", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🔢" },
  { en: "education system", th: "ระบบการศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "distance learning", th: "การเรียนทางไกล", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "💻" },
  { en: "online learning", th: "การเรียนออนไลน์", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "💻" },
  { en: "e-learning", th: "การเรียนรู้อิเล็กทรอนิกส์", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "💻" },
  { en: "blended learning", th: "การเรียนรู้แบบผสมผสาน", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "💻" },
  { en: "special education", th: "การศึกษาพิเศษ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "♿" },
  { en: "gifted education", th: "การศึกษาสำหรับเด็กอัจฉริยะ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🌟" },
  { en: "adult education", th: "การศึกษาผู้ใหญ่", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧑‍🎓" },
  { en: "lifelong learning", th: "การเรียนรู้ตลอดชีวิต", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📚" },
  { en: "vocational training", th: "การฝึกอาชีพ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🛠️" },
  { en: "work-study program", th: "โครงการทำงานควบคู่การเรียน", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "💼" },
  { en: "continuing education", th: "การศึกษาต่อเนื่อง", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "📚" },
  { en: "night school", th: "โรงเรียนภาคค่ำ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🌙" },
  { en: "home schooling", th: "การเรียนที่บ้าน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏠" },
  { en: "boarding school", th: "โรงเรียนประจำ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "international school", th: "โรงเรียนนานาชาติ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🌍" },
  { en: "public school", th: "โรงเรียนรัฐบาล", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "private school", th: "โรงเรียนเอกชน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "charter school", th: "โรงเรียนสัมปทาน", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🏫" },
  { en: "single-sex school", th: "โรงเรียนชายล้วน/หญิงล้วน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "coeducational school", th: "โรงเรียนสหศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "school uniform", th: "ชุดนักเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "👕" },
  { en: "school bus", th: "รถโรงเรียน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🚌" },
  { en: "recess", th: "เวลาพักระหว่างเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "⏸️" },
  { en: "break time", th: "เวลาพัก", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "⏸️" },
  { en: "lunch break", th: "พักกลางวัน", category: "การศึกษาและโรงเรียน", level: "A1", emoji: "🍱" },
  { en: "academic calendar", th: "ปฏิทินการศึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🗓️" },
  { en: "orientation", th: "การปฐมนิเทศ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "👋" },
  { en: "freshman orientation", th: "การปฐมนิเทศนักศึกษาใหม่", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "👋" },
  { en: "commencement", th: "พิธีจบการศึกษา", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "valedictorian", th: "นักเรียนที่มีเกรดสูงสุด", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🏅" },
  { en: "class rank", th: "อันดับในชั้นเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏅" },
  { en: "honor roll", th: "รายชื่อนักเรียนเกียรตินิยม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏅" },
  { en: "dean's list", th: "รายชื่อนักศึกษาเกียรตินิยม", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🏅" },
  { en: "academic probation", th: "การถูกพักสถานะทางวิชาการ", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "⚠️" },
  { en: "cheating", th: "การทุจริตในการสอบ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🚫" },
  { en: "cheat sheet", th: "เอกสารโกงข้อสอบ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📄" },
  { en: "study skills", th: "ทักษะการเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📚" },
  { en: "critical thinking", th: "การคิดเชิงวิพากษ์", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🧠" },
  { en: "literacy rate", th: "อัตราการรู้หนังสือ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "📊" },
  { en: "illiteracy", th: "การไม่รู้หนังสือ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🚫" },
  { en: "self-study", th: "การเรียนรู้ด้วยตนเอง", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📖" },
  { en: "revision", th: "การทบทวนบทเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🔁" },
  { en: "review session", th: "ช่วงทบทวนบทเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🔁" },
  { en: "office hours", th: "ช่วงเวลาให้คำปรึกษาของอาจารย์", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🕐" },
  { en: "academic advisor", th: "อาจารย์ที่ปรึกษา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧑‍🏫" },
  { en: "thesis advisor", th: "อาจารย์ที่ปรึกษาวิทยานิพนธ์", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🧑‍🏫" },
  { en: "peer review", th: "การประเมินโดยเพื่อน", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "👥" },
  { en: "coursework", th: "งานที่มอบหมายในรายวิชา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📝" },
  { en: "module", th: "หน่วยการเรียน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📦" },
  { en: "credit hour", th: "หน่วยกิต", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "elective course", th: "วิชาเลือก", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📘" },
  { en: "compulsory subject", th: "วิชาบังคับ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📘" },
  { en: "core subject", th: "วิชาหลัก", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📘" },
  { en: "minor", th: "วิชาโท", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "major", th: "วิชาเอก", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "double major", th: "สองวิชาเอก", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "lesson plan", th: "แผนการสอน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📋" },
  { en: "teaching method", th: "วิธีการสอน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🧑‍🏫" },
  { en: "pedagogy", th: "การสอน/ศาสตร์การสอน", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🧑‍🏫" },
  { en: "didactic", th: "เชิงสอน", category: "การศึกษาและโรงเรียน", level: "C2", emoji: "📖" },
  { en: "rote learning", th: "การเรียนรู้แบบท่องจำ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🔁" },
  { en: "experiential learning", th: "การเรียนรู้จากประสบการณ์", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🌟" },
  { en: "group discussion", th: "การอภิปรายกลุ่ม", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "💬" },
  { en: "debate", th: "การโต้วาที", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🗣️" },
  { en: "spelling bee", th: "การแข่งขันสะกดคำ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🔤" },
  { en: "science fair", th: "งานแสดงผลงานวิทยาศาสตร์", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🔬" },
  { en: "book report", th: "รายงานหนังสือ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📖" },
  { en: "oral presentation", th: "การนำเสนอด้วยวาจา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🗣️" },
  { en: "class test", th: "การทดสอบในชั้นเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📝" },
  { en: "mock exam", th: "การสอบจำลอง", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📝" },
  { en: "resit exam", th: "การสอบซ่อม (สอบใหม่)", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🔁" },
  { en: "exam hall", th: "ห้องสอบ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "exam paper", th: "ข้อสอบ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📄" },
  { en: "answer sheet", th: "กระดาษคำตอบ", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "📄" },
  { en: "multiple choice question", th: "ข้อสอบปรนัย", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "☑️" },
  { en: "open book exam", th: "การสอบแบบเปิดตำรา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📖" },
  { en: "closed book exam", th: "การสอบแบบปิดตำรา", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📕" },
  { en: "invigilator", th: "ผู้คุมสอบ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "👀" },
  { en: "proctor", th: "ผู้ควบคุมการสอบ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "👀" },
  { en: "academic integrity", th: "ความซื่อสัตย์ทางวิชาการ", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🎓" },
  { en: "academic dishonesty", th: "การทุจริตทางวิชาการ", category: "การศึกษาและโรงเรียน", level: "C1", emoji: "🚫" },
  { en: "compulsory education", th: "การศึกษาภาคบังคับ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "primary education", th: "การศึกษาระดับประถม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "secondary education", th: "การศึกษาระดับมัธยม", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🏫" },
  { en: "tertiary education", th: "การศึกษาระดับอุดมศึกษา", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "higher education", th: "การศึกษาระดับสูง", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🎓" },
  { en: "further education", th: "การศึกษาต่อเนื่องขั้นสูง", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🎓" },
  { en: "special needs education", th: "การศึกษาสำหรับผู้มีความต้องการพิเศษ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "♿" },
  { en: "remedial class", th: "ชั้นเรียนปรับพื้นฐาน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "📘" },
  { en: "enrichment program", th: "โครงการเสริมทักษะ", category: "การศึกษาและโรงเรียน", level: "B2", emoji: "🌟" },
  { en: "after-school program", th: "กิจกรรมหลังเลิกเรียน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "summer school", th: "โรงเรียนภาคฤดูร้อน", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "☀️" },
  { en: "exchange student", th: "นักเรียนแลกเปลี่ยน", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🌍" },
  { en: "foreign exchange program", th: "โครงการแลกเปลี่ยนต่างประเทศ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "🌍" },
  { en: "study abroad", th: "การเรียนต่อต่างประเทศ", category: "การศึกษาและโรงเรียน", level: "B1", emoji: "✈️" },
  { en: "campus", th: "วิทยาเขต", category: "การศึกษาและโรงเรียน", level: "A2", emoji: "🏫" },
  { en: "come apart", th: "แตกออกจากกัน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "come down", th: "ลดลง(ราคา)", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "come forward", th: "ออกมาเปิดเผยตัว", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "come off", th: "หลุดออก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "come over", th: "แวะมาที่บ้าน", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "come through", th: "ผ่านพ้นมาได้", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "cool down", th: "ทำให้เย็นลง", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "count on", th: "พึ่งพาได้", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "cross out", th: "ขีดฆ่าออก", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "deal with", th: "จัดการกับ", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "die out", th: "สูญพันธุ์ไป", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "dress up", th: "แต่งตัวสวยงาม", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "drop out", th: "ออกกลางคัน", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "eat out", th: "ทานอาหารนอกบ้าน", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" },
  { en: "end up", th: "ลงเอยด้วย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "face up to", th: "ยอมรับความจริง", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "fall apart", th: "แตกสลาย", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "fall behind", th: "ตามหลัง", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "fall for", th: "หลงรัก", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "fall out", th: "ทะเลาะกัน", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "fall through", th: "ล้มเหลวไม่สำเร็จ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "get across", th: "สื่อให้เข้าใจ", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "get ahead", th: "ก้าวหน้ากว่า", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "get around", th: "หลีกเลี่ยงปัญหา", category: "สำนวนและ Phrasal Verbs", level: "B2", emoji: "💬" },
  { en: "get by", th: "เอาตัวรอด", category: "สำนวนและ Phrasal Verbs", level: "B1", emoji: "💬" },
  { en: "get down", th: "ลงมา", category: "สำนวนและ Phrasal Verbs", level: "A2", emoji: "💬" },
  { en: "get in", th: "เข้าไปข้างใน", category: "สำนวนและ Phrasal Verbs", level: "A1", emoji: "💬" }
];
